-- Farmakodynamikken som mekanismekort (docs/farmakodynamikk-kort-kartlegging.md)
do $farmakodynamikk$
declare
  administrator uuid;
  konvertering jsonb;
  side uuid;
  e record;
  kort jsonb;
  posisjon bigint;
  objekt uuid;
begin
  select p.id into administrator from public.profiles p where p.username = 'peohol' and p.role = 'admin';
  if administrator is null then
    raise notice 'Fant ingen administrator med brukernavnet %, så importen hoppes over.', 'peohol';
    return;
  end if;
  perform set_config('request.jwt.claims', jsonb_build_object('sub', administrator, 'role', 'authenticated')::text, true);

  for konvertering in select * from jsonb_array_elements('[{"stoff":"amisulprid","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Høy affinitet til D"},{"type":"text","text":"2","marks":[{"type":"subscript"}]},{"type":"text","text":"- og D"},{"type":"text","text":"3","marks":[{"type":"subscript"}]},{"type":"text","text":"-reseptorer (antagonist). Ingen affinitet til D"},{"type":"text","text":"1","marks":[{"type":"subsc'
    'ript"}]},{"type":"text","text":"-, D"},{"type":"text","text":"4","marks":[{"type":"subscript"}]},{"type":"text","text":"-, D"},{"type":"text","text":"5","marks":[{"type":"subscript"}]},{"type":"text","text":"-, 5-HT-, α-, eller H"},{"type":"text","text":"1","marks":[{"type":"subscript"}]},{"type":"text","text":"-reseptorer, eller kolinerge reseptorer."}]}]},"kort":[{"maal":"D2-reseptor","effekt":"'
    'Antagonist","mekanisme":"antagonisme","retning":"ned","kvalifikasjon":"Høy affinitet"},{"maal":"D3-reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned","kvalifikasjon":"Høy affinitet"},{"maal":"D1-reseptor","effekt":"Ingen effekt","mekanisme":"ingen_effekt","retning":"ingen","kvalifikasjon":"Ingen affinitet"},{"maal":"D4-reseptor","effekt":"Ingen effekt","mekanisme":"ingen_eff'
    'ekt","retning":"ingen","kvalifikasjon":"Ingen affinitet"},{"maal":"D5-reseptor","effekt":"Ingen effekt","mekanisme":"ingen_effekt","retning":"ingen","kvalifikasjon":"Ingen affinitet"},{"maal":"5-HT-reseptorer","effekt":"Ingen effekt","mekanisme":"ingen_effekt","retning":"ingen","kvalifikasjon":"Ingen affinitet","merknad":"Subtype ikke oppgitt"},{"maal":"α-adrenerge reseptorer","effekt":"Ingen effe'
    'kt","mekanisme":"ingen_effekt","retning":"ingen","kvalifikasjon":"Ingen affinitet","merknad":"Subtype ikke oppgitt"},{"maal":"H1-reseptor","effekt":"Ingen effekt","mekanisme":"ingen_effekt","retning":"ingen","kvalifikasjon":"Ingen affinitet"},{"maal":"Kolinerge reseptorer","effekt":"Ingen effekt","mekanisme":"ingen_effekt","retning":"ingen","kvalifikasjon":"Ingen affinitet","merknad":"Subtype ikke'
    ' oppgitt"}]},{"stoff":"amitriptylin","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Hemmer reopptak av noradrenalin og serotonin. Også virkning på natrium-, kalium- og NMDA-kanaler. Antagonist på muskarin- og histamin H1-reseptorer."}]},{"type":"paragraph","content":[{"type":"text","text":"Aktiv metabolitt: nortriptylin."}]}]},"kort":[{"maal":"Noradrenalinreop'
    'ptak / NET","effekt":"Hemmer reopptak","mekanisme":"reopptakshemming","retning":"ned","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Aktiv metabolitt: nortriptylin."}]}]}},{"maal":"Serotoninreopptak / SERT","effekt":"Hemmer reopptak","mekanisme":"reopptakshemming","retning":"ned"},{"maal":"Natriumkanaler","effekt":"Påvirker","mekanisme":"ionekanalpavirkni'
    'ng","retning":"ukjent","merknad":"Teksten sier bare «virkning på»"},{"maal":"Kaliumkanaler","effekt":"Påvirker","mekanisme":"ionekanalpavirkning","retning":"ukjent","merknad":"Teksten sier bare «virkning på»"},{"maal":"NMDA-reseptor/kanal","effekt":"Påvirker","mekanisme":"ionekanalpavirkning","retning":"ukjent","merknad":"Teksten sier bare «virkning på NMDA-kanaler»"},{"maal":"Muskarinreseptorer",'
    '"effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned"},{"maal":"Histamin H1-reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned"}]},{"stoff":"amlodipin","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Langtidsvirkende kalsiumantagonist av dihydropyridintype med selektivitet for vaskulær glatt muskel."}]},{"type":"paragraph","conte'
    'nt":[{"type":"text","text":"Amlodipin binder seg til spenningstyrte L(low)-type kalsiumkanaler i sarcolemma i glatte muskelceller og hemmer kalsiuminnstrømming i cellene. Dette fører til ytterligere redusert kalsiumfrigivelse fra sarkoplasmatisk retikulum til cytosol. Reduksjon i intracellulært fritt kalsium reduserer glatt muskelkontraksjon, dvs. vil gi vasodilatasjon, derved redusert perifer res'
    'istens og fall i blodtrykk."}]},{"type":"paragraph","content":[{"type":"text","text":"Ved veldig høye serumkonsentrasjoner av amlodipin bindes også legemiddelet til hjertemuskelceller og kan derfor gi redusert hjerterytme (negativ kronotropisk effekt) og hjertemuskelkontraksjon (negativ inotrop effekt) dvs. kan gi hjertesvikt."}]},{"type":"paragraph","content":[{"type":"text","text":"Kalsiumantago'
    'nister av dihydropyridintype reduserer systolisk blodtrykk og diastolisk blodtrykk med ca. 15,6 ± 5,3 / 10,3 ± 2,6 mmHg (gjennomsnitt ± SD), ifølge metastudie fra Wu et al. (2005)."}]}]},"kort":[{"maal":"Spenningsstyrte L-type Ca2+-kanaler","effekt":"Hemmer kalsiuminnstrømming / blokkerer kanalaktivitet","mekanisme":"kanalblokkering","retning":"ned","merknad":"Primært vaskulær glatt muskulatur; ve'
    'd svært høye konsentrasjoner også hjertemuskel","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Langtidsvirkende kalsiumantagonist av dihydropyridintype med selektivitet for vaskulær glatt muskel."}]},{"type":"paragraph","content":[{"type":"text","text":"Amlodipin binder seg til spenningstyrte L(low)-type kalsiumkanaler i sarcolemma i glatte muskelceller o'
    'g hemmer kalsiuminnstrømming i cellene. Dette fører til ytterligere redusert kalsiumfrigivelse fra sarkoplasmatisk retikulum til cytosol. Reduksjon i intracellulært fritt kalsium reduserer glatt muskelkontraksjon, dvs. vil gi vasodilatasjon, derved redusert perifer resistens og fall i blodtrykk."}]},{"type":"paragraph","content":[{"type":"text","text":"Ved veldig høye serumkonsentrasjoner av amlod'
    'ipin bindes også legemiddelet til hjertemuskelceller og kan derfor gi redusert hjerterytme (negativ kronotropisk effekt) og hjertemuskelkontraksjon (negativ inotrop effekt) dvs. kan gi hjertesvikt."}]},{"type":"paragraph","content":[{"type":"text","text":"Kalsiumantagonister av dihydropyridintype reduserer systolisk blodtrykk og diastolisk blodtrykk med ca. 15,6 ± 5,3 / 10,3 ± 2,6 mmHg (gjennomsni'
    'tt ± SD), ifølge metastudie fra Wu et al. (2005)."}]}]}}]},{"stoff":"aripiprazol","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Partiell agonist på D"},{"type":"text","text":"2","marks":[{"type":"subscript"}]},{"type":"text","text":"- og 5-HT"},{"type":"text","text":"1A","marks":[{"type":"subscript"}]},{"type":"text","text":"-reseptorer. Antagonist på 5-HT"},'
    '{"type":"text","text":"2A","marks":[{"type":"subscript"}]},{"type":"text","text":"-reseptorer."}]},{"type":"paragraph","content":[{"type":"text","text":"Binder med høy affinitet til D"},{"type":"text","text":"2","marks":[{"type":"subscript"}]},{"type":"text","text":"-reseptoren. Bytte fra potent D"},{"type":"text","text":"2","marks":[{"type":"subscript"}]},{"type":"text","text":"-antagonist til ar'
    'ipiprazol kan paradoksalt gi redusert D"},{"type":"text","text":"2","marks":[{"type":"subscript"}]},{"type":"text","text":"-blokkade og økt symptomtrykk når dosen av aripiprazol økes."}]},{"type":"paragraph","content":[{"type":"text","text":"Aktiv metabolitt: dehydroaripiprazol."}]}]},"kort":[{"maal":"D2-reseptor","effekt":"Partiell agonist","mekanisme":"partiell_agonisme","retning":"opp","kvalifi'
    'kasjon":"Høy affinitet","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Bytte fra potent D"},{"type":"text","text":"2","marks":[{"type":"subscript"}]},{"type":"text","text":"-antagonist til aripiprazol kan paradoksalt gi redusert D"},{"type":"text","text":"2","marks":[{"type":"subscript"}]},{"type":"text","text":"-blokkade og økt symptomtrykk når dosen av '
    'aripiprazol økes."}]},{"type":"paragraph","content":[{"type":"text","text":"Aktiv metabolitt: dehydroaripiprazol."}]}]}},{"maal":"5-HT1A-reseptor","effekt":"Partiell agonist","mekanisme":"partiell_agonisme","retning":"opp"},{"maal":"5-HT2A-reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned"}]},{"stoff":"atenolol","fra":{"type":"doc","content":[{"type":"paragraph","content":[{'
    '"type":"text","text":"Selektiv beta-1-adrenerg reseptorantagonist."}]},{"type":"paragraph","content":[{"type":"text","text":"Hovedmekanismen er konkurrerende hemming av katekolaminer ved adrenerge betareseptorer i hjerte-karsystemet."}]},{"type":"paragraph","content":[{"type":"text","text":"Ved reduksjon av hjertefrekvens og kontraktilitet, nedsettes hjertets arbeid og derved også oksygenbehovet. '
    'Beta2-reseptorer i lunger og kar påvirkes lite. Beta2-mediert bronkodilatasjon og den vasodilaterende effekt av adrenalin blokkeres ikke."}]}]},"kort":[{"maal":"β1-adrenerg reseptor","effekt":"Konkurrerende antagonist","mekanisme":"kompetitiv_antagonisme","retning":"ned","kvalifikasjon":"Selektiv","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Hovedmekani'
    'smen er konkurrerende hemming av katekolaminer ved adrenerge betareseptorer i hjerte-karsystemet."}]},{"type":"paragraph","content":[{"type":"text","text":"Ved reduksjon av hjertefrekvens og kontraktilitet, nedsettes hjertets arbeid og derved også oksygenbehovet."}]}]}},{"maal":"β2-adrenerge reseptorer","effekt":"Liten/ingen relevant blokkade","mekanisme":"ingen_effekt","retning":"ingen","kvalifik'
    'asjon":"Påvirkes lite","merknad":"β2-mediert bronkodilatasjon og adrenalins vasodilaterende effekt blokkeres ikke","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Beta2-reseptorer i lunger og kar påvirkes lite. Beta2-mediert bronkodilatasjon og den vasodilaterende effekt av adrenalin blokkeres ikke."}]}]}}]},{"stoff":"bendroflumetiazid","fra":{"type":"doc"'
    ',"content":[{"type":"paragraph","content":[{"type":"text","text":"Tiazid som hemmer Na+/Cl- transporter i distale tubuli. Økt diurese (tap av blodvolum initialt) og venedilatasjon. Gir mindre diurese sammenlignet med slyngediuretika, ettersom reabsorpsjonen er mindre i distale tubuli. Nedsetter kalsiumutskillelsen i urinen (kan derfor forebygge nyresten). Nedsetter nyrenes evne til å fortynne urin'
    'en, som til vanlig skjer i distale tubuli. Tilsatt kaliumklorid minsker risiko for kaliummangel."}]},{"type":"paragraph","content":[{"type":"text","text":"Siden tiazider virker mer distalt i nefronet, hvor mye av saltene og vannet allerede er reabsorbert, gir tiazider en mindre kraftig vanndrivende effekt sammenlignet med slyngediuretika."}]}]},"kort":[{"maal":"Na+/Cl−-kotransportør i distale tubu'
    'li","effekt":"Hemmer","mekanisme":"kotransporterhemming","retning":"ned","merknad":"Øker diurese; reduserer kalsiumutskillelse i urin og nyrenes evne til å fortynne urin","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Tiazid som hemmer Na+/Cl- transporter i distale tubuli. Økt diurese (tap av blodvolum initialt) og venedilatasjon. Gir mindre diurese samme'
    'nlignet med slyngediuretika, ettersom reabsorpsjonen er mindre i distale tubuli. Nedsetter kalsiumutskillelsen i urinen (kan derfor forebygge nyresten). Nedsetter nyrenes evne til å fortynne urinen, som til vanlig skjer i distale tubuli. Tilsatt kaliumklorid minsker risiko for kaliummangel."}]},{"type":"paragraph","content":[{"type":"text","text":"Siden tiazider virker mer distalt i nefronet, hvor'
    ' mye av saltene og vannet allerede er reabsorbert, gir tiazider en mindre kraftig vanndrivende effekt sammenlignet med slyngediuretika."}]}]}}]},{"stoff":"bisoprolol","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Selektiv beta-1-adrenerg reseptorantagonist."}]},{"type":"paragraph","content":[{"type":"text","text":"Bisoprolol er et meget selektivt beta-1-adren'
    'oseptorblokkerende middel uten egenstimulerende aktivitet og uten signifikant membranstabiliserende effekt. Det viser kun lav affinitet til beta2-reseptorer i glatt muskulatur i bronkier og blodårer, samt til beta2-reseptorer som er involvert i metabolsk regulering. Bisoprolol forventes derfor generelt ikke å påvirke luftveismotstand og beta2-medierte metabolske effekter."}]},{"type":"paragraph","'
    'content":[{"type":"text","text":"Bisoprolol hemmer responsen til sympatisk aktivering ved å hemme betareseptorene i hjertet. Dette fører til redusert hjerterytme og kontraktilitet, noe som igjen reduserer hjertemuskelens oksygenbehov."}]}]},"kort":[{"maal":"β1-adrenerg reseptor","effekt":"Antagonist / blokkerer","mekanisme":"antagonisme","retning":"ned","kvalifikasjon":"Meget selektiv","merknad":"'
    'Ingen egenstimulerende aktivitet","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Bisoprolol er et meget selektivt beta-1-adrenoseptorblokkerende middel uten egenstimulerende aktivitet og uten signifikant membranstabiliserende effekt."}]},{"type":"paragraph","content":[{"type":"text","text":"Bisoprolol hemmer responsen til sympatisk aktivering ved å hemme '
    'betareseptorene i hjertet. Dette fører til redusert hjerterytme og kontraktilitet, noe som igjen reduserer hjertemuskelens oksygenbehov."}]}]}},{"maal":"β2-adrenerge reseptorer","effekt":"Lav affinitet / forventet liten effekt","mekanisme":"ingen_effekt","retning":"ingen","merknad":"Generelt ikke forventet å påvirke luftveismotstand eller β2-medierte metabolske effekter","dokument":{"type":"doc","'
    'content":[{"type":"paragraph","content":[{"type":"text","text":"Det viser kun lav affinitet til beta2-reseptorer i glatt muskulatur i bronkier og blodårer, samt til beta2-reseptorer som er involvert i metabolsk regulering. Bisoprolol forventes derfor generelt ikke å påvirke luftveismotstand og beta2-medierte metabolske effekter."}]}]}}]},{"stoff":"brekspiprazol","fra":{"type":"doc","content":[{"ty'
    'pe":"paragraph","content":[{"type":"text","text":"Partiell agonist på D"},{"type":"text","text":"2","marks":[{"type":"subscript"}]},{"type":"text","text":"- og 5-HT"},{"type":"text","text":"1A","marks":[{"type":"subscript"}]},{"type":"text","text":"-reseptorer. Antagonist på 5-HT"},{"type":"text","text":"2A","marks":[{"type":"subscript"}]},{"type":"text","text":"- og noradrenerge reseptorer."}]},{'
    '"type":"paragraph","content":[{"type":"text","text":"Binder med høy affinitet til D"},{"type":"text","text":"2","marks":[{"type":"subscript"}]},{"type":"text","text":"-reseptoren. Bytte fra potent D"},{"type":"text","text":"2","marks":[{"type":"subscript"}]},{"type":"text","text":"-antagonist til brekspiprazol kan paradoksalt gi redusert D"},{"type":"text","text":"2","marks":[{"type":"subscript"}]'
    '},{"type":"text","text":"-blokkade og økt symptomtrykk, på samme måte som for aripiprazol."}]},{"type":"paragraph","content":[{"type":"text","text":"Metabolitt: DM-3411, bidrar ikke til den terapeutiske effekten."}]}]},"kort":[{"maal":"D2-reseptor","effekt":"Partiell agonist","mekanisme":"partiell_agonisme","retning":"opp","kvalifikasjon":"Høy affinitet","dokument":{"type":"doc","content":[{"type"'
    ':"paragraph","content":[{"type":"text","text":"Bytte fra potent D"},{"type":"text","text":"2","marks":[{"type":"subscript"}]},{"type":"text","text":"-antagonist til brekspiprazol kan paradoksalt gi redusert D"},{"type":"text","text":"2","marks":[{"type":"subscript"}]},{"type":"text","text":"-blokkade og økt symptomtrykk, på samme måte som for aripiprazol."}]},{"type":"paragraph","content":[{"type"'
    ':"text","text":"Metabolitt: DM-3411, bidrar ikke til den terapeutiske effekten."}]}]}},{"maal":"5-HT1A-reseptor","effekt":"Partiell agonist","mekanisme":"partiell_agonisme","retning":"opp"},{"maal":"5-HT2A-reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned"},{"maal":"Noradrenerge reseptorer","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned","merknad":"Subtype ik'
    'ke oppgitt"}]},{"stoff":"bumetanid","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Slyngediuretikum, hemmer Na+/K+/2Cl- symporter i tubuliceller hovedsakelig i oppadgående del av Henles sløyfe. I tillegg gir slyngediuretika venedilatasjon med redusert venøs tilbakestrømming til hjerte (reduserer preload), og dermed redusert belastning på hjerte. Slyngediuretik'
    'a hemmer nyrenes evne til å konsentrere urinen, ved at den ødelegger gradienten i interstitiet."}]},{"type":"paragraph","content":[{"type":"text","text":"Bumetanid har bedre oral biotilgjengelighet, halveringstiden øker ikke like mye med grad av nyresvikt og legemidlet er 40 ganger mer potent enn furosemid."}]}]},"kort":[{"maal":"Na+/K+/2Cl−-kotransportør i oppadgående Henles sløyfe","effekt":"Hem'
    'mer","mekanisme":"kotransporterhemming","retning":"ned","merknad":"Slyngediuretikum","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Slyngediuretikum, hemmer Na+/K+/2Cl- symporter i tubuliceller hovedsakelig i oppadgående del av Henles sløyfe. I tillegg gir slyngediuretika venedilatasjon med redusert venøs tilbakestrømming til hjerte (reduserer preload), o'
    'g dermed redusert belastning på hjerte. Slyngediuretika hemmer nyrenes evne til å konsentrere urinen, ved at den ødelegger gradienten i interstitiet."}]},{"type":"paragraph","content":[{"type":"text","text":"Bumetanid har bedre oral biotilgjengelighet, halveringstiden øker ikke like mye med grad av nyresvikt og legemidlet er 40 ganger mer potent enn furosemid."}]}]}}]},{"stoff":"bupropion","fra":{'
    '"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Selektiv noradrenalin- og dopamin-reopptakshemmer (NDRI). Minimal effekt på reopptak av serotonin."}]}]},"kort":[{"maal":"Noradrenalinreopptak / NET","effekt":"Hemmer reopptak","mekanisme":"reopptakshemming","retning":"ned","kvalifikasjon":"Selektiv NDRI"},{"maal":"Dopaminreopptak / DAT","effekt":"Hemmer reopptak","mekan'
    'isme":"reopptakshemming","retning":"ned","kvalifikasjon":"Selektiv NDRI"},{"maal":"Serotoninreopptak / SERT","effekt":"Minimal effekt","mekanisme":"transportorpavirkning","retning":"ukjent","kvalifikasjon":"Minimal effekt på reopptak"}]},{"stoff":"citalopram","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Kraftig og selektiv hemmer av gjenopptak av serotonin ('
    'SSRI). Ingen effekt på reopptak av noradrenalin, dopamin eller GABA. Ingen effekt på muskarine, histaminerge eller adrenerge reseptorer."}]}]},"kort":[{"maal":"Serotoninreopptak / SERT","effekt":"Hemmer reopptak","mekanisme":"reopptakshemming","retning":"ned","kvalifikasjon":"Kraftig og selektiv"},{"maal":"Noradrenalinreopptak / NET","effekt":"Ingen effekt","mekanisme":"ingen_effekt","retning":"in'
    'gen"},{"maal":"Dopaminreopptak / DAT","effekt":"Ingen effekt","mekanisme":"ingen_effekt","retning":"ingen"},{"maal":"GABA-reopptak","effekt":"Ingen effekt","mekanisme":"ingen_effekt","retning":"ingen"},{"maal":"Muskarinreseptorer","effekt":"Ingen effekt","mekanisme":"ingen_effekt","retning":"ingen"},{"maal":"Histaminreseptorer","effekt":"Ingen effekt","mekanisme":"ingen_effekt","retning":"ingen"},'
    '{"maal":"Adrenerge reseptorer","effekt":"Ingen effekt","mekanisme":"ingen_effekt","retning":"ingen"}]},{"stoff":"diltiazem","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Kalsiumantagonist, benzotiazepintype. Hemmer selektivt langsomme spenningstyrte L-type kalsiumkanaler i sarcolemma i både hjertemuskelceller og glatte muskelceller. Dette fører også til mindr'
    'e frigivelse av kalsiumioner intracellulært. Effekten er vasodilatasjon, nedsatt perifer motstand og reduksjon i blodtrykk. Vasodilatasjon skjer også i kransarteriene."}]},{"type":"paragraph","content":[{"type":"text","text":"Redusert smerte ved angina pectoris fordi diltiazem reduserer hjertets pumpekraft som betyr redusert oksygenbehov og samtidig øker blodforsyningen til hjertemuskelen pga. vas'
    'odilatasjon."}]},{"type":"paragraph","content":[{"type":"text","text":"Antiarytmisk effekt fordi diltiazem spesifikt påvirker hjertes ledningssystem: forsinker ledningstid i AV-knuten og setter ned frekvens i sinusknuten."}]},{"type":"paragraph","content":[{"type":"text","text":"Blodtrykksreduksjon ved monoterapi, sittende systolisk/diastolisk blodtrykk: 14,4 ± 2,1 / 12,1 ± 2,8 mmHg (gjennomsnitt '
    '± SD), ifølge metastudien fra Wu et al. (2005)."}]}]},"kort":[{"maal":"Spenningsstyrte L-type Ca2+-kanaler","effekt":"Hemmer / blokkerer","mekanisme":"kanalblokkering","retning":"ned","merknad":"Gjelder både hjertemuskelceller og glatt muskulatur; gir vasodilatasjon og påvirker AV- og sinusknute","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Kalsiumantag'
    'onist, benzotiazepintype. Hemmer selektivt langsomme spenningstyrte L-type kalsiumkanaler i sarcolemma i både hjertemuskelceller og glatte muskelceller. Dette fører også til mindre frigivelse av kalsiumioner intracellulært. Effekten er vasodilatasjon, nedsatt perifer motstand og reduksjon i blodtrykk. Vasodilatasjon skjer også i kransarteriene."}]},{"type":"paragraph","content":[{"type":"text","te'
    'xt":"Redusert smerte ved angina pectoris fordi diltiazem reduserer hjertets pumpekraft som betyr redusert oksygenbehov og samtidig øker blodforsyningen til hjertemuskelen pga. vasodilatasjon."}]},{"type":"paragraph","content":[{"type":"text","text":"Antiarytmisk effekt fordi diltiazem spesifikt påvirker hjertes ledningssystem: forsinker ledningstid i AV-knuten og setter ned frekvens i sinusknuten.'
    '"}]},{"type":"paragraph","content":[{"type":"text","text":"Blodtrykksreduksjon ved monoterapi, sittende systolisk/diastolisk blodtrykk: 14,4 ± 2,1 / 12,1 ± 2,8 mmHg (gjennomsnitt ± SD), ifølge metastudien fra Wu et al. (2005)."}]}]}}]},{"stoff":"doksazosin","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Selektiv alfa-1-adrenerg reseptorantagonist."}]},{"type":'
    '"paragraph","content":[{"type":"text","text":"Selektiv og kompetitiv postsynaptisk alfa1-reseptorblokade. Senker perifer karmotstand samt relakserer glatt muskulatur i stroma, kapsel og blærehals."}]},{"type":"paragraph","content":[{"type":"text","text":"Doksazosin senker blodtrykket som følge av reduksjon i total perifer karmotstand. Bedrer benign prostatahyperplasi (BPH) symptomatisk ved selekti'
    'v alfa1-adrenoseptor blokade i glatt muskulatur i stroma, kapsel og blærehals."}]}]},"kort":[{"maal":"Postsynaptisk α1-adrenerg reseptor","effekt":"Konkurrerende antagonist","mekanisme":"kompetitiv_antagonisme","retning":"ned","kvalifikasjon":"Selektiv","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Selektiv og kompetitiv postsynaptisk alfa1-reseptorbloka'
    'de. Senker perifer karmotstand samt relakserer glatt muskulatur i stroma, kapsel og blærehals."}]},{"type":"paragraph","content":[{"type":"text","text":"Doksazosin senker blodtrykket som følge av reduksjon i total perifer karmotstand. Bedrer benign prostatahyperplasi (BPH) symptomatisk ved selektiv alfa1-adrenoseptor blokade i glatt muskulatur i stroma, kapsel og blærehals."}]}]}}]},{"stoff":"doks'
    'epin","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Dårlig kjent. Hemmer trolig reopptak av noradrenalin."}]},{"type":"paragraph","content":[{"type":"text","text":"Aktiv metabolitt: desmetyldoksepin."}]}]},"kort":[{"maal":"Noradrenalinreopptak / NET","effekt":"Hemmer trolig reopptak","mekanisme":"reopptakshemming","retning":"ned","merknad":"Mekanismen beskriv'
    'es som dårlig kjent","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Aktiv metabolitt: desmetyldoksepin."}]}]}}]},{"stoff":"duloksetin","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Hemmer reopptak av serotonin og noradrenalin (SNRI). Svak hemmer av reopptak av dopamin. Ikke signifikant affinitet for histaminerge, dop'
    'aminerge, kolinerge eller adrenerge reseptorer. Smertehemmende effekt antas å skyldes potensering av nedadgående smertehemmende baner i CNS."}]}]},"kort":[{"maal":"Serotoninreopptak / SERT","effekt":"Hemmer reopptak","mekanisme":"reopptakshemming","retning":"ned","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Smertehemmende effekt antas å skyldes potenser'
    'ing av nedadgående smertehemmende baner i CNS."}]}]}},{"maal":"Noradrenalinreopptak / NET","effekt":"Hemmer reopptak","mekanisme":"reopptakshemming","retning":"ned"},{"maal":"Dopaminreopptak / DAT","effekt":"Hemmer reopptak svakt","mekanisme":"reopptakshemming","retning":"ned","kvalifikasjon":"Svak effekt"},{"maal":"Histaminreseptorer","effekt":"Ingen signifikant effekt","mekanisme":"ingen_effekt"'
    ',"retning":"ingen","kvalifikasjon":"Ikke signifikant affinitet"},{"maal":"Dopaminreseptorer","effekt":"Ingen signifikant effekt","mekanisme":"ingen_effekt","retning":"ingen","kvalifikasjon":"Ikke signifikant affinitet"},{"maal":"Kolinerge reseptorer","effekt":"Ingen signifikant effekt","mekanisme":"ingen_effekt","retning":"ingen","kvalifikasjon":"Ikke signifikant affinitet"},{"maal":"Adrenerge res'
    'eptorer","effekt":"Ingen signifikant effekt","mekanisme":"ingen_effekt","retning":"ingen","kvalifikasjon":"Ikke signifikant affinitet"}]},{"stoff":"enalapril","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"ACE-hemmer (angiotensinkonverterende enzymhemmer). Hemming av ACE reduserer mengden angiotensin II i plasma, som igjen gir økt reninaktivitet (pga. opphør a'
    'v negativ feedback på reninfrisetting) og redusert aldosteronutskillelse. Reduserer den perifere arterielle karmotstanden. Blokkerer nedbrytningen av bradykinin."}]},{"type":"paragraph","content":[{"type":"text","text":"ACE-hemmere senker ikke blodtrykket like effektivt hos pasienter av afrikansk opprinnelse pga. en høyere prevalens av mulig lavere reninnivåer hos hypertonikere av afrikansk opprin'
    'nelse."}]}]},"kort":[{"maal":"ACE (angiotensinkonverterende enzym)","effekt":"Hemmer","mekanisme":"enzymhemming","retning":"ned","merknad":"Reduserer angiotensin II og aldosteron; reduserer også nedbrytning av bradykinin","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"ACE-hemmer (angiotensinkonverterende enzymhemmer). Hemming av ACE reduserer mengden angi'
    'otensin II i plasma, som igjen gir økt reninaktivitet (pga. opphør av negativ feedback på reninfrisetting) og redusert aldosteronutskillelse. Reduserer den perifere arterielle karmotstanden. Blokkerer nedbrytningen av bradykinin."}]},{"type":"paragraph","content":[{"type":"text","text":"ACE-hemmere senker ikke blodtrykket like effektivt hos pasienter av afrikansk opprinnelse pga. en høyere prevale'
    'ns av mulig lavere reninnivåer hos hypertonikere av afrikansk opprinnelse."}]}]}}]},{"stoff":"eplerenon","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Aldosteronantagonist, som resulterer i mindre reabsorpsjon av natrium og væske, og mindre kaliumutskillelse, altså mer kalium tilbake til blod. Den viktigste effekten er den beskyttende effekten mot remodelerin'
    'gen i hjerte, ved å blokkere aldosteronens langtidsvirkning i hjertet som har vist seg å være skadelig. Eplerenon har derfor som betablokkere og ACE-hemmere en beskyttende effekt mot langtidsskade av aktivering av RAAS-systemet i hjertet."}]},{"type":"paragraph","content":[{"type":"text","text":"Full antihypertensiv effekt innen fire uker."}]}]},"kort":[{"maal":"Aldosteron-/mineralokortikoidresept'
    'or","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned","merknad":"Mindre Na+/væskereabsorpsjon og mindre K+-utskillelse; beskyttende effekt mot remodellering i hjertet","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Aldosteronantagonist, som resulterer i mindre reabsorpsjon av natrium og væske, og mindre kaliumutskillelse, altså mer kalium ti'
    'lbake til blod. Den viktigste effekten er den beskyttende effekten mot remodeleringen i hjerte, ved å blokkere aldosteronens langtidsvirkning i hjertet som har vist seg å være skadelig. Eplerenon har derfor som betablokkere og ACE-hemmere en beskyttende effekt mot langtidsskade av aktivering av RAAS-systemet i hjertet."}]},{"type":"paragraph","content":[{"type":"text","text":"Full antihypertensiv '
    'effekt innen fire uker."}]}]}}]},{"stoff":"escitalopram","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Kraftig og selektiv hemmer av gjenopptak av serotonin (SSRI). Ingen effekt på reopptak av noradrenalin, dopamin eller GABA. Ingen effekt på muskarine, histaminerge eller adrenerge reseptorer."}]}]},"kort":[{"maal":"Serotoninreopptak / SERT","effekt":"Hemmer '
    'reopptak","mekanisme":"reopptakshemming","retning":"ned","kvalifikasjon":"Kraftig og selektiv"},{"maal":"Noradrenalinreopptak / NET","effekt":"Ingen effekt","mekanisme":"ingen_effekt","retning":"ingen"},{"maal":"Dopaminreopptak / DAT","effekt":"Ingen effekt","mekanisme":"ingen_effekt","retning":"ingen"},{"maal":"GABA-reopptak","effekt":"Ingen effekt","mekanisme":"ingen_effekt","retning":"ingen"},{'
    '"maal":"Muskarinreseptorer","effekt":"Ingen effekt","mekanisme":"ingen_effekt","retning":"ingen"},{"maal":"Histaminreseptorer","effekt":"Ingen effekt","mekanisme":"ingen_effekt","retning":"ingen"},{"maal":"Adrenerge reseptorer","effekt":"Ingen effekt","mekanisme":"ingen_effekt","retning":"ingen"}]},{"stoff":"fluoksetin","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","'
    'text":"Selektiv reopptakshemmer av serotonin (SSRI). Ingen affinitet til adrenerge, serotonerge, dopaminerge, histaminerge, muskarine eller GABA-reseptorer."}]},{"type":"paragraph","content":[{"type":"text","text":"Aktiv metabolitt: norfluoksetin."}]}]},"kort":[{"maal":"Serotoninreopptak / SERT","effekt":"Hemmer reopptak","mekanisme":"reopptakshemming","retning":"ned","kvalifikasjon":"Selektiv","d'
    'okument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Aktiv metabolitt: norfluoksetin."}]}]}},{"maal":"Adrenerge reseptorer","effekt":"Ingen effekt","mekanisme":"ingen_effekt","retning":"ingen","kvalifikasjon":"Ingen affinitet"},{"maal":"Serotonerge reseptorer","effekt":"Ingen effekt","mekanisme":"ingen_effekt","retning":"ingen","kvalifikasjon":"Ingen affinitet"},'
    '{"maal":"Dopaminerge reseptorer","effekt":"Ingen effekt","mekanisme":"ingen_effekt","retning":"ingen","kvalifikasjon":"Ingen affinitet"},{"maal":"Histaminerge reseptorer","effekt":"Ingen effekt","mekanisme":"ingen_effekt","retning":"ingen","kvalifikasjon":"Ingen affinitet"},{"maal":"Muskarine reseptorer","effekt":"Ingen effekt","mekanisme":"ingen_effekt","retning":"ingen","kvalifikasjon":"Ingen af'
    'finitet"},{"maal":"GABA-reseptorer","effekt":"Ingen effekt","mekanisme":"ingen_effekt","retning":"ingen","kvalifikasjon":"Ingen affinitet"}]},{"stoff":"flupentiksol","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Høy affinitet (antagonist) til D"},{"type":"text","text":"1","marks":[{"type":"subscript"}]},{"type":"text","text":"-, D"},{"type":"text","text":"2",'
    '"marks":[{"type":"subscript"}]},{"type":"text","text":"-, α"},{"type":"text","text":"1","marks":[{"type":"subscript"}]},{"type":"text","text":"- og 5-HT"},{"type":"text","text":"2","marks":[{"type":"subscript"}]},{"type":"text","text":"-reseptorer."}]},{"type":"paragraph","content":[{"type":"text","text":"Ingen affinitet til kolinerge reseptorer og kun svak antihistaminerg effekt. Ingen α"},{"type'
    '":"text","text":"2","marks":[{"type":"subscript"}]},{"type":"text","text":"-reseptorantagonisme."}]}]},"kort":[{"maal":"D1-reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned","kvalifikasjon":"Høy affinitet"},{"maal":"D2-reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned","kvalifikasjon":"Høy affinitet"},{"maal":"α1-reseptor","effekt":"Antagonist","mekani'
    'sme":"antagonisme","retning":"ned","kvalifikasjon":"Høy affinitet"},{"maal":"5-HT2-reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned","kvalifikasjon":"Høy affinitet"},{"maal":"Kolinerge reseptorer","effekt":"Ingen effekt","mekanisme":"ingen_effekt","retning":"ingen","kvalifikasjon":"Ingen affinitet"},{"maal":"Histaminreseptorer","effekt":"Svak antihistaminerg effekt","mekani'
    'sme":"reseptorpavirkning","retning":"ukjent"},{"maal":"α2-reseptor","effekt":"Ingen effekt","mekanisme":"ingen_effekt","retning":"ingen","kvalifikasjon":"Ingen α2-reseptorantagonisme"}]},{"stoff":"fluvoksamin","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Selektiv reopptakshemmer av serotonin (SSRI). Ubetydelig affinitet til adrenerge, histaminerge, muskarine'
    ', dopaminerge og serotonerge reseptorer. Minimal effekt på noradrenerge prosesser."}]}]},"kort":[{"maal":"Serotoninreopptak / SERT","effekt":"Hemmer reopptak","mekanisme":"reopptakshemming","retning":"ned","kvalifikasjon":"Selektiv","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Minimal effekt på noradrenerge prosesser."}]}]}},{"maal":"Adrenerge reseptore'
    'r","effekt":"Ubetydelig effekt","mekanisme":"ingen_effekt","retning":"ingen","kvalifikasjon":"Ubetydelig affinitet"},{"maal":"Histaminerge reseptorer","effekt":"Ubetydelig effekt","mekanisme":"ingen_effekt","retning":"ingen","kvalifikasjon":"Ubetydelig affinitet"},{"maal":"Muskarine reseptorer","effekt":"Ubetydelig effekt","mekanisme":"ingen_effekt","retning":"ingen","kvalifikasjon":"Ubetydelig af'
    'finitet"},{"maal":"Dopaminerge reseptorer","effekt":"Ubetydelig effekt","mekanisme":"ingen_effekt","retning":"ingen","kvalifikasjon":"Ubetydelig affinitet"},{"maal":"Serotonerge reseptorer","effekt":"Ubetydelig effekt","mekanisme":"ingen_effekt","retning":"ingen","kvalifikasjon":"Ubetydelig affinitet"}]},{"stoff":"furosemid","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"te'
    'xt","text":"Slyngediuretika med rask absorpsjon, hemmer Na+/K+/2Cl- symporter i tubuliceller hovedsakelig i oppadgående del av Henles sløyfe, som fører til redusert opptak av væske med økt diurese. I tillegg gir slyngediuretika venedilatasjon med redusert venøs tilbakestrømming til hjertet (reduserer preload), hvilket avlaster hjertet. Slyngediuretika hemmer nyrenes evne til å konsentrere urinen, '
    'ved at den ødelegger gradienten i interstitiet."}]}]},"kort":[{"maal":"Na+/K+/2Cl−-kotransportør i oppadgående Henles sløyfe","effekt":"Hemmer","mekanisme":"kotransporterhemming","retning":"ned","merknad":"Slyngediuretikum; økt diurese og redusert evne til å konsentrere urin","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Slyngediuretika med rask absorpsj'
    'on, hemmer Na+/K+/2Cl- symporter i tubuliceller hovedsakelig i oppadgående del av Henles sløyfe, som fører til redusert opptak av væske med økt diurese. I tillegg gir slyngediuretika venedilatasjon med redusert venøs tilbakestrømming til hjertet (reduserer preload), hvilket avlaster hjertet. Slyngediuretika hemmer nyrenes evne til å konsentrere urinen, ved at den ødelegger gradienten i interstitie'
    't."}]}]}}]},{"stoff":"haloperidol","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Potent D"},{"type":"text","text":"2","marks":[{"type":"subscript"}]},{"type":"text","text":"-antagonist"}]}]},"kort":[{"maal":"D2-reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned","kvalifikasjon":"Potent"}]},{"stoff":"hydroklortiazid","fra":{"type":"doc","'
    'content":[{"type":"paragraph","content":[{"type":"text","text":"Tiazid som hemmer Na+/Cl- transporter i distale tubuli med påfølgende økt diurese (tap av blodvolum som initialt gir reduksjon i blodtrykket). Gir mindre diurese sammenlignet med slyngediuretika, siden reabsorpsjonen er noe mindre i distale tubuli. Natriuresen forårsaker en sekundær utskillelse av kalium og bikarbonat. Nedsetter nyren'
    'es evne til å fortynne urinen, som til vanlig skjer i distale tubuli. Gir som slyngediuretika også venedilatasjon. Ved fortsatt behandling avhenger den blodtrykkssenkende effekten hovedsakelig av reduksjon i total perifer karmotstand."}]},{"type":"paragraph","content":[{"type":"text","text":"Siden tiazider virker mer distalt i nefronet, hvor mye av saltene og vannet allerede er reabsorbert, gir ti'
    'azider en mindre kraftig vanndrivende effekt sammenlignet med slyngediuretika."}]}]},"kort":[{"maal":"Na+/Cl−-kotransportør i distale tubuli","effekt":"Hemmer","mekanisme":"kotransporterhemming","retning":"ned","merknad":"Øker diurese; sekundær utskillelse av K+ og bikarbonat","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Tiazid som hemmer Na+/Cl- transp'
    'orter i distale tubuli med påfølgende økt diurese (tap av blodvolum som initialt gir reduksjon i blodtrykket). Gir mindre diurese sammenlignet med slyngediuretika, siden reabsorpsjonen er noe mindre i distale tubuli. Natriuresen forårsaker en sekundær utskillelse av kalium og bikarbonat. Nedsetter nyrenes evne til å fortynne urinen, som til vanlig skjer i distale tubuli. Gir som slyngediuretika og'
    'så venedilatasjon. Ved fortsatt behandling avhenger den blodtrykkssenkende effekten hovedsakelig av reduksjon i total perifer karmotstand."}]},{"type":"paragraph","content":[{"type":"text","text":"Siden tiazider virker mer distalt i nefronet, hvor mye av saltene og vannet allerede er reabsorbert, gir tiazider en mindre kraftig vanndrivende effekt sammenlignet med slyngediuretika."}]}]}}]},{"stoff"'
    ':"irbesartan","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Irbesartan blokkerer reseptoren (angiotensin 2- reseptor type 1) til angiotensin 2. Angiotensin 2 er en kraftig vasokonstriktor. Ved å blokkere denne reseptoren oppnår man vasodilatasjon og påfølgende fall i blodtrykk. Den spesifikke hemmingen av AT1-reseptorer fører til økning av plasma renin og ang'
    'iotensin-II nivå og reduksjon i konsentrasjon av plasma aldosteron."}]},{"type":"paragraph","content":[{"type":"text","text":"Reseptorer for angiotensin 2 finnes også i:"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"bakre hypofyselapp: blokkering via irbesartan medfører redusert frigjøring av antidiuretisk hormon (ADH)."}]}]'
    '},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"binyrebarken: blokkering via irbesartan medfører redusert frigjøring av aldosteron."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"nyren: blokkering via irbesartan medfører redusert gjenopptak av vann og natrium."}]}]}]},{"type":"paragraph","content":[{"type":"text","tex'
    't":"Forventet blodtrykkseffekt av monopreparat på systolisk og diastolisk kontorblodtrykk som for ACEI, se Wu et al. (2005)."}]}]},"kort":[{"maal":"Angiotensin II AT1-reseptor","effekt":"Blokkerer / antagonist","mekanisme":"antagonisme","retning":"ned","merknad":"Gir vasodilatasjon; reduserer aldosteron, ADH-frigjøring og renal reabsorpsjon av Na+/vann som nedstrøms effekter","dokument":{"type":"d'
    'oc","content":[{"type":"paragraph","content":[{"type":"text","text":"Irbesartan blokkerer reseptoren (angiotensin 2- reseptor type 1) til angiotensin 2. Angiotensin 2 er en kraftig vasokonstriktor. Ved å blokkere denne reseptoren oppnår man vasodilatasjon og påfølgende fall i blodtrykk. Den spesifikke hemmingen av AT1-reseptorer fører til økning av plasma renin og angiotensin-II nivå og reduksjon '
    'i konsentrasjon av plasma aldosteron."}]},{"type":"paragraph","content":[{"type":"text","text":"Reseptorer for angiotensin 2 finnes også i:"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"bakre hypofyselapp: blokkering via irbesartan medfører redusert frigjøring av antidiuretisk hormon (ADH)."}]}]},{"type":"listItem","content"'
    ':[{"type":"paragraph","content":[{"type":"text","text":"binyrebarken: blokkering via irbesartan medfører redusert frigjøring av aldosteron."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"nyren: blokkering via irbesartan medfører redusert gjenopptak av vann og natrium."}]}]}]},{"type":"paragraph","content":[{"type":"text","text":"Forventet blodtrykkseffekt'
    ' av monopreparat på systolisk og diastolisk kontorblodtrykk som for ACEI, se Wu et al. (2005)."}]}]}}]},{"stoff":"kandesartan","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Kandesartan blokkerer reseptoren (angiotensin 2- reseptor type 1) til angiotensin 2. Angiotensin 2 er en kraftig vasokonstriktor. Ved å blokkere denne reseptoren oppnår man vasodilatasjon '
    'og påfølgende fall i blodtrykk. Antagonismen av angiotensin II-reseptorer resulterer i en doserelatert økning i plasma reninnivået, av angiotensin I- og angiotensin II-nivået og en reduksjon av plasma aldosteron-konsentrasjonen."}]},{"type":"paragraph","content":[{"type":"text","text":"Reseptorer for angiotensin 2 finnes også i:"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"t'
    'ype":"paragraph","content":[{"type":"text","text":"bakre hypofyselapp: blokkering via kandesartan medfører redusert frigjøring av antidiuretisk hormon (ADH)."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"binyrebarken: blokkering via kandesartan medfører redusert frigjøring av aldosteron."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":['
    '{"type":"text","text":"nyren: blokkering via kandesartan medfører redusert gjenopptak av vann og natrium."}]}]}]},{"type":"paragraph","content":[{"type":"text","text":"Forventet blodtrykkseffekt av monopreparat på systolisk og diastolisk kontorblodtrykk som for ACEI, se Wu et al. (2005)."}]}]},"kort":[{"maal":"Angiotensin II AT1-reseptor","effekt":"Blokkerer / antagonist","mekanisme":"antagonisme"'
    ',"retning":"ned","merknad":"Reduserer aldosteron, ADH-frigjøring og renal reabsorpsjon av Na+/vann som nedstrøms effekter","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Kandesartan blokkerer reseptoren (angiotensin 2- reseptor type 1) til angiotensin 2. Angiotensin 2 er en kraftig vasokonstriktor. Ved å blokkere denne reseptoren oppnår man vasodilatasjon'
    ' og påfølgende fall i blodtrykk. Antagonismen av angiotensin II-reseptorer resulterer i en doserelatert økning i plasma reninnivået, av angiotensin I- og angiotensin II-nivået og en reduksjon av plasma aldosteron-konsentrasjonen."}]},{"type":"paragraph","content":[{"type":"text","text":"Reseptorer for angiotensin 2 finnes også i:"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"'
    'type":"paragraph","content":[{"type":"text","text":"bakre hypofyselapp: blokkering via kandesartan medfører redusert frigjøring av antidiuretisk hormon (ADH)."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"binyrebarken: blokkering via kandesartan medfører redusert frigjøring av aldosteron."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":'
    '[{"type":"text","text":"nyren: blokkering via kandesartan medfører redusert gjenopptak av vann og natrium."}]}]}]},{"type":"paragraph","content":[{"type":"text","text":"Forventet blodtrykkseffekt av monopreparat på systolisk og diastolisk kontorblodtrykk som for ACEI, se Wu et al. (2005)."}]}]}}]},{"stoff":"kariprazin","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","t'
    'ext":"Partiell agonist av D"},{"type":"text","text":"2","marks":[{"type":"subscript"}]},{"type":"text","text":"-, D"},{"type":"text","text":"3","marks":[{"type":"subscript"}]},{"type":"text","text":"- og 5-HT"},{"type":"text","text":"1A","marks":[{"type":"subscript"}]},{"type":"text","text":"-reseptorene. Antagonist av 5-HT"},{"type":"text","text":"2B","marks":[{"type":"subscript"}]},{"type":"text'
    '","text":"-, 5-HT"},{"type":"text","text":"2A","marks":[{"type":"subscript"}]},{"type":"text","text":"- og H"},{"type":"text","text":"1","marks":[{"type":"subscript"}]},{"type":"text","text":"-reseptorene."}]},{"type":"paragraph","content":[{"type":"text","text":"Aktive metabolitter: desmetylkariprazin og didesmetylkariprazin"}]}]},"kort":[{"maal":"D2-reseptor","effekt":"Partiell agonist","mekanis'
    'me":"partiell_agonisme","retning":"opp","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Aktive metabolitter: desmetylkariprazin og didesmetylkariprazin"}]}]}},{"maal":"D3-reseptor","effekt":"Partiell agonist","mekanisme":"partiell_agonisme","retning":"opp"},{"maal":"5-HT1A-reseptor","effekt":"Partiell agonist","mekanisme":"partiell_agonisme","retning":"opp'
    '"},{"maal":"5-HT2B-reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned"},{"maal":"5-HT2A-reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned"},{"maal":"H1-reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned"}]}]'::jsonb) loop
    select s.objekt_id into side from public.infosider s where s.tilstand = 'publisert' and s.slug = konvertering->>'stoff';

    -- Teksten slik den ble importert, uten upublisert utkast.
    select u.objekt_id, u.revisjon, r.innhold into e
    from public.innholdselementer t
    join public.objekttilstander u on u.objekt_id = t.objekt_id and u.tilstand = 'utkast'
    join public.objekttilstander p on p.objekt_id = t.objekt_id and p.tilstand = 'publisert' and p.revisjon = u.revisjon
    join public.objektrevisjoner r on r.objekt_id = t.objekt_id and r.revisjon = u.revisjon
    where t.tilstand = 'publisert' and t.infoside_id = side
      and t.panel = 'farmakodynamikk' and t.elementtype = 'riktekst'
      and r.innhold->'data'->'dokument' = konvertering->'fra'
    order by t.posisjon, t.objekt_id
    limit 1;
    if not found then
      raise notice 'Gjør ikke om farmakodynamikken på %: fant ikke teksten slik den ble importert, eller den har et upublisert utkast.',
        konvertering->>'stoff';
      continue;
    end if;

    -- Kortene, i rekkefølge, med kildene til teksten.
    perform set_config('far.revisjonskilde', 'Farmakodynamikken strukturert som mekanismekort etter kartleggingen i docs/farmakodynamikk-kort-kartlegging.md', true);
    for kort, posisjon in select k, i - 1 from jsonb_array_elements(konvertering->'kort') with ordinality as a(k, i) loop
      objekt := (public.opprett_utkast('innholdselement', jsonb_build_object(
        'infoside', side,
        'panel', 'farmakodynamikk',
        'posisjon', posisjon,
        'elementtype', 'mekanismekort',
        'data', kort
      ) || jsonb_strip_nulls(jsonb_build_object('referanser', e.innhold->'referanser')))).id;
      perform public.publiser_utkast(objekt, 1);
    end loop;

    -- Teksten tas bort fra siden, men står i historikken.
    perform set_config('far.revisjonskilde', 'Farmakodynamikkteksten erstattet av mekanismekort etter kartleggingen i docs/farmakodynamikk-kort-kartlegging.md', true);
    perform public.lagre_utkast(e.objekt_id, e.revisjon, jsonb_set(e.innhold, '{panel}', to_jsonb('fjernet'::text)));
    perform public.publiser_utkast(e.objekt_id, e.revisjon + 1);
  end loop;
end
$farmakodynamikk$;