-- Farmakodynamikken som mekanismekort (docs/farmakodynamikk-kort-kartlegging.md)
do $farmakodynamikk$
declare
  administrator uuid;
  konvertering jsonb;
  side uuid;
  e record;
  kort jsonb;
  posisjon bigint;
  objekt uuid;
begin
  select p.id into administrator from public.profiles p where p.username = 'peohol' and p.role = 'admin';
  if administrator is null then
    raise notice 'Fant ingen administrator med brukernavnet %, så importen hoppes over.', 'peohol';
    return;
  end if;
  perform set_config('request.jwt.claims', jsonb_build_object('sub', administrator, 'role', 'authenticated')::text, true);

  for konvertering in select * from jsonb_array_elements('[{"stoff":"karvedilol","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Selektiv alfa-1-adrenerg reseptorantagonist og ikke-selektiv beta-1-reseptorantagonist."}]},{"type":"paragraph","content":[{"type":"text","text":"Karvedilol er en vasodilaterende ikke-selektiv betablokker som reduserer den perifere vaskulære motstanden ved selektiv alfa 1-reseptor blokkade o'
    'g undertrykker renin-angiotensin systemet via ikke-selektiv betablokkade."}]},{"type":"paragraph","content":[{"type":"text","text":"Kombinasjonen av betablokkade og alfa-1-modulert vasodilatasjon gir redusert blodtrykk og reduserer ventrikulær pre- og afterload."}]}]},"kort":[{"maal":"α1-adrenerg reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned","kvalifikasjon":"Selektiv α1'
    '-blokkade","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Karvedilol er en vasodilaterende ikke-selektiv betablokker som reduserer den perifere vaskulære motstanden ved selektiv alfa 1-reseptor blokkade og undertrykker renin-angiotensin systemet via ikke-selektiv betablokkade."}]}]}},{"maal":"β1-adrenerg reseptor","effekt":"Antagonist / blokkerer","mekani'
    'sme":"antagonisme","retning":"ned","kvalifikasjon":"Ikke-selektiv betablokkade","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Kombinasjonen av betablokkade og alfa-1-modulert vasodilatasjon gir redusert blodtrykk og reduserer ventrikulær pre- og afterload."}]}]}},{"maal":"β2-adrenerg reseptor","effekt":"Antagonist / blokkerer","mekanisme":"antagonisme","'
    'retning":"ned","kvalifikasjon":"Ikke-selektiv betablokkade"}]},{"stoff":"klomipramin","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Hemmer reopptak av serotonin, men også noradrenalin. Har også alfa1-adrenerge, antikolinerge og antihistaminerge effekter."}]},{"type":"paragraph","content":[{"type":"text","text":"Aktiv metabolitt: desmetylklomipramin."}]}]},"ko'
    'rt":[{"maal":"Serotoninreopptak / SERT","effekt":"Hemmer reopptak","mekanisme":"reopptakshemming","retning":"ned","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Aktiv metabolitt: desmetylklomipramin."}]}]}},{"maal":"Noradrenalinreopptak / NET","effekt":"Hemmer reopptak","mekanisme":"reopptakshemming","retning":"ned"},{"maal":"α1-adrenerg reseptor","effekt'
    '":"α1-adrenerg effekt","mekanisme":"reseptorpavirkning","retning":"ukjent"},{"maal":"Kolinerge reseptorer","effekt":"Antikolinerg effekt","mekanisme":"antagonisme","retning":"ned","merknad":"Kilden bruker effektnavn, ikke eksplisitt «antagonist»"},{"maal":"Histaminreseptorer","effekt":"Antihistaminerg effekt","mekanisme":"antagonisme","retning":"ned","merknad":"Kilden bruker effektnavn, ikke ekspl'
    'isitt «antagonist»"}]},{"stoff":"klorprotiksen","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Høy affinitet (antagonist) til D"},{"type":"text","text":"1","marks":[{"type":"subscript"}]},{"type":"text","text":"-, D"},{"type":"text","text":"2","marks":[{"type":"subscript"}]},{"type":"text","text":"-, 5-HT"},{"type":"text","text":"2","marks":[{"type":"subscript'
    '"}]},{"type":"text","text":"- og α"},{"type":"text","text":"1","marks":[{"type":"subscript"}]},{"type":"text","text":"-adrenerge reseptorer samt kolinerge reseptorer. Også antihistamineffekt."}]},{"type":"paragraph","content":[{"type":"text","text":"Reseptorbindingsprofilen ligner den til klozapin, men klorprotiksen har 10 ganger høyere affinitet for dopaminreseptorer."}]}]},"kort":[{"maal":"D1-re'
    'septor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned","kvalifikasjon":"Høy affinitet","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Reseptorbindingsprofilen ligner den til klozapin, men klorprotiksen har 10 ganger høyere affinitet for dopaminreseptorer."}]}]}},{"maal":"D2-reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retnin'
    'g":"ned","kvalifikasjon":"Høy affinitet"},{"maal":"5-HT2-reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned","kvalifikasjon":"Høy affinitet"},{"maal":"α1-adrenerg reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned","kvalifikasjon":"Høy affinitet"},{"maal":"Kolinerge reseptorer","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned","kvalifikasjo'
    'n":"Høy affinitet"},{"maal":"Histaminreseptorer","effekt":"Antihistaminerg effekt","mekanisme":"reseptorpavirkning","retning":"ukjent","merknad":"Subtype ikke oppgitt"}]},{"stoff":"klozapin","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Antagonist på serotonerge (5-HT"},{"type":"text","text":"2A","marks":[{"type":"subscript"}]},{"type":"text","text":"), alfa-'
    'adrenerge, kolinerge, histaminerge og dopaminerge reseptorer. Lav affinitet til D"},{"type":"text","text":"1","marks":[{"type":"subscript"}]},{"type":"text","text":"-, D"},{"type":"text","text":"2","marks":[{"type":"subscript"}]},{"type":"text","text":"-, D"},{"type":"text","text":"3","marks":[{"type":"subscript"}]},{"type":"text","text":"- og D"},{"type":"text","text":"5","marks":[{"type":"subscr'
    'ipt"}]},{"type":"text","text":"-reseptorer, men viser høy affinitet til D"},{"type":"text","text":"4","marks":[{"type":"subscript"}]},{"type":"text","text":"-reseptorer."}]}]},"kort":[{"maal":"5-HT2A-reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned"},{"maal":"α-adrenerge reseptorer","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned","merknad":"Subtype ikke oppg'
    'itt"},{"maal":"Kolinerge reseptorer","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned"},{"maal":"Histaminerge reseptorer","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned"},{"maal":"D1-reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned","kvalifikasjon":"Lav affinitet"},{"maal":"D2-reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":'
    '"ned","kvalifikasjon":"Lav affinitet"},{"maal":"D3-reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned","kvalifikasjon":"Lav affinitet"},{"maal":"D4-reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned","kvalifikasjon":"Høy affinitet"},{"maal":"D5-reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned","kvalifikasjon":"Lav affinitet"}]},{"'
    'stoff":"kvetiapin","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Antagonist til 5-HT"},{"type":"text","text":"2","marks":[{"type":"subscript"}]},{"type":"text","text":"-, D"},{"type":"text","text":"1","marks":[{"type":"subscript"}]},{"type":"text","text":"- og D"},{"type":"text","text":"2","marks":[{"type":"subscript"}]},{"type":"text","text":"-reseptorer. Hø'
    'yere affinitet til 5-HT"},{"type":"text","text":"2","marks":[{"type":"subscript"}]},{"type":"text","text":" enn D"},{"type":"text","text":"2","marks":[{"type":"subscript"}]},{"type":"text","text":". Antagonist også på H"},{"type":"text","text":"1","marks":[{"type":"subscript"}]},{"type":"text","text":"-, α"},{"type":"text","text":"1","marks":[{"type":"subscript"}]},{"type":"text","text":"- og α"},'
    '{"type":"text","text":"2","marks":[{"type":"subscript"}]},{"type":"text","text":"-reseptorer."}]},{"type":"paragraph","content":[{"type":"text","text":"Aktiv metabolitt: norkvetiapin, som har affinitet til muskarinerge reseptorer, hemmer noradrenalintransportøren og er en partiell agonist av 5-HT"},{"type":"text","text":"1A","marks":[{"type":"subscript"}]},{"type":"text","text":"-reseptoren."}]}]}'
    ',"kort":[{"maal":"5-HT2-reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned","kvalifikasjon":"Høyere affinitet enn til D2"},{"maal":"D1-reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned"},{"maal":"D2-reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned"},{"maal":"H1-reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"'
    'ned"},{"maal":"α1-reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned"},{"maal":"α2-reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned"},{"maal":"Muskarinreseptorer (norkvetiapin)","effekt":"Binder / har affinitet","mekanisme":"reseptorbinding","retning":"ukjent","merknad":"Aktiv metabolitt norkvetiapin"},{"maal":"Noradrenalintransportør / NET (norkvetiap'
    'in)","effekt":"Hemmer transportøren","mekanisme":"transporterhemming","retning":"ned","merknad":"Aktiv metabolitt norkvetiapin"},{"maal":"5-HT1A-reseptor (norkvetiapin)","effekt":"Partiell agonist","mekanisme":"partiell_agonisme","retning":"opp","merknad":"Aktiv metabolitt norkvetiapin"}]},{"stoff":"labetalol","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Sel'
    'ektiv alfa-1-adrenerg reseptorantagonist og ikke-selektiv beta-1-reseptorantagonist."}]},{"type":"paragraph","content":[{"type":"text","text":"Labetalol senker blodtrykket ved å blokkere perifere arteriolære alfa-adrenoseptorer. Blokkeringen reduserer perifer motstand, og gjennom samtidig beta-blokkering beskyttes hjertet mot reflekssympatisk arbeid som ellers ville oppstå."}]},{"type":"paragraph"'
    ',"content":[{"type":"text","text":"Den reduserte perifere motstanden senker den myokardiale etterbelastningen og oksygenbehovet."}]}]},"kort":[{"maal":"α1-adrenerg reseptor","effekt":"Antagonist / blokkerer","mekanisme":"antagonisme","retning":"ned","kvalifikasjon":"Selektiv α1-blokkade","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Labetalol senker blod'
    'trykket ved å blokkere perifere arteriolære alfa-adrenoseptorer."}]},{"type":"paragraph","content":[{"type":"text","text":"Den reduserte perifere motstanden senker den myokardiale etterbelastningen og oksygenbehovet."}]}]}},{"maal":"β1-adrenerg reseptor","effekt":"Antagonist / blokkerer","mekanisme":"antagonisme","retning":"ned","kvalifikasjon":"Ikke-selektiv betablokkade","dokument":{"type":"doc"'
    ',"content":[{"type":"paragraph","content":[{"type":"text","text":"Blokkeringen reduserer perifer motstand, og gjennom samtidig beta-blokkering beskyttes hjertet mot reflekssympatisk arbeid som ellers ville oppstå."}]}]}},{"maal":"β2-adrenerg reseptor","effekt":"Antagonist / blokkerer","mekanisme":"antagonisme","retning":"ned","kvalifikasjon":"Ikke-selektiv betablokkade"}]},{"stoff":"lamotrigin","f'
    'ra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Bruks- og spenningsavhengig hemmer av spenningsstyrte natriumkanaler, hemmer frigjøring av glutamat."}]}]},"kort":[{"maal":"Spenningsstyrte natriumkanaler","effekt":"Hemmer / blokkerer","mekanisme":"bruksavhengig_blokkering","retning":"ned","kvalifikasjon":"Bruks- og spenningsavhengig","dokument":{"type":"doc","cont'
    'ent":[{"type":"paragraph","content":[{"type":"text","text":"Bruks- og spenningsavhengig hemmer av spenningsstyrte natriumkanaler, hemmer frigjøring av glutamat."}]}]}}]},{"stoff":"lerkanidipin","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Lerkanidipin binder seg til spenningsstyrte L(low)-type kalsiumkanaler i sarcolemma i glatte muskelceller i perifere mots'
    'tandskar (inkludert koronarkar) og hemmer kalsiuminnstrømming i cellene. Dette fører til ytterligere redusert kalsiumfrigivelse fra sarkoplasmatisk retikulum til cytosol. Reduksjon i intracellulært fritt kalsium reduserer glatt muskelkontraksjon, dvs. vil gi vasodilatasjon, derved redusert perifer resistens og fall i blodtrykk."}]},{"type":"paragraph","content":[{"type":"text","text":"Ved veldig h'
    'øye lerkanidipin serumkonsentrasjoner bindes også legemiddelet til hjertemuskelceller."}]},{"type":"paragraph","content":[{"type":"text","text":"Kalsiumantagonister av dihydropyridintype reduserer sittende systolisk blodtrykk og diastolisk blodtrykk med ca. 15,6 ± 5,3 / 10,3 ± 2,6 mmHg (gjennomsnitt ± SD), ifølge metastudie fra Wu et al. (2005)"}]}]},"kort":[{"maal":"Spenningsstyrte L-type Ca2+-ka'
    'naler","effekt":"Hemmer kalsiuminnstrømming / blokkerer kanalaktivitet","mekanisme":"kanalblokkering","retning":"ned","merknad":"Primært glatte muskelceller i perifere motstandskar; ved svært høye konsentrasjoner også hjertemuskel","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Lerkanidipin binder seg til spenningsstyrte L(low)-type kalsiumkanaler i sarco'
    'lemma i glatte muskelceller i perifere motstandskar (inkludert koronarkar) og hemmer kalsiuminnstrømming i cellene. Dette fører til ytterligere redusert kalsiumfrigivelse fra sarkoplasmatisk retikulum til cytosol. Reduksjon i intracellulært fritt kalsium reduserer glatt muskelkontraksjon, dvs. vil gi vasodilatasjon, derved redusert perifer resistens og fall i blodtrykk."}]},{"type":"paragraph","co'
    'ntent":[{"type":"text","text":"Ved veldig høye lerkanidipin serumkonsentrasjoner bindes også legemiddelet til hjertemuskelceller."}]},{"type":"paragraph","content":[{"type":"text","text":"Kalsiumantagonister av dihydropyridintype reduserer sittende systolisk blodtrykk og diastolisk blodtrykk med ca. 15,6 ± 5,3 / 10,3 ± 2,6 mmHg (gjennomsnitt ± SD), ifølge metastudie fra Wu et al. (2005)"}]}]}}]},{'
    '"stoff":"levomepromazin","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Blokade av monoaminerg transmisjon, særlig dopaminerg, adrenerg og noradrenerg."}]}]},"kort":[{"maal":"Dopaminerg transmisjon","effekt":"Blokade","mekanisme":"reseptorpavirkning","retning":"ned","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Bloka'
    'de av monoaminerg transmisjon, særlig dopaminerg, adrenerg og noradrenerg."}]}]}},{"maal":"Adrenerg transmisjon","effekt":"Blokade","mekanisme":"reseptorpavirkning","retning":"ned"},{"maal":"Noradrenerg transmisjon","effekt":"Blokade","mekanisme":"reseptorpavirkning","retning":"ned"}]},{"stoff":"lisinopril","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"ACE-he'
    'mmer (angiotensinkonverterende enzymhemmer). Hemming av ACE gir redusert angiotensin II-konsentrasjon, som igjen resulterer i redusert vasopressoraktivitet og aldosteronutskillelse. Blodtrykkssenkende effekt antas å skyldes hemming av RAAS. Blokkerer nedbrytningen av bradykinin."}]}]},"kort":[{"maal":"ACE (angiotensinkonverterende enzym)","effekt":"Hemmer","mekanisme":"enzymhemming","retning":"ned'
    '","merknad":"Reduserer angiotensin II og aldosteron; reduserer nedbrytning av bradykinin","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"ACE-hemmer (angiotensinkonverterende enzymhemmer). Hemming av ACE gir redusert angiotensin II-konsentrasjon, som igjen resulterer i redusert vasopressoraktivitet og aldosteronutskillelse. Blodtrykkssenkende effekt antas '
    'å skyldes hemming av RAAS. Blokkerer nedbrytningen av bradykinin."}]}]}}]},{"stoff":"losartan","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Losartan blokkerer reseptoren (angiotensin 2- reseptor type 1) til angiotensin 2. Angiotensin 2 er en kraftig vasokonstriktor. Ved å blokkere denne reseptoren oppnår man vasodilatasjon og påfølgende fall i blodtrykk."}]}'
    ',{"type":"paragraph","content":[{"type":"text","text":"Reseptorer for angiotensin 2 finnes også i:"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"bakre hypofyselapp: blokkering via losartan medfører redusert frigjøring av antidiuretisk hormon (ADH)."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"t'
    'ext","text":"binyrebarken: blokkering via losartan medfører redusert frigjøring av aldosteron."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"nyren: blokkering via losartan medfører redusert gjenopptak av vann og natrium."}]}]}]}]},"kort":[{"maal":"Angiotensin II AT1-reseptor","effekt":"Blokkerer / antagonist","mekanisme":"antagonisme","retning":"ned","me'
    'rknad":"Gir vasodilatasjon; reduserer ADH, aldosteron og renal reabsorpsjon av Na+/vann som nedstrøms effekter","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Losartan blokkerer reseptoren (angiotensin 2- reseptor type 1) til angiotensin 2. Angiotensin 2 er en kraftig vasokonstriktor. Ved å blokkere denne reseptoren oppnår man vasodilatasjon og påfølgende'
    ' fall i blodtrykk."}]},{"type":"paragraph","content":[{"type":"text","text":"Reseptorer for angiotensin 2 finnes også i:"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"bakre hypofyselapp: blokkering via losartan medfører redusert frigjøring av antidiuretisk hormon (ADH)."}]}]},{"type":"listItem","content":[{"type":"paragraph"'
    ',"content":[{"type":"text","text":"binyrebarken: blokkering via losartan medfører redusert frigjøring av aldosteron."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"nyren: blokkering via losartan medfører redusert gjenopptak av vann og natrium."}]}]}]}]}}]},{"stoff":"lurasidon","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","t'
    'ext":"Blokkerer dopaminerge og monoaminerge effekter. Høy affinitet til D"},{"type":"text","text":"2","marks":[{"type":"subscript"}]},{"type":"text","text":"-resptorer, 5-HT"},{"type":"text","text":"2A","marks":[{"type":"subscript"}]},{"type":"text","text":"- og 5-HT"},{"type":"text","text":"7","marks":[{"type":"subscript"}]},{"type":"text","text":"-reseptorer. Partiell agonist av 5-HT"},{"type":"'
    'text","text":"1A","marks":[{"type":"subscript"}]},{"type":"text","text":"-reseptorer. Bindes ikke til histaminerge eller muskarine reseptorer."}]},{"type":"paragraph","content":[{"type":"text","text":"Aktive metabolitter: ID-14283 og 14326."}]}]},"kort":[{"maal":"D2-reseptor","effekt":"Blokkerende/antagonistisk effekt","mekanisme":"antagonisme","retning":"ned","kvalifikasjon":"Høy affinitet","doku'
    'ment":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Aktive metabolitter: ID-14283 og 14326."}]}]}},{"maal":"5-HT2A-reseptor","effekt":"Blokkerende/antagonistisk effekt","mekanisme":"antagonisme","retning":"ned","kvalifikasjon":"Høy affinitet","merknad":"Kilden uttrykker blokade samlet som monoaminerg blokade"},{"maal":"5-HT7-reseptor","effekt":"Blokkerende/antagoni'
    'stisk effekt","mekanisme":"antagonisme","retning":"ned","kvalifikasjon":"Høy affinitet","merknad":"Kilden uttrykker blokade samlet som monoaminerg blokade"},{"maal":"5-HT1A-reseptor","effekt":"Partiell agonist","mekanisme":"partiell_agonisme","retning":"opp"},{"maal":"Histaminreseptorer","effekt":"Ingen effekt","mekanisme":"ingen_effekt","retning":"ingen","kvalifikasjon":"Bindes ikke"},{"maal":"Mu'
    'skarinreseptorer","effekt":"Ingen effekt","mekanisme":"ingen_effekt","retning":"ingen","kvalifikasjon":"Bindes ikke"}]},{"stoff":"metoprolol","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Selektiv beta-1-adrenerg reseptorantagonist."}]},{"type":"paragraph","content":[{"type":"text","text":"Metoprolol reduserer eller hemmer katekolaminenes (frigjøres ved fysis'
    'k og psykisk stress) agonistiske effekt på hjertet."}]},{"type":"paragraph","content":[{"type":"text","text":"Dette fører til at den vanlige økningen i hjertefrekvens, hjertets arbeidsmengde og kontraktilitet, og blodtrykk, som er en følge av akutt økning i katekolaminer, blir redusert av metoprolol."}]}]},"kort":[{"maal":"β1-adrenerg reseptor","effekt":"Antagonist / hemmer katekolamineffekt","mek'
    'anisme":"antagonisme","retning":"ned","kvalifikasjon":"Selektiv","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Metoprolol reduserer eller hemmer katekolaminenes (frigjøres ved fysisk og psykisk stress) agonistiske effekt på hjertet."}]},{"type":"paragraph","content":[{"type":"text","text":"Dette fører til at den vanlige økningen i hjertefrekvens, hjertet'
    's arbeidsmengde og kontraktilitet, og blodtrykk, som er en følge av akutt økning i katekolaminer, blir redusert av metoprolol."}]}]}}]},{"stoff":"mianserin","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Noradrenerg effekt gjennom α2-autoreseptorblokade og hemming av reopptak av noradrenalin. H1- og α1-antagonist. Ingen antikolinerg effekt."}]},{"type":"paragr'
    'aph","content":[{"type":"text","text":"Aktiv metabolitt: desmetylmianserin."}]}]},"kort":[{"maal":"Presynaptisk α2-autoreseptor","effekt":"Blokade / antagonistisk effekt","mekanisme":"antagonisme","retning":"ned","merknad":"Øker noradrenerg effekt som nedstrøms konsekvens","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Aktiv metabolitt: desmetylmianserin.'
    '"}]}]}},{"maal":"Noradrenalinreopptak / NET","effekt":"Hemmer reopptak","mekanisme":"reopptakshemming","retning":"ned"},{"maal":"H1-reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned"},{"maal":"α1-reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned"},{"maal":"Kolinerge/muskarine reseptorer","effekt":"Ingen effekt","mekanisme":"ingen_effekt","retning":"ing'
    'en","kvalifikasjon":"Ingen antikolinerg effekt"}]},{"stoff":"mirtazapin","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Presynaptisk α"},{"type":"text","text":"2","marks":[{"type":"subscript"}]},{"type":"text","text":"-antagonist som øker noradrenerg effekt. Serotonerg effekt spesifikt mediert via 5-HT"},{"type":"text","text":"1","marks":[{"type":"subscript"}]'
    '},{"type":"text","text":"-reseptorer (er antagonist på 5-HT"},{"type":"text","text":"2","marks":[{"type":"subscript"}]},{"type":"text","text":"- og 5-HT"},{"type":"text","text":"3","marks":[{"type":"subscript"}]},{"type":"text","text":"-reseptorer). Ingen antikolinerg aktivitet og kun begrenset effekt på det kardiovaskulære system, f.eks. ortostatisk hypotensjon. Har også antihistaminerg effekt."}'
    ']},{"type":"paragraph","content":[{"type":"text","text":"Aktiv metabolitt: desmetylmirtazapin (inngår ikke i referanseområdet)."}]}]},"kort":[{"maal":"Presynaptisk α2-reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned","merknad":"Øker noradrenerg effekt som nedstrøms konsekvens","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Aktiv me'
    'tabolitt: desmetylmirtazapin (inngår ikke i referanseområdet)."}]}]}},{"maal":"5-HT2-reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned"},{"maal":"5-HT3-reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned"},{"maal":"5-HT1-reseptorer","effekt":"Serotonerg effekt medieres via reseptoren","mekanisme":"reseptorpavirkning","retning":"ukjent","merknad":"Kilden '
    'sier ikke agonist/antagonist"},{"maal":"Histaminreseptorer","effekt":"Antihistaminerg effekt","mekanisme":"antagonisme","retning":"ned","merknad":"Subtype ikke oppgitt"},{"maal":"Kolinerge/muskarine reseptorer","effekt":"Ingen effekt","mekanisme":"ingen_effekt","retning":"ingen","kvalifikasjon":"Ingen antikolinerg aktivitet","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type'
    '":"text","text":"Ingen antikolinerg aktivitet og kun begrenset effekt på det kardiovaskulære system, f.eks. ortostatisk hypotensjon."}]}]}}]},{"stoff":"nifedipin","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Nifedipin binder seg til spenningstyrte L(low)-type kalsiumkanaler i sarcolemma i glatte muskelceller i perifere motstandskar (inkludert koronarkar) og '
    'hemmer kalsiuminnstrømming i cellene. Dette fører til ytterligere redusert kalsiumfrigivelse fra sarkoplasmatisk retikulum til cytosol. Reduksjon i intracellulært fritt kalsium reduserer glatt muskelkontraksjon, dvs. vil gi vasodilatasjon, derved redusert perifer resistens og fall i blodtrykk."}]},{"type":"paragraph","content":[{"type":"text","text":"Ved veldig høye nifedipin serumkonsentrasjoner '
    'bindes også legemiddelet til hjertemuskelceller."}]},{"type":"paragraph","content":[{"type":"text","text":"Kalsiumantagonister av dihydropyridintype reduserer sittende systolisk blodtrykk og diastolisk blodtrykk med ca. 15,6 ± 5,3 / 10,3 ± 2,6 mmHg (gjennomsnitt ± SD), ifølge metastudie fra Wu et al. (2005)"}]}]},"kort":[{"maal":"Spenningsstyrte L-type Ca2+-kanaler","effekt":"Hemmer kalsiuminnstrø'
    'mming / blokkerer kanalaktivitet","mekanisme":"kanalblokkering","retning":"ned","merknad":"Primært glatte muskelceller i perifere motstandskar; ved svært høye konsentrasjoner også hjertemuskel","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Nifedipin binder seg til spenningstyrte L(low)-type kalsiumkanaler i sarcolemma i glatte muskelceller i perifere mot'
    'standskar (inkludert koronarkar) og hemmer kalsiuminnstrømming i cellene. Dette fører til ytterligere redusert kalsiumfrigivelse fra sarkoplasmatisk retikulum til cytosol. Reduksjon i intracellulært fritt kalsium reduserer glatt muskelkontraksjon, dvs. vil gi vasodilatasjon, derved redusert perifer resistens og fall i blodtrykk."}]},{"type":"paragraph","content":[{"type":"text","text":"Ved veldig '
    'høye nifedipin serumkonsentrasjoner bindes også legemiddelet til hjertemuskelceller."}]},{"type":"paragraph","content":[{"type":"text","text":"Kalsiumantagonister av dihydropyridintype reduserer sittende systolisk blodtrykk og diastolisk blodtrykk med ca. 15,6 ± 5,3 / 10,3 ± 2,6 mmHg (gjennomsnitt ± SD), ifølge metastudie fra Wu et al. (2005)"}]}]}}]},{"stoff":"nortriptylin","fra":{"type":"doc","c'
    'ontent":[{"type":"paragraph","content":[{"type":"text","text":"Potent hemmer av reopptak av noradrenalin. Hemmer også reopptak av serotonin. Betydelig antihistaminerg effekt. Mindre antikolinergt enn amitriptylin."}]}]},"kort":[{"maal":"Noradrenalinreopptak / NET","effekt":"Hemmer reopptak","mekanisme":"reopptakshemming","retning":"ned","kvalifikasjon":"Potent"},{"maal":"Serotoninreopptak / SERT",'
    '"effekt":"Hemmer reopptak","mekanisme":"reopptakshemming","retning":"ned"},{"maal":"Histaminreseptorer","effekt":"Antihistaminerg effekt","mekanisme":"antagonisme","retning":"ned","kvalifikasjon":"Betydelig"},{"maal":"Muskarinreseptorer","effekt":"Antikolinerg effekt","mekanisme":"antagonisme","retning":"ned","merknad":"Mindre antikolinergt enn amitriptylin"}]},{"stoff":"olanzapin","fra":{"type":"'
    'doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Antagonist på 5-HT"},{"type":"text","text":"2A/2C","marks":[{"type":"subscript"}]},{"type":"text","text":"-, D"},{"type":"text","text":"1-4","marks":[{"type":"subscript"}]},{"type":"text","text":"-, α"},{"type":"text","text":"1","marks":[{"type":"subscript"}]},{"type":"text","text":"- og H"},{"type":"text","text":"1","marks":[{"'
    'type":"subscript"}]},{"type":"text","text":"-reseptorer, samt kolinerge reseptorer. Høyere affinitet til 5-HT"},{"type":"text","text":"2","marks":[{"type":"subscript"}]},{"type":"text","text":" enn D"},{"type":"text","text":"2","marks":[{"type":"subscript"}]},{"type":"text","text":"."}]}]},"kort":[{"maal":"5-HT2A-reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned"},{"maal":"5'
    '-HT2C-reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned"},{"maal":"D1-reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned"},{"maal":"D2-reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned","kvalifikasjon":"Lavere affinitet enn til 5-HT2"},{"maal":"D3-reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned"},{"maal":"'
    'D4-reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned"},{"maal":"α1-reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned"},{"maal":"H1-reseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned"},{"maal":"Kolinerge reseptorer","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned"}]},{"stoff":"paliperidon","fra":{"type":"doc","conten'
    't":[{"type":"paragraph","content":[{"type":"text","text":"Potent D"},{"type":"text","text":"2","marks":[{"type":"subscript"}]},{"type":"text","text":"-antagonist. Binder sterkt til 5-HT"},{"type":"text","text":"2","marks":[{"type":"subscript"}]},{"type":"text","text":"- og D"},{"type":"text","text":"2","marks":[{"type":"subscript"}]},{"type":"text","text":"-reseptorer. Blokkerer også α"},{"type":"'
    'text","text":"1","marks":[{"type":"subscript"}]},{"type":"text","text":"-reseptorer, og i litt mindre grad H"},{"type":"text","text":"1","marks":[{"type":"subscript"}]},{"type":"text","text":"- og α"},{"type":"text","text":"2","marks":[{"type":"subscript"}]},{"type":"text","text":"-reseptorer. Binder ikke til kolinerge reseptorer."}]}]},"kort":[{"maal":"D2-reseptor","effekt":"Antagonist","mekanism'
    'e":"antagonisme","retning":"ned","kvalifikasjon":"Potent","merknad":"Sterk binding"},{"maal":"5-HT2-reseptor","effekt":"Antagonistisk/blokkerende effekt","mekanisme":"antagonisme","retning":"ned","kvalifikasjon":"Sterk binding","merknad":"Funksjonen fremgår av samlet blokkeringsbeskrivelse"},{"maal":"α1-reseptor","effekt":"Blokkerer","mekanisme":"antagonisme","retning":"ned"},{"maal":"H1-reseptor"'
    ',"effekt":"Blokkerer","mekanisme":"antagonisme","retning":"ned","kvalifikasjon":"I litt mindre grad"},{"maal":"α2-reseptor","effekt":"Blokkerer","mekanisme":"antagonisme","retning":"ned","kvalifikasjon":"I litt mindre grad"},{"maal":"Kolinerge reseptorer","effekt":"Ingen effekt","mekanisme":"ingen_effekt","retning":"ingen","kvalifikasjon":"Binder ikke"}]},{"stoff":"paroksetin","fra":{"type":"doc",'
    '"content":[{"type":"paragraph","content":[{"type":"text","text":"Hemmer reopptak av serotonin (SSRI). Lav affinitet til α1-, α2- og β-adrenerge reseptorer, D2-, 5-HT1-lignende-, 5-HT2-, H1- og muskarinkolinerge reseptorer."}]}]},"kort":[{"maal":"Serotoninreopptak / SERT","effekt":"Hemmer reopptak","mekanisme":"reopptakshemming","retning":"ned"},{"maal":"α1-adrenerg reseptor","effekt":"Lav affinite'
    't","mekanisme":"reseptorbinding","retning":"ukjent"},{"maal":"α2-adrenerg reseptor","effekt":"Lav affinitet","mekanisme":"reseptorbinding","retning":"ukjent"},{"maal":"β-adrenerge reseptorer","effekt":"Lav affinitet","mekanisme":"reseptorbinding","retning":"ukjent"},{"maal":"D2-reseptor","effekt":"Lav affinitet","mekanisme":"reseptorbinding","retning":"ukjent"},{"maal":"5-HT1-lignende reseptorer",'
    '"effekt":"Lav affinitet","mekanisme":"reseptorbinding","retning":"ukjent"},{"maal":"5-HT2-reseptor","effekt":"Lav affinitet","mekanisme":"reseptorbinding","retning":"ukjent"},{"maal":"H1-reseptor","effekt":"Lav affinitet","mekanisme":"reseptorbinding","retning":"ukjent"},{"maal":"Muskarinkolinerge reseptorer","effekt":"Lav affinitet","mekanisme":"reseptorbinding","retning":"ukjent"}]},{"stoff":"pe'
    'rfenazin","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Reseptorblokade av katekolaminer, særlig dopamin."}]}]},"kort":[{"maal":"Dopaminreseptorer (subtype ikke oppgitt)","effekt":"Reseptorblokade","mekanisme":"antagonisme","retning":"ned","kvalifikasjon":"Særlig dopamin","merknad":"Kilden omtaler også bredere katekolaminreseptorblokade"}]},{"stoff":"ramipril'
    '","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"ACE-hemmer (angiotensinkonverterende enzymhemmer). ACE katalyserer omdannelse av angiotensin I til den aktive vasokonstriktoren angiotensin II, samt nedbrytning av den aktive vasodilatatoren bradykinin. Da angiotensin II også stimulerer frisettingen av aldosteron, fører ramiprilat til redusert aldosteronsekresjo'
    'n. Ramipril gir en markant redusert perifer arteriell motstand, og økt bradykinin."}]}]},"kort":[{"maal":"ACE (angiotensinkonverterende enzym)","effekt":"Hemmer","mekanisme":"enzymhemming","retning":"ned","merknad":"Reduserer angiotensin II og aldosteron; øker bradykinin ved redusert nedbrytning","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"ACE-hemmer ('
    'angiotensinkonverterende enzymhemmer). ACE katalyserer omdannelse av angiotensin I til den aktive vasokonstriktoren angiotensin II, samt nedbrytning av den aktive vasodilatatoren bradykinin. Da angiotensin II også stimulerer frisettingen av aldosteron, fører ramiprilat til redusert aldosteronsekresjon. Ramipril gir en markant redusert perifer arteriell motstand, og økt bradykinin."}]}]}}]},{"stoff'
    '":"risperidon","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Potent D"},{"type":"text","text":"2","marks":[{"type":"subscript"}]},{"type":"text","text":"-antagonist."}]},{"type":"paragraph","content":[{"type":"text","text":"Aktiv metabolitt: paliperidon (9-hydroksyrisperidon)."}]}]},"kort":[{"maal":"D2-reseptor","effekt":"Antagonist","mekanisme":"antagonisme"'
    ',"retning":"ned","kvalifikasjon":"Potent","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Aktiv metabolitt: paliperidon (9-hydroksyrisperidon)."}]}]}}]},{"stoff":"sertralin","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Potent hemmer av reopptak av serotonin (SSRI). Svak effekt på reopptak av noradrenalin og dopamin. '
    'Har ingen affinitet til muskarin-, serotonin-, dopamin-, adrenerge-, histamin- eller GABA-reseptorer. Øker ikke katekolaminerg aktivitet."}]}]},"kort":[{"maal":"Serotoninreopptak / SERT","effekt":"Hemmer reopptak","mekanisme":"reopptakshemming","retning":"ned","kvalifikasjon":"Potent"},{"maal":"Noradrenalinreopptak / NET","effekt":"Svak reopptakshemming","mekanisme":"reopptakshemming","retning":"n'
    'ed","kvalifikasjon":"Svak effekt","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Øker ikke katekolaminerg aktivitet."}]}]}},{"maal":"Dopaminreopptak / DAT","effekt":"Svak reopptakshemming","mekanisme":"reopptakshemming","retning":"ned","kvalifikasjon":"Svak effekt"},{"maal":"Muskarinreseptorer","effekt":"Ingen effekt","mekanisme":"ingen_effekt","retning":'
    '"ingen","kvalifikasjon":"Ingen affinitet"},{"maal":"Serotoninreseptorer","effekt":"Ingen effekt","mekanisme":"ingen_effekt","retning":"ingen","kvalifikasjon":"Ingen affinitet"},{"maal":"Dopaminreseptorer","effekt":"Ingen effekt","mekanisme":"ingen_effekt","retning":"ingen","kvalifikasjon":"Ingen affinitet"},{"maal":"Adrenerge reseptorer","effekt":"Ingen effekt","mekanisme":"ingen_effekt","retning"'
    ':"ingen","kvalifikasjon":"Ingen affinitet"},{"maal":"Histaminreseptorer","effekt":"Ingen effekt","mekanisme":"ingen_effekt","retning":"ingen","kvalifikasjon":"Ingen affinitet"},{"maal":"GABA-reseptorer","effekt":"Ingen effekt","mekanisme":"ingen_effekt","retning":"ingen","kvalifikasjon":"Ingen affinitet"}]},{"stoff":"spironolakton","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"ty'
    'pe":"text","text":"Aldosteronantagonist, som resulterer i mindre reabsorpsjon av natrium og væske og mindre kaliumutskillelse, altså mer kalium tilbake til blod. Den viktigste effekten er den beskyttende effekten mot remodeleringen i hjerte, ved å blokkere aldosteronens langtidsvirkning i hjertet som har vist seg å være skadelig. Spironolakton har derfor som betablokkere og ACE-hemmere beskyttende'
    ' effekt mot langtidsskade av aktivering av RAAS-systemet i hjertet. Spironolakton er mindre selektiv enn eplerenon, så kan også gi en viss effekt på kjønnshormonreseptorene med andre bivirkninger som følger av det."}]}]},"kort":[{"maal":"Aldosteron-/mineralokortikoidreseptor","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned","merknad":"Mindre Na+/væskereabsorpsjon og mindre K+-utskil'
    'lelse; beskyttende effekt mot remodellering i hjertet","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Aldosteronantagonist, som resulterer i mindre reabsorpsjon av natrium og væske og mindre kaliumutskillelse, altså mer kalium tilbake til blod. Den viktigste effekten er den beskyttende effekten mot remodeleringen i hjerte, ved å blokkere aldosteronens lan'
    'gtidsvirkning i hjertet som har vist seg å være skadelig. Spironolakton har derfor som betablokkere og ACE-hemmere beskyttende effekt mot langtidsskade av aktivering av RAAS-systemet i hjertet."}]}]}},{"maal":"Kjønnshormonreseptorer","effekt":"Påvirker","mekanisme":"reseptorpavirkning","retning":"ukjent","kvalifikasjon":"Mindre selektiv enn eplerenon","merknad":"Teksten sier bare at dette kan gi e'
    'n viss effekt","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Spironolakton er mindre selektiv enn eplerenon, så kan også gi en viss effekt på kjønnshormonreseptorene med andre bivirkninger som følger av det."}]}]}}]},{"stoff":"telmisartan","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Telmisartan blokkerer reseptore'
    'n (angiotensin 2- reseptor type 1) til angiotensin 2. Angiotensin 2 er en kraftig vasokonstriktor. Ved å blokkere denne reseptoren oppnår man vasodilatasjon og påfølgende fall i blodtrykk."}]},{"type":"paragraph","content":[{"type":"text","text":"Reseptorer for angiotensin 2 finnes også i:"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"tex'
    't","text":"bakre hypofyselapp: blokkering via telmisartan medfører redusert frigjøring av antidiuretisk hormon (ADH)."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"binyrebarken: blokkering via telmisartan medfører redusert frigjøring av aldosteron."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"nyren: blokkering'
    ' via telmisartan medfører redusert gjenopptak av vann og natrium."}]}]}]}]},"kort":[{"maal":"Angiotensin II AT1-reseptor","effekt":"Blokkerer / antagonist","mekanisme":"antagonisme","retning":"ned","merknad":"Gir vasodilatasjon; reduserer ADH, aldosteron og renal reabsorpsjon av Na+/vann som nedstrøms effekter","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text'
    '":"Telmisartan blokkerer reseptoren (angiotensin 2- reseptor type 1) til angiotensin 2. Angiotensin 2 er en kraftig vasokonstriktor. Ved å blokkere denne reseptoren oppnår man vasodilatasjon og påfølgende fall i blodtrykk."}]},{"type":"paragraph","content":[{"type":"text","text":"Reseptorer for angiotensin 2 finnes også i:"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"'
    'paragraph","content":[{"type":"text","text":"bakre hypofyselapp: blokkering via telmisartan medfører redusert frigjøring av antidiuretisk hormon (ADH)."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"binyrebarken: blokkering via telmisartan medfører redusert frigjøring av aldosteron."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type'
    '":"text","text":"nyren: blokkering via telmisartan medfører redusert gjenopptak av vann og natrium."}]}]}]}]}}]},{"stoff":"trimipramin","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Hemmer reopptak av noradrenalin og serotonin. Kraftig histaminantagonist. Hemmer hvilesekresjon i ventrikkelen ca. 50 %."}]}]},"kort":[{"maal":"Noradrenalinreopptak / NET","effekt'
    '":"Hemmer reopptak","mekanisme":"reopptakshemming","retning":"ned"},{"maal":"Serotoninreopptak / SERT","effekt":"Hemmer reopptak","mekanisme":"reopptakshemming","retning":"ned"},{"maal":"Histaminreseptorer","effekt":"Antagonist","mekanisme":"antagonisme","retning":"ned","kvalifikasjon":"Kraftig histaminantagonist","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","t'
    'ext":"Hemmer hvilesekresjon i ventrikkelen ca. 50 %."}]}]}}]},{"stoff":"valsartan","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Valsartan blokkerer reseptoren (angiotensin 2- reseptor type 1) til angiotensin 2. Angiotensin 2 er en kraftig vasokonstriktor. Ved å blokkere denne reseptoren oppnår man vasodilatasjon og påfølgende fall i blodtrykk."}]},{"type":"p'
    'aragraph","content":[{"type":"text","text":"Reseptorer for angiotensin 2 finnes også i:"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"bakre hypofyselapp: blokkering via valsartan medfører redusert frigjøring av antidiuretisk hormon (ADH)."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text'
    '":"binyrebarken: blokkering via valsartan medfører redusert frigjøring av aldosteron."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"nyren: blokkering via valsartan medfører redusert gjenopptak av vann og natrium."}]}]}]}]},"kort":[{"maal":"Angiotensin II AT1-reseptor","effekt":"Blokkerer / antagonist","mekanisme":"antagonisme","retning":"ned","merknad":"'
    'Gir vasodilatasjon; reduserer ADH, aldosteron og renal reabsorpsjon av Na+/vann som nedstrøms effekter","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Valsartan blokkerer reseptoren (angiotensin 2- reseptor type 1) til angiotensin 2. Angiotensin 2 er en kraftig vasokonstriktor. Ved å blokkere denne reseptoren oppnår man vasodilatasjon og påfølgende fall i'
    ' blodtrykk."}]},{"type":"paragraph","content":[{"type":"text","text":"Reseptorer for angiotensin 2 finnes også i:"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"bakre hypofyselapp: blokkering via valsartan medfører redusert frigjøring av antidiuretisk hormon (ADH)."}]}]},{"type":"listItem","content":[{"type":"paragraph","cont'
    'ent":[{"type":"text","text":"binyrebarken: blokkering via valsartan medfører redusert frigjøring av aldosteron."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"nyren: blokkering via valsartan medfører redusert gjenopptak av vann og natrium."}]}]}]}]}}]},{"stoff":"venlafaksin","fra":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","tex'
    't":"Hemmer reopptak av noradrenalin og serotonin. Svak hemmer av dopaminreopptak."}]},{"type":"paragraph","content":[{"type":"text","text":"Aktiv metabolitt: O-desmetylvenlafaksin, som regnes som ekvipotent med venlafaksin."}]},{"type":"paragraph","content":[{"type":"text","text":"Både moderstoff og metabolitt reduserer β-adrenerg responsivitet både ved korttids- og langtidsbehandling."}]}]},"kort'
    '":[{"maal":"Noradrenalinreopptak / NET","effekt":"Hemmer reopptak","mekanisme":"reopptakshemming","retning":"ned","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Aktiv metabolitt: O-desmetylvenlafaksin, som regnes som ekvipotent med venlafaksin."}]}]}},{"maal":"Serotoninreopptak / SERT","effekt":"Hemmer reopptak","mekanisme":"reopptakshemming","retning":"n'
    'ed"},{"maal":"Dopaminreopptak / DAT","effekt":"Hemmer reopptak svakt","mekanisme":"reopptakshemming","retning":"ned","kvalifikasjon":"Svak effekt"},{"maal":"β-adrenerg responsivitet","effekt":"Reduserer responsivitet","mekanisme":"reseptorpavirkning","retning":"ned","merknad":"Gjelder både moderstoff og O-desmetylvenlafaksin ved kort- og langtidsbehandling"}]},{"stoff":"verapamil","fra":{"type":"d'
    'oc","content":[{"type":"paragraph","content":[{"type":"text","text":"Kalsiumantagonist, fenylalkylaminderivat. Hemmer selektivt langsomme spenningstyrte L-type kalsiumkanaler i sarcolemma i både hjertemuskelceller og glatte muskelceller. Dette fører også til mindre frigivelse av kalsiumioner intracellulært. Effekten er vasodilatasjon (redusert afterload), nedsatt perifer motstand og reduksjon i bl'
    'odtrykk. Vasodilatasjon skjer også i kransarteriene."}]},{"type":"paragraph","content":[{"type":"text","text":"Redusert smerte ved angina pectoris fordi verapamil reduserer hjertets pumpekraft som betyr redusert oksygenbehov og samtidig øker blodforsyningen til hjertemuskelen pga. vasodilatasjon."}]},{"type":"paragraph","content":[{"type":"text","text":"Antiarytmisk effekt fordi verapamil spesifik'
    't påvirker hjertes ledningssystem: forsinker ledningstid i AV-knuten og setter ned frekvens i sinusknuten."}]},{"type":"paragraph","content":[{"type":"text","text":"Blodtrykksreduksjon ved monoterapi, sittende systolisk/diastolisk blodtrykk: 14,4 ± 2,1 / 12,1 ± 2,8 mmHg (gjennomsnitt ± SD), ifølge metastudien fra Wu et al. (2005)."}]}]},"kort":[{"maal":"Spenningsstyrte L-type Ca2+-kanaler","effekt'
    '":"Hemmer / blokkerer","mekanisme":"kanalblokkering","retning":"ned","merknad":"Gjelder både hjertemuskelceller og glatt muskulatur; gir vasodilatasjon og påvirker AV- og sinusknute","dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Kalsiumantagonist, fenylalkylaminderivat. Hemmer selektivt langsomme spenningstyrte L-type kalsiumkanaler i sarcolemma i både h'
    'jertemuskelceller og glatte muskelceller. Dette fører også til mindre frigivelse av kalsiumioner intracellulært. Effekten er vasodilatasjon (redusert afterload), nedsatt perifer motstand og reduksjon i blodtrykk. Vasodilatasjon skjer også i kransarteriene."}]},{"type":"paragraph","content":[{"type":"text","text":"Redusert smerte ved angina pectoris fordi verapamil reduserer hjertets pumpekraft som'
    ' betyr redusert oksygenbehov og samtidig øker blodforsyningen til hjertemuskelen pga. vasodilatasjon."}]},{"type":"paragraph","content":[{"type":"text","text":"Antiarytmisk effekt fordi verapamil spesifikt påvirker hjertes ledningssystem: forsinker ledningstid i AV-knuten og setter ned frekvens i sinusknuten."}]},{"type":"paragraph","content":[{"type":"text","text":"Blodtrykksreduksjon ved monoter'
    'api, sittende systolisk/diastolisk blodtrykk: 14,4 ± 2,1 / 12,1 ± 2,8 mmHg (gjennomsnitt ± SD), ifølge metastudien fra Wu et al. (2005)."}]}]}}]}]'::jsonb) loop
    select s.objekt_id into side from public.infosider s where s.tilstand = 'publisert' and s.slug = konvertering->>'stoff';

    -- Teksten slik den ble importert, uten upublisert utkast.
    select u.objekt_id, u.revisjon, r.innhold into e
    from public.innholdselementer t
    join public.objekttilstander u on u.objekt_id = t.objekt_id and u.tilstand = 'utkast'
    join public.objekttilstander p on p.objekt_id = t.objekt_id and p.tilstand = 'publisert' and p.revisjon = u.revisjon
    join public.objektrevisjoner r on r.objekt_id = t.objekt_id and r.revisjon = u.revisjon
    where t.tilstand = 'publisert' and t.infoside_id = side
      and t.panel = 'farmakodynamikk' and t.elementtype = 'riktekst'
      and r.innhold->'data'->'dokument' = konvertering->'fra'
    order by t.posisjon, t.objekt_id
    limit 1;
    if not found then
      raise notice 'Gjør ikke om farmakodynamikken på %: fant ikke teksten slik den ble importert, eller den har et upublisert utkast.',
        konvertering->>'stoff';
      continue;
    end if;

    -- Kortene, i rekkefølge, med kildene til teksten.
    perform set_config('far.revisjonskilde', 'Farmakodynamikken strukturert som mekanismekort etter kartleggingen i docs/farmakodynamikk-kort-kartlegging.md', true);
    for kort, posisjon in select k, i - 1 from jsonb_array_elements(konvertering->'kort') with ordinality as a(k, i) loop
      objekt := (public.opprett_utkast('innholdselement', jsonb_build_object(
        'infoside', side,
        'panel', 'farmakodynamikk',
        'posisjon', posisjon,
        'elementtype', 'mekanismekort',
        'data', kort
      ) || jsonb_strip_nulls(jsonb_build_object('referanser', e.innhold->'referanser')))).id;
      perform public.publiser_utkast(objekt, 1);
    end loop;

    -- Teksten tas bort fra siden, men står i historikken.
    perform set_config('far.revisjonskilde', 'Farmakodynamikkteksten erstattet av mekanismekort etter kartleggingen i docs/farmakodynamikk-kort-kartlegging.md', true);
    perform public.lagre_utkast(e.objekt_id, e.revisjon, jsonb_set(e.innhold, '{panel}', to_jsonb('fjernet'::text)));
    perform public.publiser_utkast(e.objekt_id, e.revisjon + 1);
  end loop;
end
$farmakodynamikk$;