-- Regelsettene for de enkle konsentrasjonsreglene
do $import$
declare
  importdata constant text := $data$[
{"kilde":"Importert fra kommentarer.pdf, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"KLOSUM","enhet":"nmol/L","desimaler":0,"skillepunkter":[10,2000],"intervaller":[{"niva":"under","handling":null,"kommentar":"7e31c0f6-734f-91df-612c-bcd4a7c74ba5"},{"niva":"innenfor","handling":null,"kommentar":"afba8910-d64d-4d75-c54d-b8165d9cdd0a"},{"niva":"over","handling":"ring_rekvirent","kommentar":"e575c05f-b4de-5c57-641c-d60ef40d9cb2"}],"ringegrense":2000,"cutoff":{"innledning":"fddb8133-3179-5d53-42e3-420014cc75da","kommentar":"afba8910-d64d-4d75-c54d-b8165d9cdd0a"},"kommentarer":[{"id":"7e31c0f6-734f-91df-612c-bcd4a7c74ba5","tekst":"Manglende etterlevelse? Er riktig analyse rekvirert? Referanseområdet er basert på summen av klomipramin og desmetylklomipramin, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"afba8910-d64d-4d75-c54d-b8165d9cdd0a","tekst":"Referanseområdet er basert på summen av klomipramin og desmetylklomipramin, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"e575c05f-b4de-5c57-641c-d60ef40d9cb2","tekst":"Potensielt toksisk konsentrasjon. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no). Referanseområdet er basert på summen av klomipramin og desmetylklomipramin, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon."},{"id":"fddb8133-3179-5d53-42e3-420014cc75da","tekst":"Prøven inneholder en lav konsentrasjon av klomipramin og/eller desmetylklomipramin som ligger under påvisningsgrensen."}]}},
{"kilde":"Importert fra kommentarer.pdf, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"KLOZ","enhet":"nmol/L","desimaler":0,"skillepunkter":[30,3000],"intervaller":[{"niva":"under","handling":null,"kommentar":"dc05b5d0-fbdd-1775-6790-28ae5463dca7"},{"niva":"innenfor","handling":null,"kommentar":"26dfbc24-4142-7eb1-8b8b-5b57ed53415d"},{"niva":"over","handling":"ring_rekvirent","kommentar":"2abc3fc5-9796-27b1-2e02-041d7358b872"}],"ringegrense":3000,"cutoff":{"innledning":"3ac25625-6d0a-7464-757d-53e09cb6153c","kommentar":"26dfbc24-4142-7eb1-8b8b-5b57ed53415d"},"kommentarer":[{"id":"dc05b5d0-fbdd-1775-6790-28ae5463dca7","tekst":"Manglende etterlevelse? Er riktig analyse rekvirert? Referanseområdet for klozapin er basert på bruk av 100–900 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"26dfbc24-4142-7eb1-8b8b-5b57ed53415d","tekst":"Referanseområdet for klozapin er basert på bruk av 100–900 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"2abc3fc5-9796-27b1-2e02-041d7358b872","tekst":"Potensielt toksisk konsentrasjon. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no). Referanseområdet for klozapin er basert på bruk av 100–900 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon."},{"id":"3ac25625-6d0a-7464-757d-53e09cb6153c","tekst":"Prøven inneholder en lav konsentrasjon av klozapin som ligger under påvisningsgrensen."}]}},
{"kilde":"Importert fra kommentarer.pdf, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"KVE","enhet":"nmol/L","desimaler":0,"skillepunkter":[15,2600],"intervaller":[{"niva":"under","handling":null,"kommentar":"0647f1d8-f841-9ceb-5700-d40525c9b342"},{"niva":"innenfor","handling":null,"kommentar":"086f2589-9e28-b7f6-b953-1b3fe7181b18"},{"niva":"over","handling":"ring_rekvirent","kommentar":"31d735c6-405d-e8c4-e762-94eff7716d99"}],"ringegrense":2600,"cutoff":{"innledning":"0bae6989-caa4-1f4e-8d4e-9e869f0e7786","kommentar":"086f2589-9e28-b7f6-b953-1b3fe7181b18"},"kommentarer":[{"id":"0647f1d8-f841-9ceb-5700-d40525c9b342","tekst":"Kvetiapinkonsentrasjon lavere enn referanseområdet eller under påvisningsgrensen er forventet ved bruk av doser < 100 mg. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"086f2589-9e28-b7f6-b953-1b3fe7181b18","tekst":"Referanseområdet for kvetiapin er basert på bruk av 50–1000 mg daglig, prøvetaking 12 timer ± 1 time etter siste dose ved bruk av tabletter og 18–24 timer ved bruk av depottablett og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"31d735c6-405d-e8c4-e762-94eff7716d99","tekst":"Potensielt toksisk konsentrasjon. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no). Referanseområdet for kvetiapin er basert på bruk av 50–1000 mg daglig, prøvetaking 12 timer ± 1 time etter siste dose ved bruk av tabletter og 18–24 timer ved bruk av depottablett og oppnådd likevektskonsentrasjon."},{"id":"0bae6989-caa4-1f4e-8d4e-9e869f0e7786","tekst":"Prøven inneholder en lav konsentrasjon av kvetiapin som ligger under påvisningsgrensen."}]}},
{"kilde":"Importert fra AHT.docx, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"LABE","enhet":"nmol/L","desimaler":0,"skillepunkter":[50,4000],"intervaller":[{"niva":"under","handling":null,"kommentar":"230b8cd8-1b33-98e2-7f6c-3d64ae5c1fda"},{"niva":"innenfor","handling":null,"kommentar":"bb1e5551-7619-3fb3-d1b9-6b36e5c64cdc"},{"niva":"over","handling":null,"kommentar":"217a3b5f-67b7-2c8d-f5d5-33ba9e3330e4"}],"ringegrense":null,"cutoff":null,"kommentarer":[{"id":"230b8cd8-1b33-98e2-7f6c-3d64ae5c1fda","tekst":"Mangelfull medikamentetterlevelse? Farmakokinetiske avvik? Referanseområdet for labetalol er basert på bruk av 200–2400 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"bb1e5551-7619-3fb3-d1b9-6b36e5c64cdc","tekst":"Referanseområdet for labetalol er basert på bruk av 200–2400 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"217a3b5f-67b7-2c8d-f5d5-33ba9e3330e4","tekst":"Potensielt toksisk konsentrasjon. Referanseområdet for labetalol er basert på bruk av 200–2400 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."}]}},
{"kilde":"Importert fra kommentarer.pdf, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"LAM","enhet":"µmol/L","desimaler":0,"skillepunkter":[2,75],"intervaller":[{"niva":"under","handling":null,"kommentar":"b49b359a-cf35-98c9-bc0f-e250c6a32520"},{"niva":"innenfor","handling":null,"kommentar":"dd6b9fb8-6f60-eb63-4811-814fdf571678"},{"niva":"over","handling":"ring_rekvirent","kommentar":"958d722b-e753-67e5-9440-ac6e10fb6155"}],"ringegrense":75,"cutoff":null,"kommentarer":[{"id":"b49b359a-cf35-98c9-bc0f-e250c6a32520","tekst":"Manglende etterlevelse? Er riktig analyse rekvirert? Referanseområdet for lamotrigin er basert på prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon, og er primært etablert for behandling av epilepsi. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"dd6b9fb8-6f60-eb63-4811-814fdf571678","tekst":"Referanseområdet for lamotrigin er basert på prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon, og er primært etablert for behandling av epilepsi. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"958d722b-e753-67e5-9440-ac6e10fb6155","tekst":"Potensielt toksisk konsentrasjon. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no). Referanseområdet for lamotrigin er basert på prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon, og er primært etablert for behandling av epilepsi."}]}},
{"kilde":"Importert fra AHT.docx, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"LERK","enhet":"nmol/L","desimaler":1,"skillepunkter":[0.2,20],"intervaller":[{"niva":"under","handling":null,"kommentar":"30b6c0b5-d319-b245-2a3c-29b3e5307291"},{"niva":"innenfor","handling":null,"kommentar":"c133226d-3560-6227-86f6-d556641d8a30"},{"niva":"over","handling":null,"kommentar":"5404ac19-1a79-ca88-389d-7d2c0c3e5e3c"}],"ringegrense":null,"cutoff":null,"kommentarer":[{"id":"30b6c0b5-d319-b245-2a3c-29b3e5307291","tekst":"Mangelfull medikamentetterlevelse? Farmakokinetiske avvik? Referanseområdet for lerkanidipin er basert på bruk av 10–20 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"c133226d-3560-6227-86f6-d556641d8a30","tekst":"Referanseområdet for lerkanidipin er basert på bruk av 10–20 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"5404ac19-1a79-ca88-389d-7d2c0c3e5e3c","tekst":"Potensielt toksisk konsentrasjon. Referanseområdet for lerkanidipin er basert på bruk av 10–20 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."}]}},
{"kilde":"Importert fra AHT.docx, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"LISI","enhet":"nmol/L","desimaler":0,"skillepunkter":[10,1200],"intervaller":[{"niva":"under","handling":null,"kommentar":"be5354f5-ac89-de3b-cb64-eeb454d59a15"},{"niva":"innenfor","handling":null,"kommentar":"38c546f0-dd7b-4d0c-fd0c-eb4b0aad7ccf"},{"niva":"over","handling":null,"kommentar":"2607d8e3-a37b-3b50-2082-d37aabc29b44"}],"ringegrense":null,"cutoff":null,"kommentarer":[{"id":"be5354f5-ac89-de3b-cb64-eeb454d59a15","tekst":"Mangelfull medikamentetterlevelse? Farmakokinetiske avvik? Referanseområdet for lisinopril er basert på bruk av 5–80 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"38c546f0-dd7b-4d0c-fd0c-eb4b0aad7ccf","tekst":"Referanseområdet for lisinopril er basert på bruk av 5–80 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"2607d8e3-a37b-3b50-2082-d37aabc29b44","tekst":"Potensielt toksisk konsentrasjon. Referanseområdet for lisinopril er basert på bruk av 5–80 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."}]}},
{"kilde":"Importert fra kommentarer.pdf, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"LMP","enhet":"nmol/L","desimaler":0,"skillepunkter":[5,970],"intervaller":[{"niva":"under","handling":null,"kommentar":"7d720510-f45c-fdde-3d2a-d4ae41e354cb"},{"niva":"innenfor","handling":null,"kommentar":"76c6798b-4ed1-895d-8fc0-341467edcbcc"},{"niva":"over","handling":"ring_rekvirent","kommentar":"a4d851fa-97a7-5b6b-de08-e10eabcd5169"}],"ringegrense":970,"cutoff":{"innledning":"92c9c571-408d-2b48-29ba-3b35b4cb19ca","kommentar":"76c6798b-4ed1-895d-8fc0-341467edcbcc"},"kommentarer":[{"id":"7d720510-f45c-fdde-3d2a-d4ae41e354cb","tekst":"Manglende etterlevelse? Er riktig analyse rekvirert? Referanseområdet for levomepromazin er basert på prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Referanseområdet omfatter ikke bruk av levomepromazin som primær antipsykotisk behandling. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"76c6798b-4ed1-895d-8fc0-341467edcbcc","tekst":"Referanseområdet er basert på prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Referanseområdet omfatter ikke bruk av levomepromazin som primær antipsykotisk behandling. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"a4d851fa-97a7-5b6b-de08-e10eabcd5169","tekst":"Potensielt toksisk konsentrasjon. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no). Referanseområdet er basert på prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Referanseområdet omfatter ikke bruk av levomepromazin som primær antipsykotisk behandling."},{"id":"92c9c571-408d-2b48-29ba-3b35b4cb19ca","tekst":"Prøven inneholder en lav konsentrasjon av levomepromazin som ligger under påvisningsgrensen."}]}},
{"kilde":"Importert fra AHT.docx, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"LOSYR","enhet":"nmol/L","desimaler":0,"skillepunkter":[30,1400],"intervaller":[{"niva":"under","handling":null,"kommentar":"2dc20af4-aa70-8094-ff93-ceafd7ad1cab"},{"niva":"innenfor","handling":null,"kommentar":"5da353a1-5dc1-a33d-3556-d3d2e93b0698"},{"niva":"over","handling":null,"kommentar":"25a84bd9-22ce-9b9f-deb2-07adbc256930"}],"ringegrense":null,"cutoff":null,"kommentarer":[{"id":"2dc20af4-aa70-8094-ff93-ceafd7ad1cab","tekst":"Mangelfull medikamentetterlevelse? Farmakokinetiske avvik? Losartansyre er den aktive metabolitten av losartan. Referanseområdet for losartansyre er basert på bruk av 50–100 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"5da353a1-5dc1-a33d-3556-d3d2e93b0698","tekst":"Losartansyre er den aktive metabolitten av losartan. Referanseområdet for losartansyre er basert på bruk av 50–100 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"25a84bd9-22ce-9b9f-deb2-07adbc256930","tekst":"Potensielt toksisk konsentrasjon. Losartansyre er den aktive metabolitten av losartan. Referanseområdet for losartansyre er basert på bruk av 50–100 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."}]}},
{"kilde":"Importert fra kommentarer.pdf, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"LURA","enhet":"nmol/L","desimaler":0,"skillepunkter":[2,120],"intervaller":[{"niva":"under","handling":null,"kommentar":"0783d43e-d51b-40bc-e402-17d4e1cc8c7e"},{"niva":"innenfor","handling":null,"kommentar":"62d33f4a-ccbc-21a3-3a8e-19b57b50581a"},{"niva":"over","handling":"ring_rekvirent","kommentar":"b0584b18-05a0-220e-31c5-bcb565aee8a2"}],"ringegrense":120,"cutoff":{"innledning":"a29cd182-d640-fb3d-c429-1833f9bb67aa","kommentar":"62d33f4a-ccbc-21a3-3a8e-19b57b50581a"},"kommentarer":[{"id":"0783d43e-d51b-40bc-e402-17d4e1cc8c7e","tekst":"Manglende etterlevelse? Er riktig analyse rekvirert? Referanseområdet for lurasidon er basert på prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"62d33f4a-ccbc-21a3-3a8e-19b57b50581a","tekst":"Referanseområdet for lurasidon er basert på prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"b0584b18-05a0-220e-31c5-bcb565aee8a2","tekst":"Potensielt toksisk konsentrasjon. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no). Referanseområdet for lurasidon er basert på prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon."},{"id":"a29cd182-d640-fb3d-c429-1833f9bb67aa","tekst":"Prøven inneholder en lav konsentrasjon av lurasidon som ligger under påvisningsgrensen."}]}}
]$data$;
  administrator uuid;
  import jsonb;
  status public.objektstatus;
begin
  if md5(importdata) <> '31c18ee9a10c60203e64540a10065253' then
    raise exception 'Importdataene er ikke de som ble laget: kontrollsummen stemmer ikke.';
  end if;
  select p.id into administrator from public.profiles p where p.username = 'peohol' and p.role = 'admin';
  if administrator is null then
    raise notice 'Fant ingen administrator med brukernavnet %.', 'peohol';
    return;
  end if;
  perform set_config('request.jwt.claims', jsonb_build_object('sub', administrator, 'role', 'authenticated')::text, true);

  for import in
    select e.v from jsonb_array_elements(importdata::jsonb) with ordinality e(v, nr) order by e.nr
  loop
    if exists (
      select 1 from public.intervallregelsett s
      where s.tilstand = 'utkast' and s.analyttkode = import #>> '{regelsett,analyttkode}'
    ) then
      raise notice '% har alt et regelsett og hoppes over.', import #>> '{regelsett,analyttkode}';
      continue;
    end if;
    perform set_config('far.revisjonskilde', import ->> 'kilde', true);
    status := public.opprett_utkast('intervallregelsett', import -> 'regelsett');
    perform public.publiser_utkast(status.id, status.revisjon);
  end loop;

  perform set_config('far.revisjonskilde', '', true);
end
$import$;