-- Regelsettene for de enkle konsentrasjonsreglene
do $import$
declare
  importdata constant text := $data$[
{"kilde":"Importert fra AHT.docx, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"DIL","enhet":"nmol/L","desimaler":0,"skillepunkter":[100,2000],"intervaller":[{"niva":"under","handling":null,"kommentar":"205c749d-894e-a7c8-de12-5b09bac4fc13"},{"niva":"innenfor","handling":null,"kommentar":"6f614f51-62da-8511-6ada-0393dd72b509"},{"niva":"over","handling":null,"kommentar":"1afc2e14-b3c5-1898-54e0-6ebffe4c3f8f"}],"ringegrense":null,"cutoff":null,"kommentarer":[{"id":"205c749d-894e-a7c8-de12-5b09bac4fc13","tekst":"Mangelfull medikamentetterlevelse? Farmakokinetiske avvik? Referanseområdet for diltiazem er basert på bruk av 240–480 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"6f614f51-62da-8511-6ada-0393dd72b509","tekst":"Referanseområdet for diltiazem er basert på bruk av 240–480 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"1afc2e14-b3c5-1898-54e0-6ebffe4c3f8f","tekst":"Potensielt toksisk konsentrasjon. Referanseområdet for diltiazem er basert på bruk av 240–480 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."}]}},
{"kilde":"Importert fra AHT.docx, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"DOKSA","enhet":"nmol/L","desimaler":0,"skillepunkter":[5,320],"intervaller":[{"niva":"under","handling":null,"kommentar":"9f193311-0784-3044-8758-69f7dad09096"},{"niva":"innenfor","handling":null,"kommentar":"1315a776-979b-e741-911d-222ce4ea40c7"},{"niva":"over","handling":null,"kommentar":"fb0be38f-f895-66ea-a945-4a038917cd63"}],"ringegrense":null,"cutoff":null,"kommentarer":[{"id":"9f193311-0784-3044-8758-69f7dad09096","tekst":"Mangelfull medikamentetterlevelse? Farmakokinetiske avvik? Referanseområdet for doksazosin er basert på bruk av 4–8 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"1315a776-979b-e741-911d-222ce4ea40c7","tekst":"Referanseområdet for doksazosin er basert på bruk av 4–8 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"fb0be38f-f895-66ea-a945-4a038917cd63","tekst":"Potensielt toksisk konsentrasjon. Referanseområdet for doksazosin er basert på bruk av 4–8 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."}]}},
{"kilde":"Importert fra kommentarer.pdf, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"DOKSUM","enhet":"nmol/L","desimaler":0,"skillepunkter":[20,1001,1100],"intervaller":[{"niva":"under","handling":null,"kommentar":"27397984-3277-f635-c22e-d14b1c339855"},{"niva":"innenfor","handling":null,"kommentar":"e9a52177-ecd0-b899-a52d-cf8d870188df"},{"niva":"innenfor","handling":"ring_rekvirent","kommentar":"e9a52177-ecd0-b899-a52d-cf8d870188df"},{"niva":"over","handling":"ring_rekvirent","kommentar":"92e1cdff-c4ab-c978-f46b-67eed5dedc8e"}],"ringegrense":1000,"cutoff":{"innledning":"d5cd9098-49a3-2318-fd99-3937007fbead","kommentar":"e9a52177-ecd0-b899-a52d-cf8d870188df"},"kommentarer":[{"id":"27397984-3277-f635-c22e-d14b1c339855","tekst":"Manglende etterlevelse? Er riktig analyse rekvirert? Referanseområdet er basert på summen av doksepin og desmetyldoksepin, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"e9a52177-ecd0-b899-a52d-cf8d870188df","tekst":"Referanseområdet er basert på summen av doksepin og desmetyldoksepin, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"92e1cdff-c4ab-c978-f46b-67eed5dedc8e","tekst":"Potensielt toksisk konsentrasjon. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no). Referanseområdet er basert på summen av doksepin og desmetyldoksepin, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon."},{"id":"d5cd9098-49a3-2318-fd99-3937007fbead","tekst":"Prøven inneholder en lav konsentrasjon av doksepin og/eller desmetyldoksepin som ligger under påvisningsgrensen."}]}},
{"kilde":"Importert fra kommentarer.pdf, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"DULO","enhet":"nmol/L","desimaler":0,"skillepunkter":[20,600],"intervaller":[{"niva":"under","handling":null,"kommentar":"8cacc1c1-348e-9872-4ed8-4deb92778d49"},{"niva":"innenfor","handling":null,"kommentar":"c9b1bdec-8a97-7229-0fc5-4e38313aa361"},{"niva":"over","handling":"ring_rekvirent","kommentar":"ee47f0aa-c830-9f6d-4d54-377ef9661cdb"}],"ringegrense":600,"cutoff":{"innledning":"59693527-7f51-5fe4-9001-64476a3ed1c0","kommentar":"c9b1bdec-8a97-7229-0fc5-4e38313aa361"},"kommentarer":[{"id":"8cacc1c1-348e-9872-4ed8-4deb92778d49","tekst":"Manglende etterlevelse? Er riktig analyse rekvirert? Referanseområdet for duloksetin er basert på bruk av 60–120 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"c9b1bdec-8a97-7229-0fc5-4e38313aa361","tekst":"Referanseområdet for duloksetin er basert på bruk av 60–120 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"ee47f0aa-c830-9f6d-4d54-377ef9661cdb","tekst":"Potensielt toksisk konsentrasjon. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no). Referanseområdet for duloksetin er basert på bruk av 60–120 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon."},{"id":"59693527-7f51-5fe4-9001-64476a3ed1c0","tekst":"Prøven inneholder en lav konsentrasjon av duloksetin som ligger under påvisningsgrensen."}]}},
{"kilde":"Importert fra AHT.docx, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"ENAT","enhet":"nmol/L","desimaler":0,"skillepunkter":[10,1200],"intervaller":[{"niva":"under","handling":null,"kommentar":"a493c304-2048-1060-a70b-37dc1704a1ec"},{"niva":"innenfor","handling":null,"kommentar":"6031b79c-e0d3-fc8f-229b-5fe1d55c49fe"},{"niva":"over","handling":null,"kommentar":"0063b682-aaf9-9c53-e20e-f9559a2644c1"}],"ringegrense":null,"cutoff":null,"kommentarer":[{"id":"a493c304-2048-1060-a70b-37dc1704a1ec","tekst":"Mangelfull medikamentetterlevelse? Farmakokinetiske avvik? Enalaprilat er den aktive metabolitten av enalapril. Referanseområdet for enalaprilat er basert på bruk av 5–40 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"6031b79c-e0d3-fc8f-229b-5fe1d55c49fe","tekst":"Enalaprilat er den aktive metabolitten av enalapril. Referanseområdet for enalaprilat er basert på bruk av 5–40 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"0063b682-aaf9-9c53-e20e-f9559a2644c1","tekst":"Potensielt toksisk konsentrasjon. Enalaprilat er den aktive metabolitten av enalapril. Referanseområdet for enalaprilat er basert på bruk av 5–40 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."}]}},
{"kilde":"Importert fra AHT.docx, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"EPLR","enhet":"nmol/L","desimaler":1,"skillepunkter":[3.5,1400],"intervaller":[{"niva":"under","handling":null,"kommentar":"129b8407-305c-b7dd-8798-a49ebcc6359f"},{"niva":"innenfor","handling":null,"kommentar":"0b4ead61-128a-7dcb-77da-d979d59f454c"},{"niva":"over","handling":null,"kommentar":"b4f747d7-48bd-e99f-9669-96d6a3895e40"}],"ringegrense":null,"cutoff":null,"kommentarer":[{"id":"129b8407-305c-b7dd-8798-a49ebcc6359f","tekst":"Mangelfull medikamentetterlevelse? Farmakokinetiske avvik? Referanseområdet for eplerenon er basert på bruk av 25–50 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"0b4ead61-128a-7dcb-77da-d979d59f454c","tekst":"Referanseområdet for eplerenon er basert på bruk av 25–50 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"b4f747d7-48bd-e99f-9669-96d6a3895e40","tekst":"Potensielt toksisk konsentrasjon. Referanseområdet for eplerenon er basert på bruk av 25–50 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."}]}},
{"kilde":"Importert fra kommentarer.pdf, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"ESCIT","enhet":"nmol/L","desimaler":0,"skillepunkter":[10,280],"intervaller":[{"niva":"under","handling":null,"kommentar":"bdf87903-fce7-2c3f-b198-9fe83175cd64"},{"niva":"innenfor","handling":null,"kommentar":"0f8322dd-0f5e-df08-7d90-676cbe389a6c"},{"niva":"over","handling":"ring_rekvirent","kommentar":"7e44f9fb-e696-6d91-8659-d0f768b86b15"}],"ringegrense":280,"cutoff":{"innledning":"1c46dfe2-15cd-903e-b7e3-a938df1e7364","kommentar":"0f8322dd-0f5e-df08-7d90-676cbe389a6c"},"kommentarer":[{"id":"bdf87903-fce7-2c3f-b198-9fe83175cd64","tekst":"Manglende etterlevelse? Er riktig analyse rekvirert? Referanseområdet for escitalopram er basert på bruk av 10–30 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"0f8322dd-0f5e-df08-7d90-676cbe389a6c","tekst":"Referanseområdet for escitalopram er basert på bruk av 10–30 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"7e44f9fb-e696-6d91-8659-d0f768b86b15","tekst":"Potensielt toksisk konsentrasjon. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no). Referanseområdet for escitalopram er basert på bruk av 10–30 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon."},{"id":"1c46dfe2-15cd-903e-b7e3-a938df1e7364","tekst":"Prøven inneholder en lav konsentrasjon av escitalopram som ligger under påvisningsgrensen."}]}},
{"kilde":"Importert fra kommentarer.pdf, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"FLUOSUM","enhet":"nmol/L","desimaler":0,"skillepunkter":[50,5000],"intervaller":[{"niva":"under","handling":null,"kommentar":"0ca79dcf-b040-53aa-046c-a99d45357c6e"},{"niva":"innenfor","handling":null,"kommentar":"60ff1b65-ee68-e047-300d-297aa58dca35"},{"niva":"over","handling":"ring_rekvirent","kommentar":"cdf664b6-1ec3-6dce-7ea4-62e1e9bb6e3c"}],"ringegrense":5000,"cutoff":{"innledning":"4580121d-0558-1419-bead-e4f96fb57a32","kommentar":"60ff1b65-ee68-e047-300d-297aa58dca35"},"kommentarer":[{"id":"0ca79dcf-b040-53aa-046c-a99d45357c6e","tekst":"Manglende etterlevelse? Er riktig analyse rekvirert? Referanseområdet er basert på summen av fluoksetin og norfluoksetin ved bruk av 20–60 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"60ff1b65-ee68-e047-300d-297aa58dca35","tekst":"Referanseområdet er basert på summen av fluoksetin og norfluoksetin ved bruk av 20–60 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"cdf664b6-1ec3-6dce-7ea4-62e1e9bb6e3c","tekst":"Potensielt toksisk konsentrasjon. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no). Referanseområdet er basert på summen av fluoksetin og norfluoksetin ved bruk av 20–60 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon."},{"id":"4580121d-0558-1419-bead-e4f96fb57a32","tekst":"Prøven inneholder en lav konsentrasjon av fluoksetin og/eller norfluoksetin som ligger under påvisningsgrensen."}]}},
{"kilde":"Importert fra kommentarer.pdf, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"FLUP","enhet":"nmol/L","desimaler":1,"skillepunkter":[0.6,35.1,36],"intervaller":[{"niva":"under","handling":null,"kommentar":"1bf3fa28-ed3a-ee6c-2307-e55ac04360e0"},{"niva":"innenfor","handling":null,"kommentar":"0ac40ff0-beb3-b548-1b4a-359f8638939c"},{"niva":"innenfor","handling":"ring_rekvirent","kommentar":"0ac40ff0-beb3-b548-1b4a-359f8638939c"},{"niva":"over","handling":"ring_rekvirent","kommentar":"3377ea47-be0c-bcb4-521a-a95afeff06c3"}],"ringegrense":35,"cutoff":{"innledning":"51b206b6-e562-1536-4e03-4c6911bd6d35","kommentar":"0ac40ff0-beb3-b548-1b4a-359f8638939c"},"kommentarer":[{"id":"1bf3fa28-ed3a-ee6c-2307-e55ac04360e0","tekst":"Manglende etterlevelse? Er riktig analyse rekvirert? Referanseområdet for flupentiksol er basert på bruk av 1–15 mg flupentiksol daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Ved depot anbefales prøvetaking 0–2 dager før neste injeksjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"0ac40ff0-beb3-b548-1b4a-359f8638939c","tekst":"Referanseområdet for flupentiksol er basert på bruk av 1–15 mg flupentiksol daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Ved depot anbefales prøvetaking 0–2 dager før neste injeksjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"3377ea47-be0c-bcb4-521a-a95afeff06c3","tekst":"Potensielt toksisk konsentrasjon. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no). Referanseområdet for flupentiksol er basert på bruk av 1–15 mg flupentiksol daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Ved depot anbefales prøvetaking 0–2 dager før neste injeksjon."},{"id":"51b206b6-e562-1536-4e03-4c6911bd6d35","tekst":"Prøven inneholder en lav konsentrasjon av flupentiksol som ligger under påvisningsgrensen."}]}},
{"kilde":"Importert fra kommentarer.pdf, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"FLUV","enhet":"nmol/L","desimaler":0,"skillepunkter":[20,1800],"intervaller":[{"niva":"under","handling":null,"kommentar":"31c51cd5-6d11-d693-a83a-954099863fe6"},{"niva":"innenfor","handling":null,"kommentar":"7eaab971-187d-2968-09fa-1b5b2b28ac30"},{"niva":"over","handling":"ring_rekvirent","kommentar":"5ede7f16-f4af-755e-b309-5f308872c2fe"}],"ringegrense":1800,"cutoff":{"innledning":"87b8fd26-4911-18bc-c049-4f3d88b15ddd","kommentar":"7eaab971-187d-2968-09fa-1b5b2b28ac30"},"kommentarer":[{"id":"31c51cd5-6d11-d693-a83a-954099863fe6","tekst":"Manglende etterlevelse? Er riktig analyse rekvirert? Referanseområdet for fluvoksamin er basert på bruk av 100–300 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"7eaab971-187d-2968-09fa-1b5b2b28ac30","tekst":"Referanseområdet for fluvoksamin er basert på bruk av 100–300 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"5ede7f16-f4af-755e-b309-5f308872c2fe","tekst":"Potensielt toksisk konsentrasjon. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no). Referanseområdet for fluvoksamin er basert på bruk av 100–300 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon."},{"id":"87b8fd26-4911-18bc-c049-4f3d88b15ddd","tekst":"Prøven inneholder en lav konsentrasjon av fluvoksamin som ligger under påvisningsgrensen."}]}}
]$data$;
  administrator uuid;
  import jsonb;
  status public.objektstatus;
begin
  if md5(importdata) <> '18e6f8274e6061fecd24e207a20110f4' then
    raise exception 'Importdataene er ikke de som ble laget: kontrollsummen stemmer ikke.';
  end if;
  select p.id into administrator from public.profiles p where p.username = 'peohol' and p.role = 'admin';
  if administrator is null then
    raise notice 'Fant ingen administrator med brukernavnet %.', 'peohol';
    return;
  end if;
  perform set_config('request.jwt.claims', jsonb_build_object('sub', administrator, 'role', 'authenticated')::text, true);

  for import in
    select e.v from jsonb_array_elements(importdata::jsonb) with ordinality e(v, nr) order by e.nr
  loop
    if exists (
      select 1 from public.intervallregelsett s
      where s.tilstand = 'utkast' and s.analyttkode = import #>> '{regelsett,analyttkode}'
    ) then
      raise notice '% har alt et regelsett og hoppes over.', import #>> '{regelsett,analyttkode}';
      continue;
    end if;
    perform set_config('far.revisjonskilde', import ->> 'kilde', true);
    status := public.opprett_utkast('intervallregelsett', import -> 'regelsett');
    perform public.publiser_utkast(status.id, status.revisjon);
  end loop;

  perform set_config('far.revisjonskilde', '', true);
end
$import$;