-- Regelsettene for de enkle konsentrasjonsreglene
do $import$
declare
  importdata constant text := $data$[
{"kilde":"Importert fra kommentarer.pdf, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"RISPSUM","enhet":"nmol/L","desimaler":0,"skillepunkter":[10,240],"intervaller":[{"niva":"under","handling":null,"kommentar":"eb28c3d9-d102-6232-409b-e79a851c5641"},{"niva":"innenfor","handling":null,"kommentar":"fd519f18-6de1-9b80-279b-137b49d0aabe"},{"niva":"over","handling":"ring_rekvirent","kommentar":"1b6311a8-2c55-3cb0-8899-927b00584ca8"}],"ringegrense":240,"cutoff":{"innledning":"13631bc4-c958-8e86-4b1b-aa230e573d23","kommentar":"fd519f18-6de1-9b80-279b-137b49d0aabe"},"kommentarer":[{"id":"eb28c3d9-d102-6232-409b-e79a851c5641","tekst":"Manglende etterlevelse? Er riktig analyse rekvirert? Referanseområdet er basert på summen av risperidon + paliperidon (hydroksyrisperidon) ved bruk av 1–8 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Ved depot anbefales prøvetaking 0–2 dager før neste injeksjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"fd519f18-6de1-9b80-279b-137b49d0aabe","tekst":"Referanseområdet er basert på summen av risperidon + paliperidon (hydroksyrisperidon) ved bruk av 1–8 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Ved depot anbefales prøvetaking 0–2 dager før neste injeksjon. Ved bruk av både risperidon og paliperidon vil begge bidra til påvist paliperidonkonsentrasjon (risperidon omdannes til paliperidon). Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"1b6311a8-2c55-3cb0-8899-927b00584ca8","tekst":"Potensielt toksisk konsentrasjon. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no). Referanseområdet er basert på summen av risperidon + paliperidon (hydroksyrisperidon) ved bruk av 1–8 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Ved depot anbefales prøvetaking 0–2 dager før neste injeksjon. Ved bruk av både risperidon og paliperidon vil begge bidra til påvist paliperidonkonsentrasjon (risperidon omdannes til paliperidon)."},{"id":"13631bc4-c958-8e86-4b1b-aa230e573d23","tekst":"Prøven inneholder en lav konsentrasjon av risperidon og/eller hydroksyrisperidon som ligger under påvisningsgrensen."}]}},
{"kilde":"Importert fra kommentarer.pdf, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"SERT","enhet":"nmol/L","desimaler":0,"skillepunkter":[5,500],"intervaller":[{"niva":"under","handling":null,"kommentar":"b169dad5-3e67-db56-3513-287be592debf"},{"niva":"innenfor","handling":null,"kommentar":"dce384bd-8bab-e5fa-c0ad-ab5daf0b56c8"},{"niva":"over","handling":"ring_rekvirent","kommentar":"e08f6a6f-ee8a-4bff-b9fe-bf51b8547aaf"}],"ringegrense":500,"cutoff":{"innledning":"4dba299c-78a2-ce59-d18e-24a2f698b126","kommentar":"dce384bd-8bab-e5fa-c0ad-ab5daf0b56c8"},"kommentarer":[{"id":"b169dad5-3e67-db56-3513-287be592debf","tekst":"Manglende etterlevelse? Er riktig analyse rekvirert? Referanseområdet for sertralin er basert på bruk av 50–200 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"dce384bd-8bab-e5fa-c0ad-ab5daf0b56c8","tekst":"Referanseområdet for sertralin er basert på bruk av 50–200 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"e08f6a6f-ee8a-4bff-b9fe-bf51b8547aaf","tekst":"Potensielt toksisk konsentrasjon. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no). Referanseområdet for sertralin er basert på bruk av 50–200 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon."},{"id":"4dba299c-78a2-ce59-d18e-24a2f698b126","tekst":"Prøven inneholder en lav konsentrasjon av sertralin som ligger under påvisningsgrensen."}]}},
{"kilde":"Importert fra AHT.docx, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"TELM","enhet":"nmol/L","desimaler":0,"skillepunkter":[8,320],"intervaller":[{"niva":"under","handling":null,"kommentar":"f8ab4219-ed04-3a2d-3c8c-0ab3582a4fe4"},{"niva":"innenfor","handling":null,"kommentar":"c35d0bb6-01a4-d4a4-8599-4f55dbdfd139"},{"niva":"over","handling":null,"kommentar":"3f2aa9fa-4532-9ee8-a9af-86ed64914990"}],"ringegrense":null,"cutoff":null,"kommentarer":[{"id":"f8ab4219-ed04-3a2d-3c8c-0ab3582a4fe4","tekst":"Mangelfull medikamentetterlevelse? Farmakokinetiske avvik? Referanseområdet for telmisartan er basert på bruk av 20–80 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"c35d0bb6-01a4-d4a4-8599-4f55dbdfd139","tekst":"Referanseområdet for telmisartan er basert på bruk av 20–80 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"3f2aa9fa-4532-9ee8-a9af-86ed64914990","tekst":"Potensielt toksisk konsentrasjon. Referanseområdet for telmisartan er basert på bruk av 20–80 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."}]}},
{"kilde":"Importert fra kommentarer.pdf, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"TRIM","enhet":"nmol/L","desimaler":0,"skillepunkter":[10,1600],"intervaller":[{"niva":"under","handling":null,"kommentar":"f8c34b81-5281-6347-f61d-6f77c185c23f"},{"niva":"innenfor","handling":null,"kommentar":"c4d45625-21f3-7007-f68a-41334da97b70"},{"niva":"over","handling":"ring_rekvirent","kommentar":"8a678087-f2b0-2421-959d-9bf0f516cea2"}],"ringegrense":1600,"cutoff":{"innledning":"1dc859a7-2485-f44b-1aa2-7c879ae0e24e","kommentar":"c4d45625-21f3-7007-f68a-41334da97b70"},"kommentarer":[{"id":"f8c34b81-5281-6347-f61d-6f77c185c23f","tekst":"Manglende etterlevelse? Er riktig analyse rekvirert? Referanseområdet for trimipramin er basert på prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"c4d45625-21f3-7007-f68a-41334da97b70","tekst":"Referanseområdet for trimipramin er basert på prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"8a678087-f2b0-2421-959d-9bf0f516cea2","tekst":"Potensielt toksisk konsentrasjon. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no). Referanseområdet for trimipramin er basert på prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon."},{"id":"1dc859a7-2485-f44b-1aa2-7c879ae0e24e","tekst":"Prøven inneholder en lav konsentrasjon av trimipramin som ligger under påvisningsgrensen."}]}},
{"kilde":"Importert fra AHT.docx, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"VALS","enhet":"nmol/L","desimaler":0,"skillepunkter":[300,16000],"intervaller":[{"niva":"under","handling":null,"kommentar":"eb98b88b-de1e-f469-72b4-c6f32350b0ea"},{"niva":"innenfor","handling":null,"kommentar":"7aaf1367-d9f9-a0e1-8131-d5e1f90be9fc"},{"niva":"over","handling":null,"kommentar":"0e2c820a-922c-44f8-34a1-476e1a86a886"}],"ringegrense":null,"cutoff":null,"kommentarer":[{"id":"eb98b88b-de1e-f469-72b4-c6f32350b0ea","tekst":"Mangelfull medikamentetterlevelse? Farmakokinetiske avvik? Referanseområdet for valsartan er basert på bruk av 80–320 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"7aaf1367-d9f9-a0e1-8131-d5e1f90be9fc","tekst":"Referanseområdet for valsartan er basert på bruk av 80–320 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"0e2c820a-922c-44f8-34a1-476e1a86a886","tekst":"Potensielt toksisk konsentrasjon. Referanseområdet for valsartan er basert på bruk av 80–320 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."}]}},
{"kilde":"Importert fra kommentarer.pdf, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"VENSUM","enhet":"nmol/L","desimaler":0,"skillepunkter":[20,4000],"intervaller":[{"niva":"under","handling":null,"kommentar":"d36b0c45-c1a2-89f6-35e6-01ea2603b807"},{"niva":"innenfor","handling":null,"kommentar":"9f244a70-8bb4-f8f1-ed7a-0abf71ec3948"},{"niva":"over","handling":"ring_rekvirent","kommentar":"5b1e5738-a64a-425e-2003-6a93c0613caf"}],"ringegrense":4000,"cutoff":{"innledning":"e84991cf-54f1-5bc3-9147-acc1cec4523b","kommentar":"9f244a70-8bb4-f8f1-ed7a-0abf71ec3948"},"kommentarer":[{"id":"d36b0c45-c1a2-89f6-35e6-01ea2603b807","tekst":"Manglende etterlevelse? Er riktig analyse rekvirert? Referanseområdet er basert på summen av venlafaksin og O-desmetylvenlafaksin ved bruk av 75–375 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"9f244a70-8bb4-f8f1-ed7a-0abf71ec3948","tekst":"Referanseområdet er basert på summen av venlafaksin og O-desmetylvenlafaksin ved bruk av 75–375 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"5b1e5738-a64a-425e-2003-6a93c0613caf","tekst":"Potensielt toksisk konsentrasjon. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no). Referanseområdet er basert på summen av venlafaksin og O-desmetylvenlafaksin ved bruk av 75–375 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon."},{"id":"e84991cf-54f1-5bc3-9147-acc1cec4523b","tekst":"Prøven inneholder en lav konsentrasjon av venlafaksin og/eller O-desmetylvenlafaksin som ligger under påvisningsgrensen."}]}},
{"kilde":"Importert fra AHT.docx, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"VER","enhet":"nmol/L","desimaler":0,"skillepunkter":[40,1600],"intervaller":[{"niva":"under","handling":null,"kommentar":"66c00c5e-1bf6-69b4-7c91-b92ba25d038a"},{"niva":"innenfor","handling":null,"kommentar":"32f70ffe-6358-0ace-7e42-3bab5ceeca5b"},{"niva":"over","handling":null,"kommentar":"6a6f2239-d5ca-0ff8-557b-b644bf4796de"}],"ringegrense":null,"cutoff":null,"kommentarer":[{"id":"66c00c5e-1bf6-69b4-7c91-b92ba25d038a","tekst":"Mangelfull medikamentetterlevelse? Farmakokinetiske avvik? Referanseområdet for verapamil er basert på bruk av 120–480 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"32f70ffe-6358-0ace-7e42-3bab5ceeca5b","tekst":"Referanseområdet for verapamil er basert på bruk av 120–480 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"6a6f2239-d5ca-0ff8-557b-b644bf4796de","tekst":"Potensielt toksisk konsentrasjon. Referanseområdet for verapamil er basert på bruk av 120–480 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."}]}},
{"kilde":"Importert fra kommentarer.pdf, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"VOR","enhet":"nmol/L","desimaler":0,"skillepunkter":[5,200],"intervaller":[{"niva":"under","handling":null,"kommentar":"e1fa7427-6eba-5c5e-dc60-aba743e15036"},{"niva":"innenfor","handling":null,"kommentar":"bdec1241-16e0-4e48-1cb9-ad4b664c6226"},{"niva":"over","handling":"ring_rekvirent","kommentar":"8be04765-2157-8ec6-2aae-874f1ef345c7"}],"ringegrense":200,"cutoff":{"innledning":"01520af9-bed9-72b2-cf44-6b389f08c726","kommentar":"bdec1241-16e0-4e48-1cb9-ad4b664c6226"},"kommentarer":[{"id":"e1fa7427-6eba-5c5e-dc60-aba743e15036","tekst":"Manglende etterlevelse? Er riktig analyse rekvirert? Referanseområdet for vortioksetin er basert på prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"bdec1241-16e0-4e48-1cb9-ad4b664c6226","tekst":"Referanseområdet for vortioksetin er basert på prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"8be04765-2157-8ec6-2aae-874f1ef345c7","tekst":"Potensielt toksisk konsentrasjon. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no). Referanseområdet for vortioksetin er basert på prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon."},{"id":"01520af9-bed9-72b2-cf44-6b389f08c726","tekst":"Prøven inneholder en lav konsentrasjon av vortioksetin som ligger under påvisningsgrensen."}]}},
{"kilde":"Importert fra kommentarer.pdf, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"ZIPRA","enhet":"nmol/L","desimaler":0,"skillepunkter":[10,600],"intervaller":[{"niva":"under","handling":null,"kommentar":"bb1ff6a3-9f42-f7b7-b8c1-965bf01adfe0"},{"niva":"innenfor","handling":null,"kommentar":"6fa12a83-a507-2c83-d136-3c2b478fcece"},{"niva":"over","handling":"ring_rekvirent","kommentar":"7c99300d-9c18-797f-5586-e3a521256c1f"}],"ringegrense":600,"cutoff":{"innledning":"833017b4-7a01-0090-8ce3-737b2327de9b","kommentar":"6fa12a83-a507-2c83-d136-3c2b478fcece"},"kommentarer":[{"id":"bb1ff6a3-9f42-f7b7-b8c1-965bf01adfe0","tekst":"Manglende etterlevelse? Er riktig analyse rekvirert? Referanseområdet for ziprasidon er basert på bruk av 40–240 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"6fa12a83-a507-2c83-d136-3c2b478fcece","tekst":"Referanseområdet for ziprasidon er basert på bruk av 40–240 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"7c99300d-9c18-797f-5586-e3a521256c1f","tekst":"Potensielt toksisk konsentrasjon. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no). Referanseområdet for ziprasidon er basert på bruk av 40–240 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon."},{"id":"833017b4-7a01-0090-8ce3-737b2327de9b","tekst":"Prøven inneholder en lav konsentrasjon av ziprasidon som ligger under påvisningsgrensen."}]}},
{"kilde":"Importert fra kommentarer.pdf, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"ZUKLO","enhet":"nmol/L","desimaler":0,"skillepunkter":[1,79,101],"intervaller":[{"niva":"under","handling":null,"kommentar":"d71edddc-99b0-48db-3b5c-bd42b863d01a"},{"niva":"innenfor","handling":null,"kommentar":"ae039eac-fcc4-2c2f-5513-f651d7368200"},{"niva":"over","handling":null,"kommentar":"af29e93b-c41d-945b-de50-23843ccdc200"},{"niva":"over","handling":"ring_rekvirent","kommentar":"af29e93b-c41d-945b-de50-23843ccdc200"}],"ringegrense":100,"cutoff":{"innledning":"f2b92499-574d-34f1-a5fd-4040dda3167b","kommentar":"ae039eac-fcc4-2c2f-5513-f651d7368200"},"kommentarer":[{"id":"d71edddc-99b0-48db-3b5c-bd42b863d01a","tekst":"Manglende etterlevelse? Er riktig analyse rekvirert? Referanseområdet for zuklopentiksol er basert på bruk av 2–30 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Ved depot anbefales prøvetaking 0–2 dager før neste injeksjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"ae039eac-fcc4-2c2f-5513-f651d7368200","tekst":"Referanseområdet for zuklopentiksol er basert på bruk av 2–30 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Ved depot anbefales prøvetaking 0–2 dager før neste injeksjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"af29e93b-c41d-945b-de50-23843ccdc200","tekst":"Potensielt toksisk konsentrasjon. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no). Referanseområdet for zuklopentiksol er basert på bruk av 2–30 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Ved depot anbefales prøvetaking 0–2 dager før neste injeksjon."},{"id":"f2b92499-574d-34f1-a5fd-4040dda3167b","tekst":"Prøven inneholder en lav konsentrasjon av zuklopentiksol som ligger under påvisningsgrensen."}]}}
]$data$;
  administrator uuid;
  import jsonb;
  status public.objektstatus;
begin
  if md5(importdata) <> 'f1f2797ae29176edeac7a091c75919d6' then
    raise exception 'Importdataene er ikke de som ble laget: kontrollsummen stemmer ikke.';
  end if;
  select p.id into administrator from public.profiles p where p.username = 'peohol' and p.role = 'admin';
  if administrator is null then
    raise notice 'Fant ingen administrator med brukernavnet %.', 'peohol';
    return;
  end if;
  perform set_config('request.jwt.claims', jsonb_build_object('sub', administrator, 'role', 'authenticated')::text, true);

  for import in
    select e.v from jsonb_array_elements(importdata::jsonb) with ordinality e(v, nr) order by e.nr
  loop
    if exists (
      select 1 from public.intervallregelsett s
      where s.tilstand = 'utkast' and s.analyttkode = import #>> '{regelsett,analyttkode}'
    ) then
      raise notice '% har alt et regelsett og hoppes over.', import #>> '{regelsett,analyttkode}';
      continue;
    end if;
    perform set_config('far.revisjonskilde', import ->> 'kilde', true);
    status := public.opprett_utkast('intervallregelsett', import -> 'regelsett');
    perform public.publiser_utkast(status.id, status.revisjon);
  end loop;

  perform set_config('far.revisjonskilde', '', true);
end
$import$;