-- Oppdateringer av kort etter Reimers A, Berg JA, Burns ML, Johannessen Landmark C. Felles referanseområder for antiepileptika. Tidsskr Nor Legeforen 2017; 137: 864–5
do $oppdatering$
declare
  administrator uuid;
  referanse uuid;
  kildenokler jsonb := '{}';
  oppdatering jsonb;
  e record;
  kilder jsonb;
  ny jsonb;
begin
  select p.id into administrator from public.profiles p where p.username = 'peohol' and p.role = 'admin';
  if administrator is null then
    raise notice 'Fant ingen administrator med brukernavnet %, så importen hoppes over.', 'peohol';
    return;
  end if;
  perform set_config('request.jwt.claims', jsonb_build_object('sub', administrator, 'role', 'authenticated')::text, true);

  -- Referansene: de som skal legges til og mangler, legges inn og publiseres.
  -- reimers2017
  referanse := (select r.objekt_id from public.referanser r
     where r.tilstand = 'publisert' and not r.arkivert
       and r.tittel = 'Felles referanseområder for antiepileptika' and r.lenke = 'https://doi.org/10.4045/tidsskr.17.0392'
     order by r.objekt_id limit 1);
  if referanse is null then
    perform set_config('far.revisjonskilde', 'Lagt inn etter Reimers A, Berg JA, Burns ML, Johannessen Landmark C. Felles referanseområder for antiepileptika. Tidsskr Nor Legeforen 2017; 137: 864–5', true);
    referanse := (public.opprett_utkast('referanse', '{"tittel":"Felles referanseområder for antiepileptika","forfattere":"Reimers A, Berg JA, Burns ML, Johannessen Landmark C","aar":"2017","lenke":"https://doi.org/10.4045/tidsskr.17.0392"}'::jsonb)).id;
    perform public.publiser_utkast(referanse, 1);
  end if;
  kildenokler := kildenokler || jsonb_strip_nulls(jsonb_build_object('reimers2017', referanse::text));

  -- referanseomradeprosjektet
  referanse := (select r.objekt_id from public.referanser r
     where r.tilstand = 'publisert' and not r.arkivert
       and r.tittel = 'Referanseområdeprosjektet 2005–2008: nasjonale kartleggings- og harmoniseringsprosjekter innen klinisk farmakologi – antidepressiva og antipsykotika' and r.lenke = 'https://farmakologiportalen.no/nasjonale_referanseomrader/'
     order by r.objekt_id limit 1);
  kildenokler := kildenokler || jsonb_strip_nulls(jsonb_build_object('referanseomradeprosjektet', referanse::text));

  for oppdatering in select * from jsonb_array_elements('[{"kode":null,"side":"Fenobarbital","panel":"viktige_data","elementtype":"referanseomrade","tittel":null,"fra":{"nedre":50,"ovre":130,"enhet":"µmol/L"},"til":{"nedre":50,"ovre":130},"inn":["reimers2017"],"ut":[],"kilde":"Oppdatert etter Reimers A, Berg JA, Burns ML, Johannessen Landmark C. Felles referanseområder for antiepileptika. Tidsskr Nor Legeforen 2017; 137: 864–5: det nasjonale referanseom'
    'rådet fra 2017 er det samme, 50–130 µmol/L"},{"kode":null,"side":"Fenobarbital","panel":"tdm","elementtype":"kinetikkort","tittel":"Grunnlag for referanseområdet","fra":{"dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Referanseområdene for antiepileptika ble ikke beregnet på nytt i prosjektet. Diakonhjemmet sykehus tok i 2008 i bruk områdene St. Olavs hosp'
    'ital har utarbeidet sammen med nevrologisk avdeling der."}]},{"type":"paragraph","content":[{"type":"text","text":"Diakonhjemmet sykehus, St. Olavs hospital og Statens senter for epilepsi brukte alle 50–130 µmol/L, og området ble ikke endret."}]}]}},"til":{"dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Referanseområdet er det felles nasjonale referanseomr'
    'ådet for antiepileptika fra 2017, som styret i Norsk forening for klinisk farmakologi har godkjent. Det gjelder prøver tatt medikamentfastende, det vil si like før neste ordinære dose og 12–24 timer etter forrige inntak."}]},{"type":"paragraph","content":[{"type":"text","text":"Området 50–130 µmol/L ble videreført uendret i 2017."}]},{"type":"paragraph","content":[{"type":"text","text":"Før 2017 b'
    'ygde området på referanseområdeprosjektet (2008):"}]},{"type":"paragraph","content":[{"type":"text","text":"Referanseområdene for antiepileptika ble ikke beregnet på nytt i prosjektet. Diakonhjemmet sykehus tok i 2008 i bruk områdene St. Olavs hospital har utarbeidet sammen med nevrologisk avdeling der."}]},{"type":"paragraph","content":[{"type":"text","text":"Diakonhjemmet sykehus, St. Olavs hosp'
    'ital og Statens senter for epilepsi brukte alle 50–130 µmol/L, og området ble ikke endret."}]}]}},"inn":["reimers2017"],"ut":[],"kilde":"Oppdatert etter Reimers A, Berg JA, Burns ML, Johannessen Landmark C. Felles referanseområder for antiepileptika. Tidsskr Nor Legeforen 2017; 137: 864–5: grunnlaget er de felles nasjonale referanseområdene for antiepileptika fra 2017"},{"kode":null,"side":"Fenoba'
    'rbital","panel":"tdm","elementtype":"kinetikkort","tittel":"Nyere nasjonale referanseområder","fra":{"dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Felles nasjonale referanseområder for antiepileptika ble etablert i 2017 (Reimers A, Berg JA, Burns ML mfl. Felles referanseområder for antiepileptika. Tidsskr Nor Legeforen 2017; 137: 864–5). De er ikke blant'
    ' kildene for denne siden, og referanseområdet her er fra 2008."}]}]}},"til":null,"inn":[],"ut":[],"kilde":"Oppdatert etter Reimers A, Berg JA, Burns ML, Johannessen Landmark C. Felles referanseområder for antiepileptika. Tidsskr Nor Legeforen 2017; 137: 864–5: de nasjonale referanseområdene fra 2017 står nå i grunnlaget for referanseområdet"},{"kode":null,"side":"Fenytoin","panel":"viktige_data","'
    'elementtype":"referanseomrade","tittel":null,"fra":{"nedre":40,"ovre":80,"enhet":"µmol/L"},"til":{"nedre":40,"ovre":80},"inn":["reimers2017"],"ut":[],"kilde":"Oppdatert etter Reimers A, Berg JA, Burns ML, Johannessen Landmark C. Felles referanseområder for antiepileptika. Tidsskr Nor Legeforen 2017; 137: 864–5: det nasjonale referanseområdet fra 2017 er det samme, 40–80 µmol/L"},{"kode":null,"side'
    '":"Fenytoin","panel":"tdm","elementtype":"kinetikkort","tittel":"Grunnlag for referanseområdet","fra":{"dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Referanseområdene for antiepileptika ble ikke beregnet på nytt i prosjektet. Diakonhjemmet sykehus tok i 2008 i bruk områdene St. Olavs hospital har utarbeidet sammen med nevrologisk avdeling der."}]},{"type'
    '":"paragraph","content":[{"type":"text","text":"Diakonhjemmet sykehus, St. Olavs hospital og Statens senter for epilepsi brukte alle 40–80 µmol/L, og området ble ikke endret."}]}]}},"til":{"dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Referanseområdet er det felles nasjonale referanseområdet for antiepileptika fra 2017, som styret i Norsk forening for kl'
    'inisk farmakologi har godkjent. Det gjelder prøver tatt medikamentfastende, det vil si like før neste ordinære dose og 12–24 timer etter forrige inntak."}]},{"type":"paragraph","content":[{"type":"text","text":"Området 40–80 µmol/L ble videreført uendret i 2017. Det gjelder totalkonsentrasjonen; for fritt fenytoin oppgir de nasjonale områdene ca. 10 %."}]},{"type":"paragraph","content":[{"type":"t'
    'ext","text":"Før 2017 bygde området på referanseområdeprosjektet (2008):"}]},{"type":"paragraph","content":[{"type":"text","text":"Referanseområdene for antiepileptika ble ikke beregnet på nytt i prosjektet. Diakonhjemmet sykehus tok i 2008 i bruk områdene St. Olavs hospital har utarbeidet sammen med nevrologisk avdeling der."}]},{"type":"paragraph","content":[{"type":"text","text":"Diakonhjemmet '
    'sykehus, St. Olavs hospital og Statens senter for epilepsi brukte alle 40–80 µmol/L, og området ble ikke endret."}]}]}},"inn":["reimers2017"],"ut":[],"kilde":"Oppdatert etter Reimers A, Berg JA, Burns ML, Johannessen Landmark C. Felles referanseområder for antiepileptika. Tidsskr Nor Legeforen 2017; 137: 864–5: grunnlaget er de felles nasjonale referanseområdene for antiepileptika fra 2017"},{"kod'
    'e":null,"side":"Fenytoin","panel":"tdm","elementtype":"kinetikkort","tittel":"Nyere nasjonale referanseområder","fra":{"dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Felles nasjonale referanseområder for antiepileptika ble etablert i 2017 (Reimers A, Berg JA, Burns ML mfl. Felles referanseområder for antiepileptika. Tidsskr Nor Legeforen 2017; 137: 864–5)'
    '. De er ikke blant kildene for denne siden, og referanseområdet her er fra 2008."}]}]}},"til":null,"inn":[],"ut":[],"kilde":"Oppdatert etter Reimers A, Berg JA, Burns ML, Johannessen Landmark C. Felles referanseområder for antiepileptika. Tidsskr Nor Legeforen 2017; 137: 864–5: de nasjonale referanseområdene fra 2017 står nå i grunnlaget for referanseområdet"},{"kode":null,"side":"Gabapentin","pan'
    'el":"viktige_data","elementtype":"referanseomrade","tittel":null,"fra":{"nedre":20,"ovre":120,"enhet":"µmol/L"},"til":{"nedre":20,"ovre":120},"inn":["reimers2017"],"ut":[],"kilde":"Oppdatert etter Reimers A, Berg JA, Burns ML, Johannessen Landmark C. Felles referanseområder for antiepileptika. Tidsskr Nor Legeforen 2017; 137: 864–5: det nasjonale referanseområdet fra 2017 er det samme, 20–120 µmol'
    '/L"},{"kode":null,"side":"Gabapentin","panel":"tdm","elementtype":"kinetikkort","tittel":"Grunnlag for referanseområdet","fra":{"dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Referanseområdene for antiepileptika ble ikke beregnet på nytt i prosjektet. Diakonhjemmet sykehus tok i 2008 i bruk områdene St. Olavs hospital har utarbeidet sammen med nevrologisk'
    ' avdeling der."}]},{"type":"paragraph","content":[{"type":"text","text":"Området har fått en øvre grense. Diakonhjemmet sykehus brukte tidligere > 12 µmol/L, og Statens senter for epilepsi 70–120 µmol/L."}]}]}},"til":{"dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Referanseområdet er det felles nasjonale referanseområdet for antiepileptika fra 2017, som s'
    'tyret i Norsk forening for klinisk farmakologi har godkjent. Det gjelder prøver tatt medikamentfastende, det vil si like før neste ordinære dose og 12–24 timer etter forrige inntak."}]},{"type":"paragraph","content":[{"type":"text","text":"Området 20–120 µmol/L ble videreført uendret i 2017."}]},{"type":"paragraph","content":[{"type":"text","text":"Før 2017 bygde området på referanseområdeprosjekt'
    'et (2008):"}]},{"type":"paragraph","content":[{"type":"text","text":"Referanseområdene for antiepileptika ble ikke beregnet på nytt i prosjektet. Diakonhjemmet sykehus tok i 2008 i bruk områdene St. Olavs hospital har utarbeidet sammen med nevrologisk avdeling der."}]},{"type":"paragraph","content":[{"type":"text","text":"Området har fått en øvre grense. Diakonhjemmet sykehus brukte tidligere > 12'
    ' µmol/L, og Statens senter for epilepsi 70–120 µmol/L."}]}]}},"inn":["reimers2017"],"ut":[],"kilde":"Oppdatert etter Reimers A, Berg JA, Burns ML, Johannessen Landmark C. Felles referanseområder for antiepileptika. Tidsskr Nor Legeforen 2017; 137: 864–5: grunnlaget er de felles nasjonale referanseområdene for antiepileptika fra 2017"},{"kode":null,"side":"Gabapentin","panel":"tdm","elementtype":"k'
    'inetikkort","tittel":"Nyere nasjonale referanseområder","fra":{"dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Felles nasjonale referanseområder for antiepileptika ble etablert i 2017 (Reimers A, Berg JA, Burns ML mfl. Felles referanseområder for antiepileptika. Tidsskr Nor Legeforen 2017; 137: 864–5). De er ikke blant kildene for denne siden, og referanse'
    'området her er fra 2008."}]}]}},"til":null,"inn":[],"ut":[],"kilde":"Oppdatert etter Reimers A, Berg JA, Burns ML, Johannessen Landmark C. Felles referanseområder for antiepileptika. Tidsskr Nor Legeforen 2017; 137: 864–5: de nasjonale referanseområdene fra 2017 står nå i grunnlaget for referanseområdet"},{"kode":null,"side":"Karbamazepin","panel":"viktige_data","elementtype":"referanseomrade","ti'
    'ttel":null,"fra":{"nedre":15,"ovre":45,"enhet":"µmol/L"},"til":{"nedre":15,"ovre":45},"inn":["reimers2017"],"ut":[],"kilde":"Oppdatert etter Reimers A, Berg JA, Burns ML, Johannessen Landmark C. Felles referanseområder for antiepileptika. Tidsskr Nor Legeforen 2017; 137: 864–5: det nasjonale referanseområdet fra 2017 er det samme, 15–45 µmol/L"},{"kode":null,"side":"Karbamazepin","panel":"tdm","el'
    'ementtype":"kinetikkort","tittel":"Grunnlag for referanseområdet","fra":{"dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Referanseområdet gjelder summen av karbamazepin og den aktive metabolitten karbamazepinepoksid."}]},{"type":"paragraph","content":[{"type":"text","text":"Referanseområdene for antiepileptika ble ikke beregnet på nytt i prosjektet. Diakon'
    'hjemmet sykehus tok i 2008 i bruk områdene St. Olavs hospital har utarbeidet sammen med nevrologisk avdeling der."}]},{"type":"paragraph","content":[{"type":"text","text":"Området ble ikke endret, men gjelder nå for summen. Diakonhjemmet sykehus brukte det tidligere for karbamazepin alene. St. Olavs hospital og Statens senter for epilepsi brukte også 15–45 µmol/L."}]}]}},"til":{"dokument":{"type":'
    '"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Referanseområdet er det felles nasjonale referanseområdet for antiepileptika fra 2017, som styret i Norsk forening for klinisk farmakologi har godkjent. Det gjelder prøver tatt medikamentfastende, det vil si like før neste ordinære dose og 12–24 timer etter forrige inntak."}]},{"type":"paragraph","content":[{"type":"text","text'
    '":"Området 15–45 µmol/L ble videreført uendret i 2017. For fritt karbamazepin oppgir de nasjonale områdene 24–33 % (= 4–12,5 µmol/L)."}]},{"type":"paragraph","content":[{"type":"text","text":"Tabellen fra 2017 sier ikke om området gjelder karbamazepin alene eller summen med den aktive metabolitten karbamazepinepoksid. I referanseområdeprosjektet (2008) gjaldt det summen."}]},{"type":"paragraph","c'
    'ontent":[{"type":"text","text":"Før 2017 bygde området på referanseområdeprosjektet (2008):"}]},{"type":"paragraph","content":[{"type":"text","text":"Referanseområdene for antiepileptika ble ikke beregnet på nytt i prosjektet. Diakonhjemmet sykehus tok i 2008 i bruk områdene St. Olavs hospital har utarbeidet sammen med nevrologisk avdeling der."}]},{"type":"paragraph","content":[{"type":"text","te'
    'xt":"Området ble ikke endret, men gjelder nå for summen. Diakonhjemmet sykehus brukte det tidligere for karbamazepin alene. St. Olavs hospital og Statens senter for epilepsi brukte også 15–45 µmol/L."}]}]}},"inn":["reimers2017"],"ut":[],"kilde":"Oppdatert etter Reimers A, Berg JA, Burns ML, Johannessen Landmark C. Felles referanseområder for antiepileptika. Tidsskr Nor Legeforen 2017; 137: 864–5: '
    'grunnlaget er de felles nasjonale referanseområdene for antiepileptika fra 2017"},{"kode":null,"side":"Karbamazepin","panel":"tdm","elementtype":"kinetikkort","tittel":"Nyere nasjonale referanseområder","fra":{"dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Felles nasjonale referanseområder for antiepileptika ble etablert i 2017 (Reimers A, Berg JA, Burns '
    'ML mfl. Felles referanseområder for antiepileptika. Tidsskr Nor Legeforen 2017; 137: 864–5). De er ikke blant kildene for denne siden, og referanseområdet her er fra 2008."}]}]}},"til":null,"inn":[],"ut":[],"kilde":"Oppdatert etter Reimers A, Berg JA, Burns ML, Johannessen Landmark C. Felles referanseområder for antiepileptika. Tidsskr Nor Legeforen 2017; 137: 864–5: de nasjonale referanseområdene'
    ' fra 2017 står nå i grunnlaget for referanseområdet"},{"kode":null,"side":"Levetiracetam","panel":"viktige_data","elementtype":"referanseomrade","tittel":null,"fra":{"nedre":30,"ovre":240,"enhet":"µmol/L"},"til":{"nedre":30,"ovre":240},"inn":["reimers2017"],"ut":[],"kilde":"Oppdatert etter Reimers A, Berg JA, Burns ML, Johannessen Landmark C. Felles referanseområder for antiepileptika. Tidsskr Nor'
    ' Legeforen 2017; 137: 864–5: det nasjonale referanseområdet fra 2017 er det samme, 30–240 µmol/L"},{"kode":null,"side":"Levetiracetam","panel":"tdm","elementtype":"kinetikkort","tittel":"Grunnlag for referanseområdet","fra":{"dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Referanseområdene for antiepileptika ble ikke beregnet på nytt i prosjektet. Diakonhj'
    'emmet sykehus tok i 2008 i bruk områdene St. Olavs hospital har utarbeidet sammen med nevrologisk avdeling der."}]},{"type":"paragraph","content":[{"type":"text","text":"Diakonhjemmet sykehus og Statens senter for epilepsi brukte tidligere 35–120 µmol/L."}]}]}},"til":{"dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Referanseområdet er det felles nasjonale '
    'referanseområdet for antiepileptika fra 2017, som styret i Norsk forening for klinisk farmakologi har godkjent. Det gjelder prøver tatt medikamentfastende, det vil si like før neste ordinære dose og 12–24 timer etter forrige inntak."}]},{"type":"paragraph","content":[{"type":"text","text":"Området 30–240 µmol/L ble videreført uendret i 2017."}]},{"type":"paragraph","content":[{"type":"text","text"'
    ':"Før 2017 bygde området på referanseområdeprosjektet (2008):"}]},{"type":"paragraph","content":[{"type":"text","text":"Referanseområdene for antiepileptika ble ikke beregnet på nytt i prosjektet. Diakonhjemmet sykehus tok i 2008 i bruk områdene St. Olavs hospital har utarbeidet sammen med nevrologisk avdeling der."}]},{"type":"paragraph","content":[{"type":"text","text":"Diakonhjemmet sykehus og '
    'Statens senter for epilepsi brukte tidligere 35–120 µmol/L."}]}]}},"inn":["reimers2017"],"ut":[],"kilde":"Oppdatert etter Reimers A, Berg JA, Burns ML, Johannessen Landmark C. Felles referanseområder for antiepileptika. Tidsskr Nor Legeforen 2017; 137: 864–5: grunnlaget er de felles nasjonale referanseområdene for antiepileptika fra 2017"},{"kode":null,"side":"Levetiracetam","panel":"tdm","element'
    'type":"kinetikkort","tittel":"Nyere nasjonale referanseområder","fra":{"dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Felles nasjonale referanseområder for antiepileptika ble etablert i 2017 (Reimers A, Berg JA, Burns ML mfl. Felles referanseområder for antiepileptika. Tidsskr Nor Legeforen 2017; 137: 864–5). De er ikke blant kildene for denne siden, og r'
    'eferanseområdet her er fra 2008."}]}]}},"til":null,"inn":[],"ut":[],"kilde":"Oppdatert etter Reimers A, Berg JA, Burns ML, Johannessen Landmark C. Felles referanseområder for antiepileptika. Tidsskr Nor Legeforen 2017; 137: 864–5: de nasjonale referanseområdene fra 2017 står nå i grunnlaget for referanseområdet"},{"kode":null,"side":"Okskarbazepin","panel":"viktige_data","elementtype":"referanseom'
    'rade","tittel":null,"fra":{"nedre":45,"ovre":140,"enhet":"µmol/L"},"til":{"nedre":12,"ovre":140},"inn":["reimers2017"],"ut":["referanseomradeprosjektet"],"kilde":"Oppdatert etter Reimers A, Berg JA, Burns ML, Johannessen Landmark C. Felles referanseområder for antiepileptika. Tidsskr Nor Legeforen 2017; 137: 864–5: det nasjonale referanseområdet er 12–140 µmol/L, ikke 45–140 µmol/L"},{"kode":null,'
    '"side":"Okskarbazepin","panel":"tdm","elementtype":"kinetikkort","tittel":"Grunnlag for referanseområdet","fra":{"dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Referanseområdet gjelder den aktive metabolitten monohydroksyokskarbazepin (MHD)."}]},{"type":"paragraph","content":[{"type":"text","text":"Referanseområdene for antiepileptika ble ikke beregnet på'
    ' nytt i prosjektet. Diakonhjemmet sykehus tok i 2008 i bruk områdene St. Olavs hospital har utarbeidet sammen med nevrologisk avdeling der."}]},{"type":"paragraph","content":[{"type":"text","text":"Diakonhjemmet sykehus og Statens senter for epilepsi brukte tidligere 50–140 µmol/L."}]}]}},"til":{"dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Referanseområ'
    'det er det felles nasjonale referanseområdet for antiepileptika fra 2017, som styret i Norsk forening for klinisk farmakologi har godkjent. Det gjelder prøver tatt medikamentfastende, det vil si like før neste ordinære dose og 12–24 timer etter forrige inntak."}]},{"type":"paragraph","content":[{"type":"text","text":"I 2017 ble området endret fra 45–140 til 12–140 µmol/L. Det gjelder den aktive me'
    'tabolitten likarbazepin (opprinnelig kalt monohydroksyderivat, MHD)."}]},{"type":"paragraph","content":[{"type":"text","text":"Før 2017 bygde området på referanseområdeprosjektet (2008):"}]},{"type":"paragraph","content":[{"type":"text","text":"Referanseområdene for antiepileptika ble ikke beregnet på nytt i prosjektet. Diakonhjemmet sykehus tok i 2008 i bruk områdene St. Olavs hospital har utarbe'
    'idet sammen med nevrologisk avdeling der."}]},{"type":"paragraph","content":[{"type":"text","text":"Diakonhjemmet sykehus og Statens senter for epilepsi brukte tidligere 50–140 µmol/L."}]}]}},"inn":["reimers2017"],"ut":[],"kilde":"Oppdatert etter Reimers A, Berg JA, Burns ML, Johannessen Landmark C. Felles referanseområder for antiepileptika. Tidsskr Nor Legeforen 2017; 137: 864–5: grunnlaget er d'
    'e felles nasjonale referanseområdene for antiepileptika fra 2017"},{"kode":null,"side":"Okskarbazepin","panel":"tdm","elementtype":"kinetikkort","tittel":"Nyere nasjonale referanseområder","fra":{"dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Felles nasjonale referanseområder for antiepileptika ble etablert i 2017 (Reimers A, Berg JA, Burns ML mfl. Felles'
    ' referanseområder for antiepileptika. Tidsskr Nor Legeforen 2017; 137: 864–5). De er ikke blant kildene for denne siden, og referanseområdet her er fra 2008."}]}]}},"til":null,"inn":[],"ut":[],"kilde":"Oppdatert etter Reimers A, Berg JA, Burns ML, Johannessen Landmark C. Felles referanseområder for antiepileptika. Tidsskr Nor Legeforen 2017; 137: 864–5: de nasjonale referanseområdene fra 2017 står'
    ' nå i grunnlaget for referanseområdet"},{"kode":null,"side":"Topiramat","panel":"viktige_data","elementtype":"referanseomrade","tittel":null,"fra":{"nedre":15,"ovre":60,"enhet":"µmol/L"},"til":{"nedre":6,"ovre":30},"inn":["reimers2017"],"ut":["referanseomradeprosjektet"],"kilde":"Oppdatert etter Reimers A, Berg JA, Burns ML, Johannessen Landmark C. Felles referanseområder for antiepileptika. Tidss'
    'kr Nor Legeforen 2017; 137: 864–5: det nasjonale referanseområdet er 6–30 µmol/L, ikke 15–60 µmol/L"},{"kode":null,"side":"Topiramat","panel":"tdm","elementtype":"kinetikkort","tittel":"Grunnlag for referanseområdet","fra":{"dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Referanseområdene for antiepileptika ble ikke beregnet på nytt i prosjektet. Diakonhje'
    'mmet sykehus tok i 2008 i bruk områdene St. Olavs hospital har utarbeidet sammen med nevrologisk avdeling der."}]},{"type":"paragraph","content":[{"type":"text","text":"Området har fått en øvre grense. Diakonhjemmet sykehus brukte tidligere > 10 µmol/L. Statens senter for epilepsi brukte også 15–60 µmol/L."}]}]}},"til":{"dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"te'
    'xt","text":"Referanseområdet er det felles nasjonale referanseområdet for antiepileptika fra 2017, som styret i Norsk forening for klinisk farmakologi har godkjent. Det gjelder prøver tatt medikamentfastende, det vil si like før neste ordinære dose og 12–24 timer etter forrige inntak."}]},{"type":"paragraph","content":[{"type":"text","text":"I 2017 ble området endret fra 15–60 til 6–30 µmol/L."}]}'
    ',{"type":"paragraph","content":[{"type":"text","text":"Før 2017 bygde området på referanseområdeprosjektet (2008):"}]},{"type":"paragraph","content":[{"type":"text","text":"Referanseområdene for antiepileptika ble ikke beregnet på nytt i prosjektet. Diakonhjemmet sykehus tok i 2008 i bruk områdene St. Olavs hospital har utarbeidet sammen med nevrologisk avdeling der."}]},{"type":"paragraph","conte'
    'nt":[{"type":"text","text":"Området har fått en øvre grense. Diakonhjemmet sykehus brukte tidligere > 10 µmol/L. Statens senter for epilepsi brukte også 15–60 µmol/L."}]}]}},"inn":["reimers2017"],"ut":[],"kilde":"Oppdatert etter Reimers A, Berg JA, Burns ML, Johannessen Landmark C. Felles referanseområder for antiepileptika. Tidsskr Nor Legeforen 2017; 137: 864–5: grunnlaget er de felles nasjonale'
    ' referanseområdene for antiepileptika fra 2017"},{"kode":null,"side":"Topiramat","panel":"tdm","elementtype":"kinetikkort","tittel":"Nyere nasjonale referanseområder","fra":{"dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Felles nasjonale referanseområder for antiepileptika ble etablert i 2017 (Reimers A, Berg JA, Burns ML mfl. Felles referanseområder for '
    'antiepileptika. Tidsskr Nor Legeforen 2017; 137: 864–5). De er ikke blant kildene for denne siden, og referanseområdet her er fra 2008."}]}]}},"til":null,"inn":[],"ut":[],"kilde":"Oppdatert etter Reimers A, Berg JA, Burns ML, Johannessen Landmark C. Felles referanseområder for antiepileptika. Tidsskr Nor Legeforen 2017; 137: 864–5: de nasjonale referanseområdene fra 2017 står nå i grunnlaget for r'
    'eferanseområdet"},{"kode":null,"side":"Valproat","panel":"viktige_data","elementtype":"referanseomrade","tittel":null,"fra":{"nedre":300,"ovre":700,"enhet":"µmol/L"},"til":{"nedre":300,"ovre":700},"inn":["reimers2017"],"ut":[],"kilde":"Oppdatert etter Reimers A, Berg JA, Burns ML, Johannessen Landmark C. Felles referanseområder for antiepileptika. Tidsskr Nor Legeforen 2017; 137: 864–5: det nasjon'
    'ale referanseområdet fra 2017 er det samme, 300–700 µmol/L"},{"kode":null,"side":"Valproat","panel":"tdm","elementtype":"kinetikkort","tittel":"Grunnlag for referanseområdet","fra":{"dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Referanseområdene for antiepileptika ble ikke beregnet på nytt i prosjektet. Diakonhjemmet sykehus tok i 2008 i bruk områdene St'
    '. Olavs hospital har utarbeidet sammen med nevrologisk avdeling der."}]},{"type":"paragraph","content":[{"type":"text","text":"Diakonhjemmet sykehus brukte tidligere 300–900 µmol/L, som var veiledende ved psykiatrisk indikasjon; ved epilepsi ble 600 µmol/L anbefalt som øvre grense. Statens senter for epilepsi brukte 300–600 µmol/L."}]}]}},"til":{"dokument":{"type":"doc","content":[{"type":"paragra'
    'ph","content":[{"type":"text","text":"Referanseområdet er det felles nasjonale referanseområdet for antiepileptika fra 2017, som styret i Norsk forening for klinisk farmakologi har godkjent. Det gjelder prøver tatt medikamentfastende, det vil si like før neste ordinære dose og 12–24 timer etter forrige inntak."}]},{"type":"paragraph","content":[{"type":"text","text":"I 2017 ble området harmonisert'
    ' til 300–700 µmol/L; laboratoriene brukte før det ulike grenser (250/300–600/700 µmol/L). Det gjelder totalkonsentrasjonen; for fritt valproat oppgir de nasjonale områdene ca. 10 %."}]},{"type":"paragraph","content":[{"type":"text","text":"Før 2017 bygde området på referanseområdeprosjektet (2008):"}]},{"type":"paragraph","content":[{"type":"text","text":"Referanseområdene for antiepileptika ble i'
    'kke beregnet på nytt i prosjektet. Diakonhjemmet sykehus tok i 2008 i bruk områdene St. Olavs hospital har utarbeidet sammen med nevrologisk avdeling der."}]},{"type":"paragraph","content":[{"type":"text","text":"Diakonhjemmet sykehus brukte tidligere 300–900 µmol/L, som var veiledende ved psykiatrisk indikasjon; ved epilepsi ble 600 µmol/L anbefalt som øvre grense. Statens senter for epilepsi bru'
    'kte 300–600 µmol/L."}]}]}},"inn":["reimers2017"],"ut":[],"kilde":"Oppdatert etter Reimers A, Berg JA, Burns ML, Johannessen Landmark C. Felles referanseområder for antiepileptika. Tidsskr Nor Legeforen 2017; 137: 864–5: grunnlaget er de felles nasjonale referanseområdene for antiepileptika fra 2017"},{"kode":null,"side":"Valproat","panel":"tdm","elementtype":"kinetikkort","tittel":"Nyere nasjonale'
    ' referanseområder","fra":{"dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Felles nasjonale referanseområder for antiepileptika ble etablert i 2017 (Reimers A, Berg JA, Burns ML mfl. Felles referanseområder for antiepileptika. Tidsskr Nor Legeforen 2017; 137: 864–5). De er ikke blant kildene for denne siden, og referanseområdet her er fra 2008."}]}]}},"til"'
    ':null,"inn":[],"ut":[],"kilde":"Oppdatert etter Reimers A, Berg JA, Burns ML, Johannessen Landmark C. Felles referanseområder for antiepileptika. Tidsskr Nor Legeforen 2017; 137: 864–5: de nasjonale referanseområdene fra 2017 står nå i grunnlaget for referanseområdet"},{"kode":"LAM","side":null,"panel":"viktige_data","elementtype":"referanseomrade","tittel":null,"fra":{"nedre":10,"ovre":50,"enhet"'
    ':"µmol/L"},"til":{"nedre":10,"ovre":50},"inn":["reimers2017"],"ut":[],"kilde":"Oppdatert etter Reimers A, Berg JA, Burns ML, Johannessen Landmark C. Felles referanseområder for antiepileptika. Tidsskr Nor Legeforen 2017; 137: 864–5: det nasjonale referanseområdet fra 2017 er det samme, 10–50 µmol/L"},{"kode":"LAM","side":null,"panel":"tdm","elementtype":"kinetikkort","tittel":"Grunnlag for referan'
    'seområdet","fra":{"dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Referanseområdene for antiepileptika ble ikke beregnet på nytt i prosjektet. Diakonhjemmet sykehus tok i 2008 i bruk området St. Olavs hospital har utarbeidet sammen med nevrologisk avdeling der. Statens senter for epilepsi brukte da 10–60 µmol/L."}]}]}},"til":{"dokument":{"type":"doc","cont'
    'ent":[{"type":"paragraph","content":[{"type":"text","text":"Referanseområdet er det felles nasjonale referanseområdet for antiepileptika fra 2017, som styret i Norsk forening for klinisk farmakologi har godkjent. Det gjelder prøver tatt medikamentfastende, det vil si like før neste ordinære dose og 12–24 timer etter forrige inntak."}]},{"type":"paragraph","content":[{"type":"text","text":"I 2017 b'
    'le området harmonisert til 10–50 µmol/L. Laboratoriene brukte før det 10–50 eller 10–60 µmol/L."}]},{"type":"paragraph","content":[{"type":"text","text":"Før 2017 bygde området på referanseområdeprosjektet (2008):"}]},{"type":"paragraph","content":[{"type":"text","text":"Referanseområdene for antiepileptika ble ikke beregnet på nytt i prosjektet. Diakonhjemmet sykehus tok i 2008 i bruk området St.'
    ' Olavs hospital har utarbeidet sammen med nevrologisk avdeling der. Statens senter for epilepsi brukte da 10–60 µmol/L."}]}]}},"inn":["reimers2017"],"ut":[],"kilde":"Oppdatert etter Reimers A, Berg JA, Burns ML, Johannessen Landmark C. Felles referanseområder for antiepileptika. Tidsskr Nor Legeforen 2017; 137: 864–5: grunnlaget er de felles nasjonale referanseområdene for antiepileptika fra 2017"'
    '},{"kode":"CZP","side":null,"panel":"tdm","elementtype":"kinetikkort","tittel":"Referansegrense","fra":{"dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Øvre referansegrense 50 nmol/L er den øvre forventede medikamentfastende konsentrasjonen ved døgndose 1,5 mg, høyeste døgndose ved angst, uro og/eller søvnvansker."}]},{"type":"paragraph","content":[{"type"'
    ':"text","text":"Ved epilepsi brukes høyere doser, og referanseområdet er da 60–220 nmol/L."}]},{"type":"paragraph","content":[{"type":"text","text":"Det er ikke satt noen nedre grense, siden konsentrasjonen bør holdes så lav som mulig. Lavest mulig dosering og kortvarig eller periodevis bruk bør tilstrebes."}]}]}},"til":{"dokument":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"t'
    'ext","text":"Øvre referansegrense 50 nmol/L er den øvre forventede medikamentfastende konsentrasjonen ved døgndose 1,5 mg, høyeste døgndose ved angst, uro og/eller søvnvansker."}]},{"type":"paragraph","content":[{"type":"text","text":"Ved epilepsi brukes høyere doser, og referanseområdet er da 40–120 nmol/L. Det er det felles nasjonale referanseområdet for antiepileptika fra 2017; før det var områ'
    'det 60–220 nmol/L."}]},{"type":"paragraph","content":[{"type":"text","text":"Det er ikke satt noen nedre grense, siden konsentrasjonen bør holdes så lav som mulig. Lavest mulig dosering og kortvarig eller periodevis bruk bør tilstrebes."}]}]}},"inn":["reimers2017"],"ut":[],"kilde":"Oppdatert etter Reimers A, Berg JA, Burns ML, Johannessen Landmark C. Felles referanseområder for antiepileptika. Tid'
    'sskr Nor Legeforen 2017; 137: 864–5: referanseområdet ved epilepsi er 40–120 nmol/L, ikke 60–220 nmol/L"}]'::jsonb) loop
    -- Kortet på siden, der feltene står nøyaktig som oppgitt, uten upublisert utkast.
    select u.objekt_id, u.revisjon, r.innhold into e
    from public.innholdselementer t
    join public.objekttilstander u on u.objekt_id = t.objekt_id and u.tilstand = 'utkast'
    join public.objekttilstander p on p.objekt_id = t.objekt_id and p.tilstand = 'publisert' and p.revisjon = u.revisjon
    join public.objektrevisjoner r on r.objekt_id = t.objekt_id and r.revisjon = u.revisjon
    where t.tilstand = 'publisert'
      and t.infoside_id = coalesce(
        (select a.hovedside_id from public.laboratorieanalytter a where a.tilstand = 'publisert' and a.kode = oppdatering->>'kode'),
        (select s.objekt_id from public.infosider s where s.tilstand = 'publisert' and lower(s.navn) = lower(oppdatering->>'side')))
      and t.panel = oppdatering->>'panel' and t.elementtype = oppdatering->>'elementtype'
      and (t.data->>'tittel') is not distinct from (oppdatering->>'tittel')
      and not exists (
        select 1 from jsonb_each(oppdatering->'fra') f where r.innhold->'data'->f.key is distinct from f.value)
    order by t.posisjon, t.objekt_id
    limit 1;
    if not found then
      raise notice 'Oppdaterer ikke % på %: fant ikke kortet slik det var, eller det har et upublisert utkast.',
        coalesce(oppdatering->>'tittel', oppdatering->>'elementtype'), coalesce(oppdatering->>'kode', oppdatering->>'side');
      continue;
    end if;

    -- De nye kildene først, så de som sto fra før og ikke tas bort.
    select coalesce(jsonb_agg(k order by rekke, i), '[]'::jsonb) into kilder
    from (
      select to_jsonb(kildenokler->>n) as k, 0 as rekke, i
        from jsonb_array_elements_text(oppdatering->'inn') with ordinality as inn(n, i)
      union all
      select x, 1, i
        from jsonb_array_elements(coalesce(e.innhold->'referanser', '[]')) with ordinality as fra(x, i)
        where not exists (select 1 from jsonb_array_elements_text(oppdatering->'inn') n where to_jsonb(kildenokler->>n) = x)
          and not exists (select 1 from jsonb_array_elements_text(oppdatering->'ut') n where to_jsonb(kildenokler->>n) = x)
    ) alle;

    ny := case when jsonb_typeof(oppdatering->'til') = 'null'
      then jsonb_set(e.innhold, '{panel}', to_jsonb('fjernet'::text))
      else e.innhold || jsonb_build_object('data', (e.innhold->'data') || (oppdatering->'til'), 'referanser', kilder)
    end;
    -- Står kortet alt slik oppdateringen gir det, lages ingen ny revisjon.
    continue when ny = e.innhold;

    perform set_config('far.revisjonskilde', oppdatering->>'kilde', true);
    perform public.lagre_utkast(e.objekt_id, e.revisjon, ny);
    perform public.publiser_utkast(e.objekt_id, e.revisjon + 1);
  end loop;
end
$oppdatering$;