-- Regelsettene for de enkle konsentrasjonsreglene
do $import$
declare
  importdata constant text := $data$[
{"kilde":"Importert fra AHT.docx, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"METOP","enhet":"nmol/L","desimaler":0,"skillepunkter":[10,2000],"intervaller":[{"niva":"under","handling":null,"kommentar":"653aca60-37ef-b7ac-3c50-e358252bf021"},{"niva":"innenfor","handling":null,"kommentar":"d16dfc18-5e1e-67c3-ee11-5513fee4f0bc"},{"niva":"over","handling":null,"kommentar":"06a9c13c-7bfd-4279-463a-5a9e22e6c6d5"}],"ringegrense":null,"cutoff":null,"kommentarer":[{"id":"653aca60-37ef-b7ac-3c50-e358252bf021","tekst":"Mangelfull medikamentetterlevelse? Farmakokinetiske avvik? Referanseområdet for metoprolol er basert på bruk av 50–200 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"d16dfc18-5e1e-67c3-ee11-5513fee4f0bc","tekst":"Referanseområdet for metoprolol er basert på bruk av 50–200 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"06a9c13c-7bfd-4279-463a-5a9e22e6c6d5","tekst":"Potensielt toksisk konsentrasjon. Referanseområdet for metoprolol er basert på bruk av 50–200 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."}]}},
{"kilde":"Importert fra kommentarer.pdf, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"MIASUM","enhet":"nmol/L","desimaler":0,"skillepunkter":[10,1800],"intervaller":[{"niva":"under","handling":null,"kommentar":"894bfe3e-59d0-320c-f2c7-afe4b3e4f316"},{"niva":"innenfor","handling":null,"kommentar":"40e5e203-083d-d84a-ce36-9de53e1fbbca"},{"niva":"over","handling":"ring_rekvirent","kommentar":"dc4b1ee3-3e06-4f3d-e23f-d96ea15c7d7e"}],"ringegrense":1800,"cutoff":{"innledning":"e840c491-c856-a180-c5e6-f2eb43cf5b54","kommentar":"40e5e203-083d-d84a-ce36-9de53e1fbbca"},"kommentarer":[{"id":"894bfe3e-59d0-320c-f2c7-afe4b3e4f316","tekst":"Manglende etterlevelse? Er riktig analyse rekvirert? Referanseområdet er basert på summen av mianserin og desmetylmianserin ved bruk av 60–120 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"40e5e203-083d-d84a-ce36-9de53e1fbbca","tekst":"Referanseområdet er basert på summen av mianserin og desmetylmianserin ved bruk av 60–120 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"dc4b1ee3-3e06-4f3d-e23f-d96ea15c7d7e","tekst":"Potensielt toksisk konsentrasjon. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no). Referanseområdet er basert på summen av mianserin og desmetylmianserin ved bruk av 60–120 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon."},{"id":"e840c491-c856-a180-c5e6-f2eb43cf5b54","tekst":"Prøven inneholder en lav konsentrasjon av mianserin og/eller desmetylmianserin som ligger under påvisningsgrensen."}]}},
{"kilde":"Importert fra kommentarer.pdf, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"MTZ","enhet":"nmol/L","desimaler":0,"skillepunkter":[10,700],"intervaller":[{"niva":"under","handling":null,"kommentar":"2aa4b2b6-0162-bc60-d118-ae13bc8050ba"},{"niva":"innenfor","handling":null,"kommentar":"2c2bed2e-de89-dc5e-25d8-0107d66abb1c"},{"niva":"over","handling":"ring_rekvirent","kommentar":"3fc77d65-717a-5a83-02c4-095f2a9edd02"}],"ringegrense":700,"cutoff":{"innledning":"e19062b9-5018-409f-1c06-d17916799bee","kommentar":"2c2bed2e-de89-dc5e-25d8-0107d66abb1c"},"kommentarer":[{"id":"2aa4b2b6-0162-bc60-d118-ae13bc8050ba","tekst":"Manglende etterlevelse? Er riktig analyse rekvirert? Referanseområdet for mirtazapin er basert på bruk av 15–60 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"2c2bed2e-de89-dc5e-25d8-0107d66abb1c","tekst":"Referanseområdet for mirtazapin er basert på bruk av 15–60 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"3fc77d65-717a-5a83-02c4-095f2a9edd02","tekst":"Potensielt toksisk konsentrasjon. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no). Referanseområdet for mirtazapin er basert på bruk av 15–60 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon."},{"id":"e19062b9-5018-409f-1c06-d17916799bee","tekst":"Prøven inneholder en lav konsentrasjon av mirtazapin som ligger under påvisningsgrensen."}]}},
{"kilde":"Importert fra AHT.docx, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"NIFE","enhet":"nmol/L","desimaler":0,"skillepunkter":[20,600],"intervaller":[{"niva":"under","handling":null,"kommentar":"04b4231e-e75c-3ea4-eea6-d69c8f8f6d8b"},{"niva":"innenfor","handling":null,"kommentar":"83132736-ad5c-bfad-b389-079bd3acda14"},{"niva":"over","handling":null,"kommentar":"07136463-756e-39bb-f7a6-f3ee938f6ec3"}],"ringegrense":null,"cutoff":null,"kommentarer":[{"id":"04b4231e-e75c-3ea4-eea6-d69c8f8f6d8b","tekst":"Mangelfull medikamentetterlevelse? Farmakokinetiske avvik? Referanseområdet for nifedipin er basert på bruk av 20–60 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"83132736-ad5c-bfad-b389-079bd3acda14","tekst":"Referanseområdet for nifedipin er basert på bruk av 20–60 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"07136463-756e-39bb-f7a6-f3ee938f6ec3","tekst":"Potensielt toksisk konsentrasjon. Referanseområdet for nifedipin er basert på bruk av 20–60 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."}]}},
{"kilde":"Importert fra kommentarer.pdf, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"NOR","enhet":"nmol/L","desimaler":0,"skillepunkter":[10,1200],"intervaller":[{"niva":"under","handling":null,"kommentar":"3ab493d1-952c-0cd0-90c9-caf75559f1b6"},{"niva":"innenfor","handling":null,"kommentar":"1cc3e2c0-bad5-35c5-8c52-444ad3c67bd1"},{"niva":"over","handling":"ring_rekvirent","kommentar":"bcb2f082-153d-a331-1cd6-3c2e97537c5f"}],"ringegrense":1200,"cutoff":{"innledning":"ca83be87-0c99-3c07-cbd4-ede151c52040","kommentar":"1cc3e2c0-bad5-35c5-8c52-444ad3c67bd1"},"kommentarer":[{"id":"3ab493d1-952c-0cd0-90c9-caf75559f1b6","tekst":"Manglende etterlevelse? Er riktig analyse rekvirert? Referanseområdet for nortriptylin er basert på prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"1cc3e2c0-bad5-35c5-8c52-444ad3c67bd1","tekst":"Referanseområdet for nortriptylin er basert på prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"bcb2f082-153d-a331-1cd6-3c2e97537c5f","tekst":"Potensielt toksisk konsentrasjon. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no). Referanseområdet for nortriptylin er basert på prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon."},{"id":"ca83be87-0c99-3c07-cbd4-ede151c52040","tekst":"Prøven inneholder en lav konsentrasjon av nortriptylin som ligger under påvisningsgrensen."}]}},
{"kilde":"Importert fra kommentarer.pdf, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"OLAN","enhet":"nmol/L","desimaler":0,"skillepunkter":[10,400],"intervaller":[{"niva":"under","handling":null,"kommentar":"21588223-67f9-e5fc-be28-8051a1de46e1"},{"niva":"innenfor","handling":null,"kommentar":"2c514620-96f3-3949-deda-5f936103f202"},{"niva":"over","handling":"ring_rekvirent","kommentar":"2d3a9469-a034-616c-b4c9-1e5404f5c8d1"}],"ringegrense":400,"cutoff":{"innledning":"c7c14f35-e9c4-4a4b-dc0b-1bf9552c7d30","kommentar":"2c514620-96f3-3949-deda-5f936103f202"},"kommentarer":[{"id":"21588223-67f9-e5fc-be28-8051a1de46e1","tekst":"Manglende etterlevelse? Er riktig analyse rekvirert? Referanseområdet for olanzapin er basert på bruk av 5–30 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Ved depot anbefales prøvetaking 0–2 dager før neste injeksjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"2c514620-96f3-3949-deda-5f936103f202","tekst":"Referanseområdet for olanzapin er basert på bruk av 5–30 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Ved depot anbefales prøvetaking 0–2 dager før neste injeksjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"2d3a9469-a034-616c-b4c9-1e5404f5c8d1","tekst":"Potensielt toksisk konsentrasjon. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no). Referanseområdet for olanzapin er basert på bruk av 5–30 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Ved depot anbefales prøvetaking 0–2 dager før neste injeksjon."},{"id":"c7c14f35-e9c4-4a4b-dc0b-1bf9552c7d30","tekst":"Prøven inneholder en lav konsentrasjon av olanzapin som ligger under påvisningsgrensen."}]}},
{"kilde":"Importert fra kommentarer.pdf, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"PALI","enhet":"nmol/L","desimaler":0,"skillepunkter":[10,240],"intervaller":[{"niva":"under","handling":null,"kommentar":"ac991252-a19e-3e2a-ff12-f78679d59606"},{"niva":"innenfor","handling":null,"kommentar":"13cc0531-6f50-52cd-acea-f9fe7cf032fa"},{"niva":"over","handling":"ring_rekvirent","kommentar":"3f5b4b08-59b5-a16e-4f90-5cf7e946b8ff"}],"ringegrense":240,"cutoff":{"innledning":"3873286e-f91a-fc15-3065-dd12879667c9","kommentar":"13cc0531-6f50-52cd-acea-f9fe7cf032fa"},"kommentarer":[{"id":"ac991252-a19e-3e2a-ff12-f78679d59606","tekst":"Er riktig analyse rekvirert? Referanseområdet for paliperidon er basert på prøvetaking 0–2 dager før neste depotinjeksjon og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"13cc0531-6f50-52cd-acea-f9fe7cf032fa","tekst":"Referanseområdet for paliperidon er basert på prøvetaking 0–2 dager før neste depotinjeksjon og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"3f5b4b08-59b5-a16e-4f90-5cf7e946b8ff","tekst":"Potensielt toksisk konsentrasjon. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no). Referanseområdet for paliperidon er basert på prøvetaking 0–2 dager før neste depotinjeksjon og oppnådd likevektskonsentrasjon."},{"id":"3873286e-f91a-fc15-3065-dd12879667c9","tekst":"Prøven inneholder en lav konsentrasjon av paliperidon (hydroksyrisperidon) som ligger under påvisningsgrensen."}]}},
{"kilde":"Importert fra kommentarer.pdf, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"PARO","enhet":"nmol/L","desimaler":0,"skillepunkter":[10,800],"intervaller":[{"niva":"under","handling":null,"kommentar":"04be102a-77aa-ac99-6935-03d556666c89"},{"niva":"innenfor","handling":null,"kommentar":"d4ac44a0-e665-8fdb-4f22-24c5aae845f3"},{"niva":"over","handling":"ring_rekvirent","kommentar":"aacf23c3-e4c0-0f17-0bc8-fdf70293498b"}],"ringegrense":800,"cutoff":{"innledning":"14a56582-999b-b69c-30a4-f4da4ea00a7d","kommentar":"d4ac44a0-e665-8fdb-4f22-24c5aae845f3"},"kommentarer":[{"id":"04be102a-77aa-ac99-6935-03d556666c89","tekst":"Manglende etterlevelse? Er riktig analyse rekvirert? Referanseområdet for paroksetin er basert på bruk av 20–60 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"d4ac44a0-e665-8fdb-4f22-24c5aae845f3","tekst":"Referanseområdet for paroksetin er basert på bruk av 20–60 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"aacf23c3-e4c0-0f17-0bc8-fdf70293498b","tekst":"Potensielt toksisk konsentrasjon. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no). Referanseområdet for paroksetin er basert på bruk av 20–60 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon."},{"id":"14a56582-999b-b69c-30a4-f4da4ea00a7d","tekst":"Prøven inneholder en lav konsentrasjon av paroksetin som ligger under påvisningsgrensen."}]}},
{"kilde":"Importert fra kommentarer.pdf, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"PERF","enhet":"nmol/L","desimaler":1,"skillepunkter":[0.6,14],"intervaller":[{"niva":"under","handling":null,"kommentar":"5fa9b111-eeb5-e6dc-603c-f02336876ab5"},{"niva":"innenfor","handling":null,"kommentar":"18b3e0d3-707e-1caf-d837-e5204ff00181"},{"niva":"over","handling":"ring_rekvirent","kommentar":"68252b94-a052-b1c0-70c3-dc165e39ef41"}],"ringegrense":14,"cutoff":{"innledning":"70cb89f3-2808-b4a9-c39a-4ea730dbe668","kommentar":"18b3e0d3-707e-1caf-d837-e5204ff00181"},"kommentarer":[{"id":"5fa9b111-eeb5-e6dc-603c-f02336876ab5","tekst":"Manglende etterlevelse? Er riktig analyse rekvirert? Referanseområdet for perfenazin er basert på bruk av 4–32 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Ved depot anbefales prøvetaking 0–2 dager før neste injeksjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"18b3e0d3-707e-1caf-d837-e5204ff00181","tekst":"Referanseområdet for perfenazin er basert på bruk av 4–32 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Ved depot anbefales prøvetaking 0–2 dager før neste injeksjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"68252b94-a052-b1c0-70c3-dc165e39ef41","tekst":"Potensielt toksisk konsentrasjon. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no). Referanseområdet for perfenazin er basert på bruk av 4–32 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Ved depot anbefales prøvetaking 0–2 dager før neste injeksjon."},{"id":"70cb89f3-2808-b4a9-c39a-4ea730dbe668","tekst":"Prøven inneholder en lav konsentrasjon av perfenazin som ligger under påvisningsgrensen."}]}},
{"kilde":"Importert fra AHT.docx, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"RAMAT","enhet":"nmol/L","desimaler":0,"skillepunkter":[4,240],"intervaller":[{"niva":"under","handling":null,"kommentar":"a7f492b4-2955-f151-718f-f0fa38c94445"},{"niva":"innenfor","handling":null,"kommentar":"ff1396d2-45a2-58fe-4595-a57546f79bd3"},{"niva":"over","handling":null,"kommentar":"89222f75-2cc6-5382-0546-66fef8db09d4"}],"ringegrense":null,"cutoff":null,"kommentarer":[{"id":"a7f492b4-2955-f151-718f-f0fa38c94445","tekst":"Mangelfull medikamentetterlevelse? Farmakokinetiske avvik? Ramiprilat er den aktive metabolitten av ramipril. Referanseområdet for ramiprilat er basert på bruk av 2,5–10 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"ff1396d2-45a2-58fe-4595-a57546f79bd3","tekst":"Ramiprilat er den aktive metabolitten av ramipril. Referanseområdet for ramiprilat er basert på bruk av 2,5–10 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"89222f75-2cc6-5382-0546-66fef8db09d4","tekst":"Potensielt toksisk konsentrasjon. Ramiprilat er den aktive metabolitten av ramipril. Referanseområdet for ramiprilat er basert på bruk av 2,5–10 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."}]}}
]$data$;
  administrator uuid;
  import jsonb;
  status public.objektstatus;
begin
  if md5(importdata) <> '71970def42698852b1d927e9855d4d96' then
    raise exception 'Importdataene er ikke de som ble laget: kontrollsummen stemmer ikke.';
  end if;
  select p.id into administrator from public.profiles p where p.username = 'peohol' and p.role = 'admin';
  if administrator is null then
    raise notice 'Fant ingen administrator med brukernavnet %.', 'peohol';
    return;
  end if;
  perform set_config('request.jwt.claims', jsonb_build_object('sub', administrator, 'role', 'authenticated')::text, true);

  for import in
    select e.v from jsonb_array_elements(importdata::jsonb) with ordinality e(v, nr) order by e.nr
  loop
    if exists (
      select 1 from public.intervallregelsett s
      where s.tilstand = 'utkast' and s.analyttkode = import #>> '{regelsett,analyttkode}'
    ) then
      raise notice '% har alt et regelsett og hoppes over.', import #>> '{regelsett,analyttkode}';
      continue;
    end if;
    perform set_config('far.revisjonskilde', import ->> 'kilde', true);
    status := public.opprett_utkast('intervallregelsett', import -> 'regelsett');
    perform public.publiser_utkast(status.id, status.revisjon);
  end loop;

  perform set_config('far.revisjonskilde', '', true);
end
$import$;