-- Regelsettene for de enkle konsentrasjonsreglene
do $import$
declare
  importdata constant text := $data$[
{"kilde":"Importert fra kommentarer.pdf, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"AMIS","enhet":"nmol/L","desimaler":0,"skillepunkter":[10,1800],"intervaller":[{"niva":"under","handling":null,"kommentar":"68df11d8-0ee9-b48b-fd2f-4c69ac0af993"},{"niva":"innenfor","handling":null,"kommentar":"16262032-c7c7-72a0-2675-5fd9081b6f9f"},{"niva":"over","handling":"ring_rekvirent","kommentar":"dfbcdd07-0b0d-19a9-316c-37f5db722887"}],"ringegrense":1800,"cutoff":{"innledning":"f4139c18-87e3-fc3e-b154-0161cd4eedba","kommentar":"16262032-c7c7-72a0-2675-5fd9081b6f9f"},"kommentarer":[{"id":"68df11d8-0ee9-b48b-fd2f-4c69ac0af993","tekst":"Manglende etterlevelse? Er riktig analyse rekvirert? Referanseområdet for amisulprid er basert på bruk av 50–1200 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"16262032-c7c7-72a0-2675-5fd9081b6f9f","tekst":"Referanseområdet for amisulprid er basert på bruk av 50–1200 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"dfbcdd07-0b0d-19a9-316c-37f5db722887","tekst":"Potensielt toksisk konsentrasjon. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no). Referanseområdet for amisulprid er basert på bruk av 50–1200 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon."},{"id":"f4139c18-87e3-fc3e-b154-0161cd4eedba","tekst":"Prøven inneholder en lav konsentrasjon av amisulprid som ligger under påvisningsgrensen."}]}},
{"kilde":"Importert fra AHT.docx, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"AMLO","enhet":"nmol/L","desimaler":0,"skillepunkter":[10,280],"intervaller":[{"niva":"under","handling":null,"kommentar":"3d7a7b4c-98ab-2c77-4df9-ab3280381bd1"},{"niva":"innenfor","handling":null,"kommentar":"b20ccc1d-765a-ffdf-4c06-40399e661fde"},{"niva":"over","handling":null,"kommentar":"22e7b890-7abd-fe92-129a-dbf98f735785"}],"ringegrense":null,"cutoff":null,"kommentarer":[{"id":"3d7a7b4c-98ab-2c77-4df9-ab3280381bd1","tekst":"Mangelfull medikamentetterlevelse? Farmakokinetiske avvik? Referanseområdet for amlodipin er basert på bruk av 5–10 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"b20ccc1d-765a-ffdf-4c06-40399e661fde","tekst":"Referanseområdet for amlodipin er basert på bruk av 5–10 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"22e7b890-7abd-fe92-129a-dbf98f735785","tekst":"Potensielt toksisk konsentrasjon. Referanseområdet for amlodipin er basert på bruk av 5–10 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."}]}},
{"kilde":"Importert fra kommentarer.pdf, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"AMTNORSUM","enhet":"nmol/L","desimaler":0,"skillepunkter":[10,1800],"intervaller":[{"niva":"under","handling":null,"kommentar":"24012b1b-d54d-1d45-26a2-8c17be8fe2ab"},{"niva":"innenfor","handling":null,"kommentar":"29c7460d-c011-5c9c-1846-7cfc894965c4"},{"niva":"over","handling":"ring_rekvirent","kommentar":"715abfcf-ebab-6432-b692-b254b79bf31d"}],"ringegrense":1800,"cutoff":{"innledning":"131e2a84-9142-270b-dadd-210f57e94cf9","kommentar":"29c7460d-c011-5c9c-1846-7cfc894965c4"},"kommentarer":[{"id":"24012b1b-d54d-1d45-26a2-8c17be8fe2ab","tekst":"Manglende etterlevelse? Er riktig analyse rekvirert? Referanseområdet er basert på summen av amitriptylin og nortriptylin, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"29c7460d-c011-5c9c-1846-7cfc894965c4","tekst":"Referanseområdet er basert på summen av amitriptylin og nortriptylin, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"715abfcf-ebab-6432-b692-b254b79bf31d","tekst":"Potensielt toksisk konsentrasjon. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no). Referanseområdet er basert på summen av amitriptylin og nortriptylin, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon."},{"id":"131e2a84-9142-270b-dadd-210f57e94cf9","tekst":"Prøven inneholder en lav konsentrasjon av amitriptylin og/eller nortriptylin som ligger under påvisningsgrensen."}]}},
{"kilde":"Importert fra kommentarer.pdf, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"ARISUM","enhet":"nmol/L","desimaler":0,"skillepunkter":[10,2200],"intervaller":[{"niva":"under","handling":null,"kommentar":"7f72b862-b172-20e7-2d5b-76038452ec15"},{"niva":"innenfor","handling":null,"kommentar":"586f6d28-10d5-1fa9-06a6-737919cda441"},{"niva":"over","handling":"ring_rekvirent","kommentar":"a0d69724-8c26-2695-639e-1e3f8339d80c"}],"ringegrense":2200,"cutoff":{"innledning":"7e34f0e3-c6e4-79da-81dd-b60377ad0b1a","kommentar":"586f6d28-10d5-1fa9-06a6-737919cda441"},"kommentarer":[{"id":"7f72b862-b172-20e7-2d5b-76038452ec15","tekst":"Manglende etterlevelse? Er riktig analyse rekvirert? Referanseområdet er basert på summen av aripiprazol + dehydroaripiprazol ved bruk av 10–30 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Ved depot anbefales prøvetaking 0–2 dager før neste injeksjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"586f6d28-10d5-1fa9-06a6-737919cda441","tekst":"Referanseområdet er basert på summen av aripiprazol + dehydroaripiprazol ved bruk av 10–30 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Ved depot anbefales prøvetaking 0–2 dager før neste injeksjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"a0d69724-8c26-2695-639e-1e3f8339d80c","tekst":"Potensielt toksisk konsentrasjon. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no). Referanseområdet er basert på summen av aripiprazol + dehydroaripiprazol ved bruk av 10–30 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Ved depot anbefales prøvetaking 0–2 dager før neste injeksjon."},{"id":"7e34f0e3-c6e4-79da-81dd-b60377ad0b1a","tekst":"Prøven inneholder en lav konsentrasjon av aripiprazol og/eller dehydroaripiprazol som ligger under påvisningsgrensen."}]}},
{"kilde":"Importert fra AHT.docx, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"ATEN","enhet":"nmol/L","desimaler":0,"skillepunkter":[75,3000],"intervaller":[{"niva":"under","handling":null,"kommentar":"e38781ec-ca8f-3d44-0af4-416b5121ac55"},{"niva":"innenfor","handling":null,"kommentar":"7a0b5764-1cbe-9a1a-048c-915a34e47aa1"},{"niva":"over","handling":null,"kommentar":"c29ae07c-86c1-0c7d-2ad4-7c300cd22741"}],"ringegrense":null,"cutoff":null,"kommentarer":[{"id":"e38781ec-ca8f-3d44-0af4-416b5121ac55","tekst":"Mangelfull medikamentetterlevelse? Farmakokinetiske avvik? Referanseområdet for atenolol er basert på bruk av 50–100 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"7a0b5764-1cbe-9a1a-048c-915a34e47aa1","tekst":"Referanseområdet for atenolol er basert på bruk av 50–100 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"c29ae07c-86c1-0c7d-2ad4-7c300cd22741","tekst":"Potensielt toksisk konsentrasjon. Referanseområdet for atenolol er basert på bruk av 50–100 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."}]}},
{"kilde":"Importert fra AHT.docx, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"BEND","enhet":"nmol/L","desimaler":1,"skillepunkter":[1.5,120],"intervaller":[{"niva":"under","handling":null,"kommentar":"15bd21e2-af1d-142b-8955-8b8ed87419a9"},{"niva":"innenfor","handling":null,"kommentar":"2c94b929-ebda-9f4c-59a6-6c05f061f553"},{"niva":"over","handling":null,"kommentar":"98a9d82c-39e6-c34d-7cd8-8799f442fe05"}],"ringegrense":null,"cutoff":null,"kommentarer":[{"id":"15bd21e2-af1d-142b-8955-8b8ed87419a9","tekst":"Mangelfull medikamentetterlevelse? Farmakokinetiske avvik? Referanseområdet for bendroflumetiazid er basert på bruk av 1,25–5 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"2c94b929-ebda-9f4c-59a6-6c05f061f553","tekst":"Referanseområdet for bendroflumetiazid er basert på bruk av 1,25–5 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"98a9d82c-39e6-c34d-7cd8-8799f442fe05","tekst":"Potensielt toksisk konsentrasjon. Referanseområdet for bendroflumetiazid er basert på bruk av 1,25–5 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."}]}},
{"kilde":"Importert fra AHT.docx, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"BISO","enhet":"nmol/L","desimaler":0,"skillepunkter":[10,800],"intervaller":[{"niva":"under","handling":null,"kommentar":"7d2e2180-ee45-be08-9d07-2689d74c4779"},{"niva":"innenfor","handling":null,"kommentar":"ed9e6cdb-2068-89a9-c817-c652b8793c30"},{"niva":"over","handling":null,"kommentar":"58358d62-8cef-aba0-ae63-0ffebed98813"}],"ringegrense":null,"cutoff":null,"kommentarer":[{"id":"7d2e2180-ee45-be08-9d07-2689d74c4779","tekst":"Mangelfull medikamentetterlevelse? Farmakokinetiske avvik? Referanseområdet for bisoprolol er basert på bruk av 5–20 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"ed9e6cdb-2068-89a9-c817-c652b8793c30","tekst":"Referanseområdet for bisoprolol er basert på bruk av 5–20 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"58358d62-8cef-aba0-ae63-0ffebed98813","tekst":"Potensielt toksisk konsentrasjon. Referanseområdet for bisoprolol er basert på bruk av 5–20 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."}]}},
{"kilde":"Importert fra kommentarer.pdf, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"BREK","enhet":"nmol/L","desimaler":0,"skillepunkter":[10,600],"intervaller":[{"niva":"under","handling":null,"kommentar":"e0f14a9b-ba7e-847a-b245-11d8f6ef7b07"},{"niva":"innenfor","handling":null,"kommentar":"12b3c06e-d677-78aa-2355-9369378a7fbc"},{"niva":"over","handling":"ring_rekvirent","kommentar":"ecafef40-f972-53f1-db02-8b861acd5dff"}],"ringegrense":600,"cutoff":{"innledning":"2f9051f5-f2f9-29a3-f0fa-d1b4f68c806c","kommentar":"12b3c06e-d677-78aa-2355-9369378a7fbc"},"kommentarer":[{"id":"e0f14a9b-ba7e-847a-b245-11d8f6ef7b07","tekst":"Manglende etterlevelse? Er riktig analyse rekvirert? Referanseområdet for brekspiprazol er basert på bruk av 1–4 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysen er ny og begrenset dokumentasjon foreligger. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"12b3c06e-d677-78aa-2355-9369378a7fbc","tekst":"Referanseområdet for brekspiprazol er basert på bruk av 1–4 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysen er ny og begrenset dokumentasjon foreligger. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"ecafef40-f972-53f1-db02-8b861acd5dff","tekst":"Potensielt toksisk konsentrasjon. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no). Referanseområdet for brekspiprazol er basert på bruk av 1–4 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysen er ny og begrenset dokumentasjon foreligger."},{"id":"2f9051f5-f2f9-29a3-f0fa-d1b4f68c806c","tekst":"Prøven inneholder en lav konsentrasjon av brekspiprazol som ligger under påvisningsgrensen."}]}},
{"kilde":"Importert fra AHT.docx, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"BUME","enhet":"nmol/L","desimaler":0,"skillepunkter":[10,1600],"intervaller":[{"niva":"under","handling":null,"kommentar":"411e465a-0be5-0744-d230-e4af145211ab"},{"niva":"innenfor","handling":null,"kommentar":"649f3208-7cfa-36d9-a899-47a22a2fa56e"},{"niva":"over","handling":null,"kommentar":"9adc5ebb-2e30-d199-bc8e-404590c5a9d7"}],"ringegrense":null,"cutoff":null,"kommentarer":[{"id":"411e465a-0be5-0744-d230-e4af145211ab","tekst":"Bumetanid er ikke påvisbart medikamentfastende, men kan påvises 1–6 timer etter inntak. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"649f3208-7cfa-36d9-a899-47a22a2fa56e","tekst":"Bumetanid kan påvises 1–6 timer etter inntak. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"9adc5ebb-2e30-d199-bc8e-404590c5a9d7","tekst":"Potensielt toksisk konsentrasjon. Bumetanid er ikke påvisbart medikamentfastende, men kan påvises 1–6 timer etter inntak. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."}]}},
{"kilde":"Importert fra kommentarer.pdf, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"CITAL","enhet":"nmol/L","desimaler":0,"skillepunkter":[10,700],"intervaller":[{"niva":"under","handling":null,"kommentar":"a7aeb06d-f8ee-974f-b564-d7dc91a280ff"},{"niva":"innenfor","handling":null,"kommentar":"46e95299-e854-49bc-6469-333d5d7bf289"},{"niva":"over","handling":"ring_rekvirent","kommentar":"0e9ad420-279d-6362-98d3-4cc26607ac23"}],"ringegrense":700,"cutoff":{"innledning":"9ef8a0fe-dcaf-46f3-2d20-657d0cf40f41","kommentar":"46e95299-e854-49bc-6469-333d5d7bf289"},"kommentarer":[{"id":"a7aeb06d-f8ee-974f-b564-d7dc91a280ff","tekst":"Manglende etterlevelse? Er riktig analyse rekvirert? Referanseområdet for citalopram er basert på bruk av 20–60 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"46e95299-e854-49bc-6469-333d5d7bf289","tekst":"Referanseområdet for citalopram er basert på bruk av 20–60 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"0e9ad420-279d-6362-98d3-4cc26607ac23","tekst":"Potensielt toksisk konsentrasjon. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no). Referanseområdet for citalopram er basert på bruk av 20–60 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon."},{"id":"9ef8a0fe-dcaf-46f3-2d20-657d0cf40f41","tekst":"Prøven inneholder en lav konsentrasjon av citalopram som ligger under påvisningsgrensen."}]}}
]$data$;
  administrator uuid;
  import jsonb;
  status public.objektstatus;
begin
  if md5(importdata) <> 'c3471b9d8bfbd70dbf3161a3ff46bcbf' then
    raise exception 'Importdataene er ikke de som ble laget: kontrollsummen stemmer ikke.';
  end if;
  select p.id into administrator from public.profiles p where p.username = 'peohol' and p.role = 'admin';
  if administrator is null then
    raise notice 'Fant ingen administrator med brukernavnet %.', 'peohol';
    return;
  end if;
  perform set_config('request.jwt.claims', jsonb_build_object('sub', administrator, 'role', 'authenticated')::text, true);

  for import in
    select e.v from jsonb_array_elements(importdata::jsonb) with ordinality e(v, nr) order by e.nr
  loop
    if exists (
      select 1 from public.intervallregelsett s
      where s.tilstand = 'utkast' and s.analyttkode = import #>> '{regelsett,analyttkode}'
    ) then
      raise notice '% har alt et regelsett og hoppes over.', import #>> '{regelsett,analyttkode}';
      continue;
    end if;
    perform set_config('far.revisjonskilde', import ->> 'kilde', true);
    status := public.opprett_utkast('intervallregelsett', import -> 'regelsett');
    perform public.publiser_utkast(status.id, status.revisjon);
  end loop;

  perform set_config('far.revisjonskilde', '', true);
end
$import$;