-- Regelsettene for de enkle konsentrasjonsreglene
do $import$
declare
  importdata constant text := $data$[
{"kilde":"Importert fra AHT.docx, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"FURO","enhet":"nmol/L","desimaler":0,"skillepunkter":[50,40000],"intervaller":[{"niva":"under","handling":null,"kommentar":"e6cfbbbe-e96c-9eb8-c660-646a973f758e"},{"niva":"innenfor","handling":null,"kommentar":"2727aa47-6b7e-f67d-dcc8-475e4bf5b367"},{"niva":"over","handling":null,"kommentar":"442daa36-efdc-8fd0-fbb8-17a22f4e4c87"}],"ringegrense":null,"cutoff":null,"kommentarer":[{"id":"e6cfbbbe-e96c-9eb8-c660-646a973f758e","tekst":"Furosemid er ikke påvisbart medikamentfastende, men kan påvises 1–6 timer etter inntak. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"2727aa47-6b7e-f67d-dcc8-475e4bf5b367","tekst":"Furosemid kan påvises 1–6 timer etter inntak. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"442daa36-efdc-8fd0-fbb8-17a22f4e4c87","tekst":"Potensielt toksisk konsentrasjon. Furosemid er ikke påvisbart medikamentfastende, men kan påvises 1–6 timer etter inntak. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."}]}},
{"kilde":"Importert fra kommentarer.pdf, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"HALO","enhet":"nmol/L","desimaler":0,"skillepunkter":[1,40],"intervaller":[{"niva":"under","handling":null,"kommentar":"c7d16640-f484-33da-351c-37800a92515e"},{"niva":"innenfor","handling":null,"kommentar":"2f0d9a85-ed85-f4e0-a12d-52b6839d954d"},{"niva":"over","handling":"ring_rekvirent","kommentar":"177308f9-2543-9559-8190-d00ee465a688"}],"ringegrense":40,"cutoff":{"innledning":"dca2b4da-7b73-2c27-bd36-abcc40521847","kommentar":"2f0d9a85-ed85-f4e0-a12d-52b6839d954d"},"kommentarer":[{"id":"c7d16640-f484-33da-351c-37800a92515e","tekst":"Manglende etterlevelse? Er riktig analyse rekvirert? Referanseområdet for haloperidol er basert på bruk av 1–20 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Ved depot anbefales prøvetaking 0–2 dager før neste injeksjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"2f0d9a85-ed85-f4e0-a12d-52b6839d954d","tekst":"Referanseområdet for haloperidol er basert på bruk av 1–20 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Ved depot anbefales prøvetaking 0–2 dager før neste injeksjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"177308f9-2543-9559-8190-d00ee465a688","tekst":"Potensielt toksisk konsentrasjon. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no). Referanseområdet for haloperidol er basert på bruk av 1–20 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Ved depot anbefales prøvetaking 0–2 dager før neste injeksjon."},{"id":"dca2b4da-7b73-2c27-bd36-abcc40521847","tekst":"Prøven inneholder en lav konsentrasjon av haloperidol som ligger under påvisningsgrensen."}]}},
{"kilde":"Importert fra kommentarer.pdf, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"HBUP","enhet":"nmol/L","desimaler":0,"skillepunkter":[100,8000],"intervaller":[{"niva":"under","handling":null,"kommentar":"bc40c01a-96af-924f-9c05-5846b2895d9d"},{"niva":"innenfor","handling":null,"kommentar":"bccc043c-bcf0-a879-e7db-f0fa5cc1df95"},{"niva":"over","handling":"ring_rekvirent","kommentar":"d48c6c27-9282-f80e-9d63-9194f861ee31"}],"ringegrense":8000,"cutoff":{"innledning":"af75d1db-4c62-a8a3-0091-993d8a636a9e","kommentar":"bccc043c-bcf0-a879-e7db-f0fa5cc1df95"},"kommentarer":[{"id":"bc40c01a-96af-924f-9c05-5846b2895d9d","tekst":"Manglende etterlevelse? Er riktig analyse rekvirert? Siden bupropion er ustabil i serum analyseres kun den aktive metabolitten hydroksybupropion. Referanseområdet er basert på prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"bccc043c-bcf0-a879-e7db-f0fa5cc1df95","tekst":"Siden bupropion er ustabil i serum analyseres kun den aktive metabolitten hydroksybupropion. Referanseområdet er basert på prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"d48c6c27-9282-f80e-9d63-9194f861ee31","tekst":"Potensielt toksisk konsentrasjon. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no). Siden bupropion er ustabil i serum analyseres kun den aktive metabolitten hydroksybupropion. Referanseområdet er basert på prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon."},{"id":"af75d1db-4c62-a8a3-0091-993d8a636a9e","tekst":"Prøven inneholder en lav konsentrasjon av hydroksybupropion som ligger under påvisningsgrensen."}]}},
{"kilde":"Importert fra AHT.docx, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"HYDR","enhet":"nmol/L","desimaler":0,"skillepunkter":[15,1200],"intervaller":[{"niva":"under","handling":null,"kommentar":"076f7a16-d3df-9cc2-8b57-0840b21f8ea8"},{"niva":"innenfor","handling":null,"kommentar":"2e9f9cfb-0cbe-7177-058c-c2d05cad13de"},{"niva":"over","handling":null,"kommentar":"6b498f0b-3222-82e3-7342-364876a86508"}],"ringegrense":null,"cutoff":null,"kommentarer":[{"id":"076f7a16-d3df-9cc2-8b57-0840b21f8ea8","tekst":"Mangelfull medikamentetterlevelse? Farmakokinetiske avvik? Referanseområdet for hydroklortiazid er basert på bruk av 12,5–50 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"2e9f9cfb-0cbe-7177-058c-c2d05cad13de","tekst":"Referanseområdet for hydroklortiazid er basert på bruk av 12,5–50 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"6b498f0b-3222-82e3-7342-364876a86508","tekst":"Potensielt toksisk konsentrasjon. Referanseområdet for hydroklortiazid er basert på bruk av 12,5–50 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."}]}},
{"kilde":"Importert fra AHT.docx, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"IRBE","enhet":"nmol/L","desimaler":0,"skillepunkter":[300,12000],"intervaller":[{"niva":"under","handling":null,"kommentar":"fffdde79-b3e9-0cce-b14c-b34c22d582ad"},{"niva":"innenfor","handling":null,"kommentar":"991f4319-2926-30a8-2888-25133c8af6a5"},{"niva":"over","handling":null,"kommentar":"b4b8f4f6-028b-8c34-c1fa-6a411008ac55"}],"ringegrense":null,"cutoff":null,"kommentarer":[{"id":"fffdde79-b3e9-0cce-b14c-b34c22d582ad","tekst":"Mangelfull medikamentetterlevelse? Farmakokinetiske avvik? Referanseområdet for irbesartan er basert på bruk av 150–300 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"991f4319-2926-30a8-2888-25133c8af6a5","tekst":"Referanseområdet for irbesartan er basert på bruk av 150–300 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"b4b8f4f6-028b-8c34-c1fa-6a411008ac55","tekst":"Potensielt toksisk konsentrasjon. Referanseområdet for irbesartan er basert på bruk av 150–300 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."}]}},
{"kilde":"Importert fra AHT.docx, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"KAND","enhet":"nmol/L","desimaler":0,"skillepunkter":[15,800],"intervaller":[{"niva":"under","handling":null,"kommentar":"8be81940-8704-f026-d99c-429174ed815e"},{"niva":"innenfor","handling":null,"kommentar":"24102d38-42ea-924a-1dab-6dc0a1c2e654"},{"niva":"over","handling":null,"kommentar":"bfc1b2a4-3ff4-c319-44fc-b3629876a348"}],"ringegrense":null,"cutoff":null,"kommentarer":[{"id":"8be81940-8704-f026-d99c-429174ed815e","tekst":"Mangelfull medikamentetterlevelse? Farmakokinetiske avvik? Referanseområdet for kandesartan er basert på bruk av 8–32 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"24102d38-42ea-924a-1dab-6dc0a1c2e654","tekst":"Referanseområdet for kandesartan er basert på bruk av 8–32 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"bfc1b2a4-3ff4-c319-44fc-b3629876a348","tekst":"Potensielt toksisk konsentrasjon. Referanseområdet for kandesartan er basert på bruk av 8–32 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."}]}},
{"kilde":"Importert fra AHT.docx, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"KANR","enhet":"nmol/L","desimaler":0,"skillepunkter":[15,1200],"intervaller":[{"niva":"under","handling":null,"kommentar":"b4a38cb2-4100-4a71-ce66-d5e687a8e18e"},{"niva":"innenfor","handling":null,"kommentar":"8e60be81-8a54-6a50-9c2f-fe379ca31a6b"},{"niva":"over","handling":null,"kommentar":"f55b33ad-8e12-8ff6-88be-97c7eedc0ab3"}],"ringegrense":null,"cutoff":null,"kommentarer":[{"id":"b4a38cb2-4100-4a71-ce66-d5e687a8e18e","tekst":"Mangelfull medikamentetterlevelse? Farmakokinetiske avvik? Kanrenon er den aktive metabolitten av spironolakton. Referanseområdet for kanrenon er basert på bruk av 25–100 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"8e60be81-8a54-6a50-9c2f-fe379ca31a6b","tekst":"Kanrenon er den aktive metabolitten av spironolakton. Referanseområdet for kanrenon er basert på bruk av 25–100 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"f55b33ad-8e12-8ff6-88be-97c7eedc0ab3","tekst":"Potensielt toksisk konsentrasjon. Kanrenon er den aktive metabolitten av spironolakton. Referanseområdet for kanrenon er basert på bruk av 25–100 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."}]}},
{"kilde":"Importert fra kommentarer.pdf, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"KARSUM","enhet":"nmol/L","desimaler":0,"skillepunkter":[2,300],"intervaller":[{"niva":"under","handling":null,"kommentar":"4ff365bf-faf2-5d2c-56e8-d272f06ebfe2"},{"niva":"innenfor","handling":null,"kommentar":"d0b4dbff-3dc1-d685-e8b1-78b38f9496fe"},{"niva":"over","handling":"ring_rekvirent","kommentar":"11782d88-96f9-21df-baa6-d7847ae13258"}],"ringegrense":300,"cutoff":{"innledning":"e8681c0c-a29b-f683-b569-584e7de2dbd1","kommentar":"d0b4dbff-3dc1-d685-e8b1-78b38f9496fe"},"kommentarer":[{"id":"4ff365bf-faf2-5d2c-56e8-d272f06ebfe2","tekst":"Manglende etterlevelse? Er riktig analyse rekvirert? Referanseområdet er basert på summen av kariprazin, desmetylkariprazin og didesmetylkariprazin ved bruk av 1,5–6 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysen er ny og begrenset dokumentasjon foreligger. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"d0b4dbff-3dc1-d685-e8b1-78b38f9496fe","tekst":"Referanseområdet er basert på summen av kariprazin, desmetylkariprazin og didesmetylkariprazin ved bruk av 1,5–6 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysen er ny og begrenset dokumentasjon foreligger. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"11782d88-96f9-21df-baa6-d7847ae13258","tekst":"Potensielt toksisk konsentrasjon. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no). Referanseområdet er basert på summen av kariprazin, desmetylkariprazin og didesmetylkariprazin ved bruk av 1,5–6 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysen er ny og begrenset dokumentasjon foreligger."},{"id":"e8681c0c-a29b-f683-b569-584e7de2dbd1","tekst":"Prøven inneholder en lav konsentrasjon av kariprazin, desmetylkariprazin og/eller didesmetylkariprazin som ligger under påvisningsgrensen."}]}},
{"kilde":"Importert fra AHT.docx, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"KARV","enhet":"nmol/L","desimaler":1,"skillepunkter":[2.5,200],"intervaller":[{"niva":"under","handling":null,"kommentar":"c58852c7-e238-b457-abd3-015c9ab55877"},{"niva":"innenfor","handling":null,"kommentar":"9ffd89ef-77a3-5db9-d529-30eeeaf14d23"},{"niva":"over","handling":null,"kommentar":"e7a918db-594b-9b40-e1e5-d6049a59d072"}],"ringegrense":null,"cutoff":null,"kommentarer":[{"id":"c58852c7-e238-b457-abd3-015c9ab55877","tekst":"Mangelfull medikamentetterlevelse? Farmakokinetiske avvik? Referanseområdet for karvedilol er basert på bruk av 12,5–50 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"9ffd89ef-77a3-5db9-d529-30eeeaf14d23","tekst":"Referanseområdet for karvedilol er basert på bruk av 12,5–50 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"e7a918db-594b-9b40-e1e5-d6049a59d072","tekst":"Potensielt toksisk konsentrasjon. Referanseområdet for karvedilol er basert på bruk av 12,5–50 mg daglig, prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."}]}},
{"kilde":"Importert fra kommentarer.pdf, via de statiske fortolkningsreglene i OUSFAR","regelsett":{"analyttkode":"KLORP","enhet":"nmol/L","desimaler":0,"skillepunkter":[5,1200],"intervaller":[{"niva":"under","handling":null,"kommentar":"f13755f7-4f06-f091-ec2a-5e84b20f6704"},{"niva":"innenfor","handling":null,"kommentar":"c49be8aa-699b-eca7-a237-abf7df7a8010"},{"niva":"over","handling":"ring_rekvirent","kommentar":"1d41f38b-44ca-1545-7e70-6229e8e844dc"}],"ringegrense":1200,"cutoff":{"innledning":"0fbd36ed-29be-083a-58e6-6a9164b531e8","kommentar":"c49be8aa-699b-eca7-a237-abf7df7a8010"},"kommentarer":[{"id":"f13755f7-4f06-f091-ec2a-5e84b20f6704","tekst":"Manglende etterlevelse? Er riktig analyse rekvirert? Referanseområdet er basert på prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Referanseområdet omfatter ikke bruk av klorprotiksen som primær antipsykotisk behandling. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"c49be8aa-699b-eca7-a237-abf7df7a8010","tekst":"Referanseområdet for klorprotiksen er basert på prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Referanseområdet omfatter ikke bruk av klorprotiksen som primær antipsykotisk behandling. Analysesvaret må alltid ses i sammenheng med klinikk. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no)."},{"id":"1d41f38b-44ca-1545-7e70-6229e8e844dc","tekst":"Potensielt toksisk konsentrasjon. Ved spørsmål kan rekvirent kontakte vakthavende lege ved Seksjon for klinisk farmakologi Ullevål (se ous.labfag.no). Referanseområdet for klorprotiksen er basert på prøvetaking 12–24 timer etter siste dose og oppnådd likevektskonsentrasjon. Referanseområdet omfatter ikke bruk av klorprotiksen som primær antipsykotisk behandling."},{"id":"0fbd36ed-29be-083a-58e6-6a9164b531e8","tekst":"Prøven inneholder en lav konsentrasjon av klorprotiksen som ligger under påvisningsgrensen."}]}}
]$data$;
  administrator uuid;
  import jsonb;
  status public.objektstatus;
begin
  if md5(importdata) <> '7c2eb56430f0a7e1d59ed0e0687b003c' then
    raise exception 'Importdataene er ikke de som ble laget: kontrollsummen stemmer ikke.';
  end if;
  select p.id into administrator from public.profiles p where p.username = 'peohol' and p.role = 'admin';
  if administrator is null then
    raise notice 'Fant ingen administrator med brukernavnet %.', 'peohol';
    return;
  end if;
  perform set_config('request.jwt.claims', jsonb_build_object('sub', administrator, 'role', 'authenticated')::text, true);

  for import in
    select e.v from jsonb_array_elements(importdata::jsonb) with ordinality e(v, nr) order by e.nr
  loop
    if exists (
      select 1 from public.intervallregelsett s
      where s.tilstand = 'utkast' and s.analyttkode = import #>> '{regelsett,analyttkode}'
    ) then
      raise notice '% har alt et regelsett og hoppes over.', import #>> '{regelsett,analyttkode}';
      continue;
    end if;
    perform set_config('far.revisjonskilde', import ->> 'kilde', true);
    status := public.opprett_utkast('intervallregelsett', import -> 'regelsett');
    perform public.publiser_utkast(status.id, status.revisjon);
  end loop;

  perform set_config('far.revisjonskilde', '', true);
end
$import$;